// Portuguese display names for the historically significant empires,
// kingdoms, civilizations and states found in the vendored GeoJSON
// snapshots (public/data/historical-basemaps). Keys must match the
// NAME/SUBJECTO property exactly as it appears in the source data —
// including the odd encoding/spelling variants the dataset itself has
// across different year files.
//
// Anything not listed here just falls back to the original English
// name — this is a curated subset, not a full translation of the
// dataset (see README).
//
// Entries present here are also treated as "always worth a label" and
// take priority over the area-based ranking in territoryLabels.ts, so
// historically important-but-small territories (Byzantium, Portugal,
// city-states...) don't get crowded out by huge sparsely-populated
// hunter-gatherer regions.
export const CURATED_TERRITORIES: Record<string, string> = {
  // Ancient Near East / Mediterranean
  Ur: "Suméria (Ur)",
  Elam: "Elão",
  Babylonia: "Babilônia",
  Assyria: "Assíria",
  Canaan: "Canaã",
  Minoan: "Civilização Minóica",
  Cycladic: "Civilização Cicládica",
  Hittites: "Hititas",
  Urartu: "Urartu",
  Phrygians: "Frígios",
  Thrace: "Trácia",
  Illyrians: "Ilírios",
  "Kingdom of David and Solomon": "Reino de Davi e Salomão",
  Arameans: "Arameus",
  "state societies and Aramaean kingdoms": "Sociedades estatais e reinos arameus",
  "Iranian pastoralists": "Pastores iranianos",
  "Gandhara grave culture": "Cultura de Gandara",
  "Indus valley civilization": "Civilização do Vale do Indo",
  Egypt: "Egito",
  "Achaemenid Empire": "Império Aquemênida",
  "Empire of Alexander": "Império de Alexandre",
  Macedonia: "Macedônia",
  "Macedon and Hellenic League": "Macedônia e Liga Helênica",
  "Greek city-states": "Cidades-Estado Gregas",
  Persia: "Pérsia",
  Arabia: "Arábia",
  Scythians: "Citas",
  Carthage: "Cartago",
  "Carthaginian Empire": "Império Cartaginês",
  Rome: "Roma",
  "Roman Empire": "Império Romano",
  "Rome (Diocletianus)": "Roma (Diocleciano)",
  "Seleucid Kingdom": "Reino Selêucida",
  "Ptolemaic Kingdom": "Reino Ptolomaico",
  "Byzantine Empire": "Império Bizantino",
  "Eastern Roman Empire": "Império Romano do Oriente",
  "Holy Roman Empire": "Sacro Império Romano-Germânico",
  "Papal States": "Estados Papais",
  "Roman Republic": "República Romana",
  "Rome (Maximian)": "Roma (Maximiano)",
  "Rome (Constantinus)": "Roma (Constantino)",
  Sarmates: "Sármatas",
  Cimerians: "Cimérios",
  "Hurrian Kingdoms": "Reinos Hurritas",

  // South / Central / East Asia (ancient–medieval)
  Xiongnu: "Xiongnu",
  Xia: "Dinastia Xia",
  Han: "Império Han",
  "Han Empire": "Império Han",
  "Kushan Empire": "Império Cuchana",
  "Kushan Principalities": "Principados Cuchanas",
  Kushites: "Cuchitas",
  Kush: "Reino de Cuxe",
  "Mauryan Empire": "Império Máuria",
  "Gupta Empire": "Império Gupta",
  "Parthian Empire": "Império Parta",
  "Sasanian Empire": "Império Sassânida",
  Jin: "Dinastia Jin",
  "Jin Empire": "Império Jin",
  "Sui Empire": "Dinastia Sui",
  Göktürks: "Canato Turco (Göktürks)",
  "Tang Empire": "Dinastia Tang",
  "Tibetan Empire": "Império Tibetano",
  "Song Empire": "Dinastia Song",
  "Abbasid Caliphate": "Califado Abássida",
  "Umayyad Caliphate": "Califado Omíada",
  "Ming Chinese Empire": "Dinastia Ming",
  "Manchu Empire": "Império Manchu",
  "Qing Empire": "Dinastia Qing",
  "Chinese Warlords": "Senhores da Guerra Chineses",
  "Chinese warlords": "Senhores da Guerra Chineses",
  "Sultanate of Delhi": "Sultanato de Deli",
  Vijayanagara: "Vijayanagara",
  "Chola state": "Império Chola",
  Cholas: "Império Chola",
  "Maratha Confederacy": "Confederação Marata",
  "Mughal Empire": "Império Mogol",
  "British Raj": "Raj Britânico (Índia)",
  "Khmer Empire": "Império Khmer",
  "Srivijaya Empire": "Império de Srivijaya",
  Champa: "Champa",
  "Đại Việt": "Đại Việt",
  Vietnam: "Vietnã",
  "Saka Kingdom": "Reino Saka",
  "Suren Kingdom": "Reino Suren",
  Satavahanihara: "Satavahana",
  "Hindu kingdoms": "Reinos Hindus",
  "Hindu kingdoms and republics": "Reinos e Repúblicas Hindus",
  Magadha: "Magadha",
  "Zhow states": "Estados Zhou",
  "Zhou states": "Estados Zhou",
  Zhoa: "Estados Zhou",
  "Zhangzhung Kingdom": "Reino de Zhangzhung",
  Yuezhi: "Yuezhi",
  Sinic: "Estados Sínicos",
  "Toba Wei": "Dinastia Wei do Norte",
  Ruanruan: "Canato Ruanruan",
  "Tufan Empire": "Império Tibetano",
  Tungus: "Tungues",
  "Western Gokturk Khaganate": "Canato Turco Ocidental (Göktürks)",
  "Oghuz Turks": "Turcos Oguzes",
  Koreans: "Coreanos",
  Tibetans: "Tibetanos",
  "Tibeto-Burmanese": "Tibeto-Birmaneses",

  // Steppe / Central Asian empires
  Mongols: "Mongóis",
  "Mongol Empire": "Império Mongol",
  "Great Khanate": "Grande Canato",
  "Khanate of the Golden Horde": "Canato da Horda Dourada",
  Ilkhanate: "Ilcanato",
  "Chagatai Khanate": "Canato Chagatai",
  "White Horde": "Horda Branca",
  "Kara Khitai Khaganate": "Canato Kara Khitai",
  "Cuman-Kipchak confederation": "Confederação Cumano-Kipchak",
  "Kimek-Kipchak khaganate": "Canato Kimek-Kipchak",
  "Timurid Empire": "Império Timúrida",
  "central Asian khanates": "Canatos da Ásia Central",

  // Islamic world (later)
  "Ottoman Empire": "Império Otomano",
  "Safavid Empire": "Império Safávida",

  // Europe
  "Kalmar Union": "União de Kalmar",
  "Grand Duchy of Moscow": "Grão-Ducado de Moscou",
  "Tsardom of Muscovy": "Czarado da Moscóvia",
  "Russian Empire": "Império Russo",
  Russia: "Rússia",
  USSR: "URSS",
  "United Kingdom of Great Britain and Ireland": "Reino Unido da Grã-Bretanha e Irlanda",
  "United Kingdom": "Reino Unido",
  "Austrian Empire": "Império Austríaco",
  "Austria Hungary": "Áustria-Hungria",
  Denmark: "Dinamarca",
  "Denmark-Norway": "Dinamarca-Noruega",
  France: "França",
  Spain: "Espanha",
  Portugal: "Portugal",
  Sweden: "Suécia",
  Norway: "Noruega",
  Poland: "Polônia",
  Germany: "Alemanha",
  "German Empire": "Império Alemão",

  // The Americas
  "Aztec Empire": "Império Asteca",
  "Inca Empire": "Império Inca",
  "Toltec Empire": "Império Tolteca",
  "Zapotec Empire": "Império Zapoteca",
  Olmec: "Olmecas",
  Teotihuacán: "Teotihuacán",
  Teotihuacàn: "Teotihuacán",
  "Teotihuac�n": "Teotihuacán",
  "Maya city-states": "Cidades-Estado Maias",
  "Maya chiefdoms and states": "Cacicados e Estados Maias",
  "Norte Chico": "Norte Chico",
  "Vice Royalty of Peru": "Vice-Reino do Peru",
  "Vice-Royalty of Peru": "Vice-Reino do Peru",
  "Vice-Royalty of New Spain": "Vice-Reino da Nova Espanha",
  "Vice-Royalty of Brazil": "Vice-Reino do Brasil",
  "Kingdom of Brazil": "Reino do Brasil",
  "Vice-Royalty of New Granada": "Vice-Reino de Nova Granada",
  "Viceroyalty of the Río de la Plata": "Vice-Reino do Rio da Prata",
  "Rupert's Land": "Terra de Rupert",
  Canada: "Canadá",
  "United States": "Estados Unidos",
  "United States of America": "Estados Unidos",
  Mexico: "México",
  Brazil: "Brasil",
  Argentina: "Argentina",

  // Africa
  "Great Zimbabwe": "Grande Zimbábue",
  Zimbabwe: "Zimbábue",
  Songhai: "Império Songhai",
  Zulu: "Zulu",
  Zululand: "Zululândia",
  Sudan: "Sudão",
  "Anglo-Egyption Sudan": "Sudão Anglo-Egípcio",
  Zaire: "Zaire",
  "Zaire (Belgium)": "Zaire (Bélgica)",
  Algeria: "Argélia",
  "Algeria (France)": "Argélia (França)",
  "Belgian Congo": "Congo Belga",
  "French West Africa": "África Ocidental Francesa",
  "French Equatorial Africa": "África Equatorial Francesa",
  "Saudi Arabia": "Arábia Saudita",
  Axum: "Reino de Axum",
  Meroe: "Reino de Meroë",
  Kerma: "Reino de Kerma",
  Berbers: "Berberes",
  Tuaregs: "Tuaregues",

  // Oceania / other modern
  Australia: "Austrália",
  "Western Australia (UK)": "Austrália Ocidental (RU)",
  India: "Índia",
  China: "China",
  Kazakhstan: "Cazaquistão",
  Greenland: "Groenlândia",
  Antarctica: "Antártida",

  // Prehistoric/Bronze Age cultures and peoples
  Saami: "Samis",
  Andronovo: "Cultura Andronovo",
  Afanasevo: "Cultura Afanasevo",
  Thai: "Tais",
  "Oxus": "Civilização do Oxus",
  Beaker: "Cultura Campaniforme",
  "city-states": "Cidades-Estado",
  Ainu: "Ainos",
  Jōmon: "Cultura Jomon",
  Valdivia: "Valdivia",
  Namazga: "Cultura Namazga",
  "minor states": "Estados menores",
  "Yamnaya culture": "Cultura Yamnaya",
  Sintashta: "Cultura Sintashta",
  Únětice: "Cultura Únětice",
  "Dapenkeng culture": "Cultura Dapenkeng",
  "Dakapeng culture": "Cultura Dapenkeng",

// Bulk translation pass over every remaining unique NAME/SUBJECTO value
// across the 34 vendored snapshots (~1500 entries) that were not already
// hand-curated above. Historical states/empires/kingdoms are translated
// properly; ethnonyms and indigenous-group names with no established
// Portuguese form are kept as-is rather than inventing one.
  "Aaniiih": "Aaniiih",
  "Abdelouadides": "Abdelouadides",
  "Abnaki": "Abenaquis",
  "Aboriginal Tasmanians": "Aborígenes tasmanianos",
  "Aboriginal tribes": "Tribos aborígenes",
  "Abyssinia": "Abissínia",
  "Acadian Peninsula (UK)": "Península Acadiana (Reino Unido)",
  "Acaxea": "Acaxea",
  "Accra": "Acra",
  "Aceh": "Aceh",
  "Adal": "Adal",
  "Adena Culture": "Cultura Adena",
  "Afghanistan": "Afeganistão",
  "Africa": "África",
  "Aghlabid Emirate": "Emirado Aglábida",
  "Agwarmin": "Agwarmin",
  "Ahmadnagar": "Ahmadnagar",
  "Ainus": "Ainos",
  "Air": "Air",
  "Akan": "Akan",
  "Alabama": "Alabama",
  "Alans": "Alanos",
  "Alawa": "Alawa",
  "Albania": "Albânia",
  "Algiers": "Argel",
  "Algonquin": "Algonquinos",
  "Almohad Caliphate": "Califado Almóada",
  "Almoravid dynasty": "Dinastia Almorávida",
  "Alwa": "Alwa",
  "Alyawarre": "Alyawarre",
  "Amangu": "Amangu",
  "Amarak": "Amarak",
  "Amazon hunter-gatherers": "Caçadores-coletores da Amazônia",
  "Ambur": "Ambur",
  "American Samoa": "Samoa Americana",
  "Anasazi": "Anasazi",
  "Anatolian tribes": "Tribos anatólias",
  "Andean hunter-gatherers": "Caçadores-coletores andinos",
  "Andean states and chiefdoms": "Estados e cacicados andinos",
  "Andegerebenha": "Andegerebenha",
  "Andorra": "Andorra",
  "Andyamathanha": "Andyamathanha",
  "Angevin Empire": "Império Angevino",
  "Anggamudi": "Anggamudi",
  "Anglo-Saxons": "Anglo-Saxões",
  "Angola": "Angola",
  "Angola (Portugal)": "Angola (Portugal)",
  "Anguilla": "Anguilla",
  "Anguthimri": "Anguthimri",
  "Anhalt": "Anhalt",
  "Anmatyerre": "Anmatyerre",
  "Annam": "Anam",
  "Antakarinja": "Antakarinja",
  "Antigua and Barbuda": "Antígua e Barbuda",
  "Apache": "Apaches",
  "Apalachee": "Apalaches",
  "Arabana": "Arabana",
  "Arabia (Nejd)": "Arábia (Nejd)",
  "Arabian pastoral nomads": "Pastores nômades da Arábia",
  "Arabs": "Árabes",
  "Aragón": "Aragão",
  "Arakan": "Arracão",
  "Arakan (Indian princely state)": "Arracão (estado principesco indiano)",
  "Arapaho": "Arapahos",
  "Arawaks": "Aruaques",
  "Archaic Amerindian hunter-gatherers": "Caçadores-coletores ameríndios arcaicos",
  "Arctic marine mammal hunters": "Caçadores árticos de mamíferos marinhos",
  "Arikara": "Arikara",
  "Armenia": "Armênia",
  "Armorica": "Armórica",
  "Arran": "Arran",
  "Arrernte": "Arrernte",
  "Artsakh": "Artsakh",
  "Asante": "Asante",
  "Assiniboin": "Assiniboin",
  "Asturias": "Astúrias",
  "Atakapa": "Atakapa",
  "Athabascan": "Atabascanos",
  "Athabaskan": "Atabascanos",
  "Ato trading confederacy": "Confederação comercial Ato",
  "Atropatene": "Atropatena",
  "Aures": "Aurés",
  "Australian aboriginal hunter-gatherers": "Caçadores-coletores aborígenes australianos",
  "Austria": "Áustria",
  "Austrian Netherlands": "Países Baixos Austríacos",
  "Austro-Asiatic rice farmers": "Agricultores de arroz austroasiáticos",
  "Austro-Hungarian Empire": "Império Austro-Húngaro",
  "Austroasian rice cultures": "Culturas de arroz austroasiáticas",
  "Austronesians": "Austronésios",
  "Ava": "Ava",
  "Avanti": "Avanti",
  "Avars": "Ávaros",
  "Awabakal": "Awabakal",
  "Awngthim": "Awngthim",
  "Awsa": "Awsa",
  "Aymara kingdoms": "Reinos aimarás",
  "Ayutthaya": "Ayutthaya",
  "Azandes": "Azandes",
  "Azerbaijan": "Azerbaijão",
  "Bactria": "Báctria",
  "Baden": "Baden",
  "Badimaya": "Badimaya",
  "Badtjala": "Badtjala",
  "Bagan": "Bagan",
  "Bagirmi": "Bagirmi",
  "Bahamas": "Bahamas",
  "Bahawalpur": "Bahawalpur",
  "Bahmani Kingdom": "Reino Bahmani",
  "Bakanh": "Bakanh",
  "Balhae": "Balhae",
  "Ballardong": "Ballardong",
  "Baltic Tribes": "Tribos Bálticas",
  "Baltic tribes": "Tribos bálticas",
  "Balts": "Bálticos",
  "Banas": "Banas",
  "Bandjigali": "Bandjigali",
  "Banggarla": "Banggarla",
  "Bangladesh": "Bangladesh",
  "Banjima": "Banjima",
  "Bantou": "Bantos",
  "Bantu": "Bantos",
  "Baraba Baraba": "Baraba Baraba",
  "Baradha": "Baradha",
  "Barbados": "Barbados",
  "Bardi": "Bardi",
  "Barghawata": "Barghawata",
  "Barindji": "Barindji",
  "Barkindji": "Barkindji",
  "Barna": "Barna",
  "Barotse": "Barotse",
  "Barranbinya": "Barranbinya",
  "Barundji": "Barundji",
  "Barunggam": "Barunggam",
  "Basks": "Bascos",
  "Basutoland": "Basutolândia",
  "Batavian Republic": "República Batava",
  "Bavaria": "Baviera",
  "Bayali": "Bayali",
  "Bedouins": "Beduínos",
  "Bega": "Bega",
  "Bejas": "Bejas",
  "Belgium": "Bélgica",
  "Belize": "Belize",
  "Bell-shaped burials culture": "Cultura Campaniforme",
  "Bella": "Bella",
  "Bengal": "Bengala",
  "Benin": "Benim",
  "Beothuk": "Beothuk",
  "Berber Tribes": "Tribos Berberes",
  "Beylik of Aydin": "Beylik de Aydin",
  "Bhutan": "Butão",
  "Bibbulman": "Bibbulman",
  "Bidar": "Bidar",
  "Bidjara": "Bidjara",
  "Bidwell": "Bidwell",
  "Bigambul": "Bigambul",
  "Bijapur": "Bijapur",
  "Bilinara": "Bilinara",
  "Biloxi": "Biloxi",
  "Binbinga": "Binbinga",
  "Bindjali": "Bindjali",
  "Biri": "Biri",
  "Biripi": "Biripi",
  "Birria": "Birria",
  "Blackfoot": "Pés-Negros",
  "Blemmyes": "Blêmios",
  "Blue Horde": "Horda Azul",
  "Boethuk": "Beothuk",
  "Boihaenum": "Boihaenum",
  "Boii": "Boios",
  "Bolivia": "Bolívia",
  "Boonwurrung": "Boonwurrung",
  "Borgu States": "Estados de Borgu",
  "Bornu-Kanem": "Bornu-Kanem",
  "Bosnia": "Bósnia",
  "Bosnia and Herzegovina": "Bósnia e Herzegovina",
  "Bosnia-Herzegovina": "Bósnia-Herzegovina",
  "Bosporan Kingdom": "Reino do Bósforo",
  "Bosporian Kingdom": "Reino do Bósforo",
  "Botswana": "Botsuana",
  "Bremen": "Brema",
  "Britany": "Bretanha",
  "British East Africa": "África Oriental Britânica",
  "British Guiana": "Guiana Britânica",
  "British Protectorate": "Protetorado Britânico",
  "British Somaliland": "Somalilândia Britânica",
  "Broërec": "Broërec",
  "Brunei": "Brunei",
  "Brunswick": "Brunsvique",
  "Brushed Pottery culture": "Cultura da Cerâmica Escovada",
  "Buandig": "Buandig",
  "Budjari": "Budjari",
  "Buganda": "Buganda",
  "Bukurnidja": "Bukurnidja",
  "Bularnu": "Bularnu",
  "Bulgar Khanate": "Canato Búlgaro",
  "Bulgaria": "Bulgária",
  "Bulgars": "Búlgaros",
  "Bundelkhand": "Bundelkhand",
  "Bundjalung": "Bundjalung",
  "Bunyoro": "Bunyoro",
  "Burarra": "Burarra",
  "Burgandy": "Borgonha",
  "Burgunds": "Burgúndios",
  "Burkina Faso": "Burkina Faso",
  "Burma": "Birmânia",
  "Burmese": "Birmaneses",
  "Burmese kingdoms": "Reinos birmaneses",
  "Burundi": "Burundi",
  "Buwayhid Emirates": "Emirados Buídas",
  "Buyid Emirate": "Emirado Buída",
  "Buyiids": "Buídas",
  "Byelarus": "Bielorrússia",
  "Caddo": "Caddo",
  "Cahitas": "Cahitas",
  "Cahulia": "Cahulia",
  "Calabar": "Calabar",
  "Caliphate of Córdoba": "Califado de Córdova",
  "Caloosahatchee culture": "Cultura Caloosahatchee",
  "Caloosahatchee cultureure": "Cultura Caloosahatchee",
  "Calusa": "Calusa",
  "Cambodia": "Camboja",
  "Cameroon": "Camarões",
  "Cantia": "Cantia",
  "Caohuiltecs": "Coauiltecos",
  "Cape Colony": "Colônia do Cabo",
  "Cappadocia": "Capadócia",
  "Caribbean hunter-gatherers": "Caçadores-coletores do Caribe",
  "Carnatic": "Carnática",
  "Carolingian Empire": "Império Carolíngio",
  "Castile": "Castela",
  "Castilla": "Castela",
  "Castille": "Castela",
  "Catacomb culture": "Cultura das Catacumbas",
  "Catawba": "Catawba",
  "Caxcane": "Caxcanes",
  "Cayenne": "Caiena",
  "Cayuse": "Cayuse",
  "Celtiberians": "Celtiberos",
  "Celtic kingdoms": "Reinos celtas",
  "Celts": "Celtas",
  "Central African Republic": "República Centro-Africana",
  "Ceylon": "Ceilão",
  "Ceylon (Dutch)": "Ceilão (Holandês)",
  "Chad": "Chade",
  "Chalukya Empire": "Império Chalukya",
  "Chalukyas": "Chalukyas",
  "Champa City States": "Cidades-Estado de Champa",
  "Chandellas": "Chandelas",
  "Chatot": "Chatot",
  "Chauhans": "Chauhans",
  "Chavin": "Chavín",
  "Chelmia": "Chelmia",
  "Chen-La": "Chenla",
  "Cheras": "Cheras",
  "Cherokee": "Cherokees",
  "Cherookee": "Cherokees",
  "Cheyenne": "Cheyennes",
  "Chicaksaw": "Chickasaws",
  "Chile": "Chile",
  "Chimú Empire": "Império Chimú",
  "Chinchoros": "Chinchorros",
  "Chinchorro culture": "Cultura Chinchorro",
  "Chiricahua": "Chiricahua",
  "Chisos": "Chisos",
  "Choctaw": "Choctaws",
  "Chorrera": "Chorrera",
  "Chtimacha": "Chitimacha",
  "Chuds": "Chudes",
  "Chukchi": "Chukchis",
  "Chumash": "Chumash",
  "Chūzan": "Chuzan",
  "Ciboney": "Ciboney",
  "Circars": "Circars",
  "CochimÃ­": "Cochimí",
  "Cochin": "Cochim",
  "Cochin China": "Cochinchina",
  "Colchis": "Cólquida",
  "Colombia": "Colômbia",
  "Comanche": "Comanches",
  "Comté de Toulouse": "Condado de Toulouse",
  "Congo": "Congo",
  "Congo (France)": "Congo (França)",
  "Conoy": "Conoy",
  "Copena": "Copena",
  "Coqs": "Coqs",
  "Corsica": "Córsega",
  "Costa Rica": "Costa Rica",
  "Costanoan": "Costanoan",
  "Cotonou": "Cotonou",
  "Couture Complex": "Complexo Couture",
  "Cree": "Cree",
  "Crimean Khanate": "Canato da Crimeia",
  "Croatia": "Croácia",
  "Croatian kingdom": "Reino da Croácia",
  "Crow": "Crow",
  "Cuacasian Albania": "Albânia Caucasiana",
  "Cuba": "Cuba",
  "Cuba (Spain)": "Cuba (Espanha)",
  "Cuman Khanates": "Canatos Cumanos",
  "Curonians": "Curônios",
  "Cusabo": "Cusabo",
  "Cushites": "Cuxitas",
  "Cuxhaven": "Cuxhaven",
  "Cyprus": "Chipre",
  "Cyraneica (UK Lybia)": "Cirenaica (Líbia Britânica)",
  "Cyrenaica": "Cirenaica",
  "Czech Republic": "República Tcheca",
  "Czechoslovakia": "Tchecoslováquia",
  "Czechs": "Tchecos",
  "Daces": "Dácios",
  "Dacia": "Dácia",
  "Dadi Dadi": "Dadi Dadi",
  "Dahomey": "Daomé",
  "Dainggatti": "Dainggatti",
  "Danes": "Daneses",
  "Dangbon": "Dangbon",
  "Danggali": "Danggali",
  "Danube Bulgars": "Búlgaros do Danúbio",
  "Dardania": "Dardânia",
  "Darfur": "Darfur",
  "Darkinung": "Darkinung",
  "Darumbal": "Darumbal",
  "Delagoa Bay": "Baía de Delagoa",
  "Delaware": "Delaware",
  "Derbent": "Derbent",
  "Desert hunter-gatherers": "Caçadores-coletores do deserto",
  "Dharawala": "Dharawala",
  "Dharug": "Dharug",
  "Dhirari": "Dhirari",
  "Dieri": "Dieri",
  "Dja Dja Wurrung": "Dja Dja Wurrung",
  "Djabuganjdji": "Djabuganjdji",
  "Djabwurung": "Djabwurung",
  "Djargurdwurung": "Djargurdwurung",
  "Djibouti": "Djibuti",
  "Djirbalngan": "Djirbalngan",
  "Dominica": "Dominica",
  "Dominican Republic": "República Dominicana",
  "Dominion of Newfoundland": "Domínio de Terra Nova",
  "Doolboong/Miriwoong": "Doolboong/Miriwoong",
  "Dorset": "Dorset",
  "Dravidians": "Dravídicos",
  "Duchy of Swabia": "Ducado da Suábia",
  "Dumnonia": "Dumnônia",
  "Dumonii": "Dumnônios",
  "Durdzuks": "Durdzuks",
  "Dutch Brazil": "Brasil Holandês",
  "Dutch East Indies": "Índias Orientais Holandesas",
  "Dutch Formosa": "Formosa Holandesa",
  "Dutch Guiana": "Guiana Holandesa",
  "Dutch Guinea": "Guiné Holandesa",
  "Dutch Republic": "República Holandesa",
  "Dutch settlements": "Colônias Holandesas",
  "Dutchy of Benevento": "Ducado de Benevento",
  "Dvaravati": "Dvaravati",
  "Dyungungoo (Gubbi Gubbi)": "Dyungungoo (Gubbi Gubbi)",
  "East Francia": "Francia Oriental",
  "East Germany": "Alemanha Oriental",
  "East Getaes": "Getas Orientais",
  "East Java": "Java Oriental",
  "East Prussia": "Prússia Oriental",
  "Eastern Masurian culture": "Cultura da Masúria Oriental",
  "Eastern North Amercian hunter-gatherers": "Caçadores-coletores do leste da América do Norte",
  "Ecuador": "Equador",
  "El Paraiso": "El Paraíso",
  "El Salvador": "El Salvador",
  "Emirate of Bin Shal'an": "Emirado de Bin Shal'an",
  "Emirate of Córdoba": "Emirado de Córdova",
  "Emirate of Sicily": "Emirado da Sicília",
  "Emirate of Tiflis": "Emirado de Tíflis",
  "Emirate of the White Sheep Turks": "Emirado dos Turcomanos do Carneiro Branco",
  "Empire of Ghana": "Império de Gana",
  "Empire of Japan": "Império do Japão",
  "Enets": "Enets",
  "England": "Inglaterra",
  "England and Ireland": "Inglaterra e Irlanda",
  "English territory": "Território Inglês",
  "Eora": "Eora",
  "Equatorial Guinea": "Guiné Equatorial",
  "Erie": "Erie",
  "Eritrea": "Eritreia",
  "Eritrea (Italy)": "Eritreia (Itália)",
  "Essequibo": "Essequibo",
  "Essex": "Essex",
  "Estonia": "Estônia",
  "Ethiopia": "Etiópia",
  "Ethiopia (Italy)": "Etiópia (Itália)",
  "Ethiopian HIghland Peoples": "Povos das Terras Altas da Etiópia",
  "Ethiopian highland farmers": "Agricultores das terras altas da Etiópia",
  "Etrurians": "Etruscos",
  "Expansionist Kingdom of Merina": "Reino Expansionista de Merina",
  "Eyaq": "Eyak",
  "Far Eastern SSR": "RSS do Extremo Oriente",
  "Fatimid Caliphate": "Califado Fatímida",
  "Fezzan (Frech Lybia)": "Fezã (Líbia Francesa)",
  "Fiji": "Fiji",
  "Finland": "Finlândia",
  "Finnmark": "Finnmark",
  "Finno-Ugric taiga hunter-gatherers": "Caçadores-coletores finoúgricos da taiga",
  "First Samori Empire": "Primeiro Império de Samori",
  "Fivizzano": "Fivizzano",
  "Flathead": "Flathead",
  "Florence": "Florença",
  "Florida": "Flórida",
  "Fourche Maline Culture": "Cultura Fourche Maline",
  "Fox": "Fox",
  "Franche-Comté": "Franco-Condado",
  "Frankish Kingdom": "Reino Franco",
  "Franks": "Francos",
  "French Cameroons": "Camarões Francês",
  "French Guiana": "Guiana Francesa",
  "French Indo-China": "Indochina Francesa",
  "French Indochina": "Indochina Francesa",
  "French Somaliland": "Somalilândia Francesa",
  "Frisians": "Frísios",
  "Funan": "Funan",
  "Funj": "Funj",
  "Futa Jalon": "Futa Jalon",
  "Futa Toro": "Futa Toro",
  "Gabalbara": "Gabalbara",
  "Gabon": "Gabão",
  "Gadubanud": "Gadubanud",
  "Gagudju": "Gagudju",
  "Gamberre": "Gamberre",
  "Gambia": "Gâmbia",
  "Gambia, The": "Gâmbia",
  "Gananggalinda": "Gananggalinda",
  "Gandhāra": "Gandara",
  "Ganggalida": "Ganggalida",
  "Gangulu": "Gangulu",
  "Garawa": "Garawa",
  "Garingbal": "Garingbal",
  "Gaya": "Gaya",
  "Gayiri": "Gayiri",
  "Geawegal": "Geawegal",
  "Geneva": "Genebra",
  "Genoa": "Gênova",
  "Georgia": "Geórgia",
  "Georgian Kingdom": "Reino da Geórgia",
  "German E. Africa (Tanganyika)": "África Oriental Alemã (Tanganica)",
  "German South-West Africa": "África do Sudoeste Alemã",
  "Germany (France)": "Alemanha (França)",
  "Germany (Soviet)": "Alemanha (Soviética)",
  "Germany (UK)": "Alemanha (Reino Unido)",
  "Germany (USA)": "Alemanha (EUA)",
  "Ghana": "Gana",
  "Gharra": "Gharra",
  "Ghaznavid Emirate": "Emirado Gaznávida",
  "Gilbert and Elice Islands": "Ilhas Gilbert e Ellice",
  "Giraiwurung": "Giraiwurung",
  "Giya": "Giya",
  "Glades Culture": "Cultura Glades",
  "Goa": "Goa",
  "Goghtn": "Goghtn",
  "Gold Coast": "Costa do Ouro",
  "Golden Horde": "Horda Dourada",
  "Golkonda": "Golconda",
  "Goodall Focus": "Foco Goodall",
  "Gooniyandi": "Gooniyandi",
  "Gooty": "Gooty",
  "Goreng": "Goreng",
  "Goryeo": "Goryeo",
  "Goths": "Godos",
  "Granada": "Granada",
  "Great Moravia": "Grande Morávia",
  "Greece": "Grécia",
  "Grenada": "Granada",
  "Griqualand West": "Griqualand Ocidental",
  "Gros Ventre": "Gros Ventre",
  "Guachichiles": "Guachichiles",
  "Guachimis": "Guachimis",
  "Guadeloupe": "Guadalupe",
  "Guam": "Guam",
  "Guamar / Pecchichitane": "Guamar / Pecchichitane",
  "Guanahatabeyes": "Guanahatabeyes",
  "Guanches": "Guanches",
  "Guatemala": "Guatemala",
  "Gugu-Badhun": "Gugu-Badhun",
  "Guinea": "Guiné",
  "Guinea-Bissau": "Guiné-Bissau",
  "Guinea-Bissau (Portugal)": "Guiné-Bissau (Portugal)",
  "Gulidjan": "Gulidjan",
  "Gumbainggir": "Gumbainggir",
  "Gunbalang": "Gunbalang",
  "Gunditjmara": "Gunditjmara",
  "Gundungurra": "Gundungurra",
  "Gungabula": "Gungabula",
  "Gunggari": "Gunggari",
  "Gungurugoni": "Gungurugoni",
  "Gunibidji": "Gunibidji",
  "Gunindiri": "Gunindiri",
  "Gunu": "Gunu",
  "Gunwinggu": "Gunwinggu",
  "Gureng Gureng": "Gureng Gureng",
  "Gurindji": "Gurindji",
  "Guringai": "Guringai",
  "Gurjara Pratihara": "Gurjara-Pratihara",
  "Guta": "Guta",
  "Guugu-Yimidhirr": "Guugu-Yimidhirr",
  "Guwa": "Guwa",
  "Guwinmal": "Guwinmal",
  "Guyana": "Guiana",
  "Habsburg Netherlands": "Países Baixos Habsburgos",
  "Hadramaut": "Hadramaute",
  "Hafsid Caliphate": "Califado Hafsida",
  "Hail": "Hail",
  "Hainan": "Hainan",
  "Haiti": "Haiti",
  "Hamburg": "Hamburgo",
  "Han Zhao": "Han Zhao",
  "Hanover": "Hanôver",
  "Harapunchai": "Haripunjaya",
  "Harer (Egypt)": "Harar (Egito)",
  "Haripunjaya": "Haripunjaya",
  "Hausa States": "Estados Haúçás",
  "Havasupai": "Havasupai",
  "Hejaz": "Hejaz",
  "Helvetic Republic": "República Helvética",
  "Heruli": "Hérulos",
  "Himyarite Kingdom": "Reino Himiarita",
  "Hindu Kingdoms": "Reinos Hindus",
  "Hindu Shahis": "Hindu Shahis",
  "Hindu states": "Estados hindus",
  "Hispaniola (Spain)": "Hispaniola (Espanha)",
  "Hitchiti": "Hitchiti",
  "Hohenzollern": "Hohenzollern",
  "Hokuzan": "Hokuzan",
  "Holstein": "Holsácia",
  "Honduras": "Honduras",
  "Hong Kong": "Hong Kong",
  "Hopewell Culture": "Cultura Hopewell",
  "Hopi": "Hopi",
  "Hopie": "Hopi",
  "Houma": "Houma",
  "Huari Empire": "Império Huari",
  "Hungary": "Hungria",
  "Huns": "Hunos",
  "Hunters-gatherers": "Caçadores-coletores",
  "Huron": "Huron",
  "Hövsgöl Nuur": "Hövsgöl Nuur",
  "Ibadan": "Ibadan",
  "Ibadites": "Ibaditas",
  "Iceland": "Islândia",
  "Icelandic Commonwealth": "Comunidade Islandesa",
  "Idrisid Caliphate": "Califado Idrisida",
  "Ifat": "Ifat",
  "Illinnois": "Illinois",
  "Imerina": "Imerina",
  "Imperial Hungary": "Hungria Imperial",
  "Imperial Japan": "Japão Imperial",
  "Imperial Japan (Fujiwara)": "Japão Imperial (Fujiwara)",
  "Indonesia": "Indonésia",
  "Iningai": "Iningai",
  "Innu": "Innu",
  "Inupiaq": "Inupiaq",
  "Iowa": "Iowa",
  "Iran": "Irã",
  "Iraq": "Iraque",
  "Ireland": "Irlanda",
  "Irlanda": "Irlanda",
  "Iron Age chieftainships": "Cacicados da Idade do Ferro",
  "Iron Age megalith cultures": "Culturas megalíticas da Idade do Ferro",
  "Iroquois": "Iroqueses",
  "Irritilas": "Irritilas",
  "Islamic and Hindu states": "Estados islâmicos e hindus",
  "Islamic city-states": "Cidades-estado islâmicas",
  "Islamic states": "Estados islâmicos",
  "Israel": "Israel",
  "Italian Somaliland": "Somalilândia Italiana",
  "Italy": "Itália",
  "Itelmen": "Itelmen",
  "Ivory Coast": "Costa do Marfim",
  "Iwaidja": "Iwaidja",
  "Jabirrjabirr": "Jabirrjabirr",
  "Jaburrara": "Jaburrara",
  "Jaitmatang": "Jaitmatang",
  "Jamaica": "Jamaica",
  "Jamaica (UK)": "Jamaica (Reino Unido)",
  "Jaminjung": "Jaminjung",
  "Janabres": "Janabres",
  "Japan": "Japão",
  "Japan (USA)": "Japão (EUA)",
  "Japan (Warring States)": "Japão (Período Sengoku)",
  "Jardwadjali": "Jardwadjali",
  "Jaru": "Jaru",
  "Jawoyn": "Jawoyn",
  "Jicarilla": "Jicarilla",
  "Jingili": "Jingili",
  "Jiwarli": "Jiwarli",
  "Jordan": "Jordânia",
  "Judea": "Judeia",
  "Jukun": "Jukun",
  "Jurruru": "Jurruru",
  "Kaantju": "Kaantju",
  "Kaarta": "Kaarta",
  "Kadambas": "Kadambas",
  "Kadjerong": "Kadjerong",
  "Kakheti-Hereti": "Kakheti-Hereti",
  "Kalaako/Malpa": "Kalaako/Malpa",
  "Kalaamaya": "Kalaamaya",
  "Kalapuya": "Kalapuya",
  "Kalinago": "Kalinago",
  "Kalinga": "Kalinga",
  "Kalispel": "Kalispel",
  "Kalkadoon": "Kalkadoon",
  "Kamarupa": "Kamarupa",
  "Kamerun": "Camarões",
  "Kamia": "Kamia",
  "Kamilaroi": "Kamilaroi",
  "Kanara": "Canará",
  "Kanauj": "Kanauj",
  "Kandy": "Kandy",
  "Kanem": "Kanem",
  "Kanem-Bornu": "Kanem-Bornu",
  "Kaniyang": "Kaniyang",
  "Kansa": "Kansa",
  "Karajarri": "Karajarri",
  "Karakalpaks": "Caracalpaques",
  "Karangpurru": "Karangpurru",
  "Karangura": "Karangura",
  "Karankawa": "Karankawa",
  "Karasuk culture": "Cultura Karasuk",
  "Karelians": "Carélios",
  "Karenggapa": "Karenggapa",
  "Kariyarra": "Kariyarra",
  "Karkhanids": "Caracânidas",
  "Karluks": "Karluks",
  "Karuwali": "Karuwali",
  "Kashmir and Ladakh": "Caxemira e Ladaque",
  "Kasi": "Kasi",
  "Kaurna Pangkarra": "Kaurna Pangkarra",
  "Kawahsu": "Kawahsu",
  "Kaytej": "Kaytej",
  "Kediri": "Kediri",
  "Kent": "Kent",
  "Kenya": "Quênia",
  "Khanate of Sibir": "Canato da Sibéria",
  "Khazars": "Cazares",
  "Khitans": "Khitans",
  "Khiva Khanate": "Canato de Khiva",
  "Khoiasan": "Khoisan",
  "Khoisan": "Khoisan",
  "Khundzi": "Khundzi",
  "Kievan Rus": "Rússia de Kiev",
  "Kija": "Kija",
  "Kijkitat": "Kijkitat",
  "Kingdom of France": "Reino da França",
  "Kingdom of Gala": "Reino de Gala",
  "Kingdom of Georgia": "Reino da Geórgia",
  "Kingdom of Hawaii": "Reino do Havaí",
  "Kingdom of Hungary": "Reino da Hungria",
  "Kingdom of Ireland": "Reino da Irlanda",
  "Kingdom of Kapisa": "Reino de Kapisa",
  "Kingdom of Kashmir": "Reino da Caxemira",
  "Kingdom of Norway": "Reino da Noruega",
  "Kingdom of Pagan": "Reino de Pagan",
  "Kingdom of Sardinia": "Reino da Sardenha",
  "Kingdom of Sind": "Reino de Sinde",
  "Kingdom of Sukhotai": "Reino de Sukhothai",
  "Kingdom of Syphax": "Reino de Sífax",
  "Kingdom of Zunbil": "Reino de Zunbil",
  "Kingdom of the Two Sicilies": "Reino das Duas Sicílias",
  "Kingfom of Italy": "Reino da Itália",
  "Kiowa": "Kiowa",
  "Klachuris": "Kalachuris",
  "Knucati": "Knucati",
  "Koguryo": "Goguryeo",
  "Kokatha": "Kokatha",
  "Koknar": "Koknar",
  "Koko-bera": "Koko-bera",
  "Kokomini": "Kokomini",
  "Kokowarra": "Kokowarra",
  "Konbudj": "Konbudj",
  "Kong": "Kong",
  "Kong Empire": "Império de Kong",
  "Kooma": "Kooma",
  "Korea": "Coreia",
  "Korea (USA)": "Coreia (EUA)",
  "Korea (USSR)": "Coreia (URSS)",
  "Korea, Democratic People's Republic of": "Coreia, República Popular Democrática da",
  "Korea, Republic of": "Coreia, República da",
  "Koryaks": "Coriaques",
  "Kosala": "Kosala",
  "Kryvichs": "Kryvichs",
  "Kuba": "Kuba",
  "Kukatj": "Kukatj",
  "Kukatja": "Kukatja",
  "Kuku-yalanji": "Kuku-yalanji",
  "Kullilla": "Kullilla",
  "Kundjey’mi": "Kundjey'mi",
  "Kungarakany": "Kungarakany",
  "Kunja": "Kunja",
  "Kunjen": "Kunjen",
  "Kureinji": "Kureinji",
  "Kuril Islands": "Ilhas Curilas",
  "Kurnai": "Kurnai",
  "Kurrama": "Kurrama",
  "Kurs": "Curônios",
  "Kurtjar": "Kurtjar",
  "Kuru": "Kuru",
  "Kurykans": "Kurykans",
  "Kuthant": "Kuthant",
  "Kuuku-yani": "Kuuku-yani",
  "Kuuku-ya’u": "Kuuku-ya'u",
  "Kuungkari": "Kuungkari",
  "Kuwait": "Kuwait",
  "Kuwarra": "Kuwarra",
  "Kuwema": "Kuwema",
  "Kuyani": "Kuyani",
  "Kwakwaka'wakw": "Kwakwaka'wakw",
  "Kwarezm": "Corásmia",
  "Kwarizm-Shah": "Xás de Corásmia",
  "Kwini": "Kwini",
  "Kyivan Rus": "Rússia de Kiev",
  "Kyrgyzstan": "Quirguistão",
  "Lagos": "Lagos",
  "Lagunero": "Lagunero",
  "Lake Segozerskoye": "Lago Segozero",
  "Lake Vygozero": "Lago Vygozero",
  "Lamalama": "Lamalama",
  "Lambakannas": "Lambakannas",
  "Lan Na": "Lan Na",
  "Laos": "Laos",
  "Laotian states": "Estados laosianos",
  "Larrakia": "Larrakia",
  "Late Jomon culture": "Cultura Jomon Tardia",
  "Latje Latje": "Latje Latje",
  "Latvia": "Letônia",
  "Laurel complex": "Complexo Laurel",
  "Lavo": "Lavo",
  "Lebanon": "Líbano",
  "Leks": "Leks",
  "Lesotho": "Lesoto",
  "León": "Leão",
  "Liao": "Liao",
  "Liberia": "Libéria",
  "Libya": "Líbia",
  "Libya (IT)": "Líbia (IT)",
  "Liechtenstein": "Liechtenstein",
  "Limilngan": "Limilngan",
  "Lipan": "Lipan",
  "Lippe-Detmold": "Lippe-Detmold",
  "Lithuania": "Lituânia",
  "Lombard duchies": "Ducados lombardos",
  "Lombard principalities": "Principados lombardos",
  "Lombardy": "Lombardia",
  "Lopburi Kingdom": "Reino de Lopburi",
  "Lozi": "Lozi",
  "Luba": "Luba",
  "Lucca": "Lucca",
  "Luiseno": "Luiseno",
  "Luisiana": "Luisiana",
  "Lunda": "Lunda",
  "Luritja": "Luritja",
  "Luthigh": "Luthigh",
  "Luva": "Luva",
  "Luxembourg": "Luxemburgo",
  "Lübeck": "Lübeck",
  "M?ori": "Maori",
  "Maan": "Maan",
  "Madagascar": "Madagáscar",
  "Madagascar (France)": "Madagáscar (França)",
  "Madi Madi": "Madi Madi",
  "Madras": "Madras",
  "Magyars": "Magiares",
  "Mahicacn": "Mahicacn",
  "Mahra": "Mahra",
  "Maiawali": "Maiawali",
  "Maiou": "Maiou",
  "Maitraka Kingdom": "Reino Maitraka",
  "Maize farmers": "Agricultores de milho",
  "Makkura": "Makkura",
  "Malabar": "Malabar",
  "Malacca": "Malaca",
  "Malagasy": "Malgaxe",
  "Malak malak": "Malak Malak",
  "Malawi": "Malawi",
  "Malay": "Malaio",
  "Malaya": "Malaia",
  "Malays": "Malaios",
  "Malaysia": "Malásia",
  "Malaysian Islamic states": "Estados Islâmicos Malaios",
  "Mali": "Mali",
  "Malkana": "Malkana",
  "Malla": "Malla",
  "Malta": "Malta",
  "Malyangaba": "Malyangaba",
  "Mamluke Sultanate": "Sultanato Mameluco",
  "Manchuria": "Manchúria",
  "Mandan": "Mandan",
  "Mandandanji": "Mandandanji",
  "Mandatory Palestine (GB)": "Palestina Mandatária (GB)",
  "Mandes": "Mandé",
  "Mandjindja": "Mandjindja",
  "Mangala": "Mangala",
  "Mangarayi": "Mangarayi",
  "Manioc farmers": "Agricultores de mandioca",
  "Maori": "Maori",
  "Maoris": "Maoris",
  "Mara": "Mara",
  "Maranunggu": "Maranunggu",
  "Maratines": "Maratines",
  "Mardu": "Mardu",
  "Margany": "Margany",
  "Marksville Culture": "Cultura Marksville",
  "Marramaninjsji": "Marramaninjsji",
  "Marringarr": "Marringarr",
  "Marrithiyel": "Marrithiyel",
  "Martinique": "Martinica",
  "Martinique (France)": "Martinica (França)",
  "Martuthunira": "Martuthunira",
  "Masachuset": "Masachuset",
  "Mascat": "Mascate",
  "Maskat": "Mascate",
  "Massa": "Massa",
  "Massachusetts Bay": "Baía de Massachusetts",
  "Mataram": "Mataram",
  "Maung": "Maung",
  "Mauretania": "Mauritânia",
  "Mauri": "Mauros",
  "Mauritania": "Mauritânia",
  "Maya": "Maia",
  "Maya states": "Estados Maias",
  "Mayas": "Maias",
  "Mayi-Kulan": "Mayi-Kulan",
  "Mayi-Kutuna": "Mayi-Kutuna",
  "Mayi-Thakurti": "Mayi-Thakurti",
  "Mayi-Yapi": "Mayi-Yapi",
  "Mazun": "Mazun",
  "Mbabaram": "Mbabaram",
  "Mbailundu": "Bailundo",
  "Mbara": "Mbara",
  "Mbeiwum": "Mbeiwum",
  "Mbukarla": "Mbukarla",
  "Mecklenburg-Schwerin": "Mecklemburgo-Schwerin",
  "Mecklenburg-Strelitz": "Mecklemburgo-Strelitz",
  "Menomini": "Menomini",
  "Mercia": "Mércia",
  "Merinides": "Merínidas",
  "Meru": "Meru",
  "Mescalero": "Mescalero",
  "Mesoamerican city-states and chiefdoms": "Cidades-estado e cacicados mesoamericanos",
  "Mesoamerican hunter-gatherers and maïze farmers": "Caçadores-coletores e agricultores de milho da Mesoamérica",
  "Mesopotamia (GB)": "Mesopotâmia (GB)",
  "Mi'kma'ki": "Mi'kma'ki",
  "Miami": "Miami",
  "Middag Kingdom": "Reino de Middag",
  "Milan": "Milão",
  "Mill Creek Culture": "Cultura Mill Creek",
  "Miller": "Miller",
  "Milograd culture": "Cultura de Milograd",
  "Min-Yue": "Minyue",
  "Minang": "Minang",
  "Mingin": "Mingin",
  "Mirambo Unyanyembe Ukimbu": "Mirambo Unyanyembe Ukimbu",
  "Mirning": "Mirning",
  "Missouri": "Missouri",
  "Mithaka": "Mithaka",
  "Miwa": "Miwa",
  "Miwok": "Miwok",
  "Mixtec Empire": "Império Mixteco",
  "Mixtecs": "Mixtecas",
  "Miyan": "Miyan",
  "Moche": "Moche",
  "Modena": "Módena",
  "Modoc": "Modoc",
  "Mogollon": "Mogollon",
  "Moldova": "Moldávia",
  "Mon States": "Estados Mon",
  "Mon state": "Estado Mon",
  "Mon-Khmer": "Mon-Khmer",
  "Mongolia": "Mongólia",
  "Montagnais Innu": "Montagnais Innu",
  "Montana": "Montana",
  "Monte Alb?n": "Monte Albán",
  "Monte Albàn": "Monte Albán",
  "Monte Albán": "Monte Albán",
  "Monte Alb�n": "Monte Albán",
  "Montenegro": "Montenegro",
  "Montserrat": "Monserrate",
  "Moravians": "Morávios",
  "Morocco": "Marrocos",
  "Morocco (France)": "Marrocos (França)",
  "Mossi States": "Estados Mossi",
  "Mozambique": "Moçambique",
  "Mozambique (Portugal)": "Moçambique (Portugal)",
  "Mpalitjanh": "Mpalitjanh",
  "Mudburra": "Mudburra",
  "Multan": "Multan",
  "Murrinh-patha": "Murrinh-patha",
  "Muruwari": "Muruwari",
  "Muscat": "Mascate",
  "Muscat and Oman": "Mascate e Omã",
  "Muskogee": "Muskogee",
  "Mutumui": "Mutumui",
  "Mwenemutapa": "Monomotapa",
  "Mysore": "Mysore",
  "N. European Bronze Age cultures": "Culturas da Idade do Bronze do Norte da Europa",
  "Nabatean Kingdom": "Reino Nabateu",
  "Nakako": "Nakako",
  "Nakara": "Nakara",
  "Namibia": "Namíbia",
  "Nan Chao": "Nanzhao",
  "Nan-Yue": "Nanyue",
  "Nan-Zhao": "Nanzhao",
  "Nana": "Nana",
  "Naniaho": "Naniaho",
  "Nanzan": "Nanzan",
  "Naples": "Nápoles",
  "Narangga": "Narangga",
  "Nari Nari": "Nari Nari",
  "Naskapi Innu": "Naskapi Innu",
  "Natal": "Natal",
  "Natchez": "Natchez",
  "Navaho": "Navajo",
  "Navajo": "Navajo",
  "Navarre": "Navarra",
  "Nawu": "Nawu",
  "Nayarit": "Nayarit",
  "Nazca": "Nazca",
  "Ndebele": "Ndebele",
  "Ndongo": "Ndongo",
  "Nejd": "Nejd",
  "Nepal": "Nepal",
  "Netherlands": "Países Baixos",
  "Netherlands Antilles": "Antilhas Neerlandesas",
  "Netherlands Indies": "Índias Neerlandesas",
  "Neustria": "Nêustria",
  "New Amsterdam": "Nova Amsterdã",
  "New Caledonia": "Nova Caledônia",
  "New France": "Nova França",
  "New Hebrides": "Novas Hébridas",
  "New South Wales (UK)": "Nova Gales do Sul (Reino Unido)",
  "New Zealand": "Nova Zelândia",
  "Nez Perce": "Nez Percé",
  "Ngaanyatjarra": "Ngaanyatjarra",
  "Ngadjuri": "Ngadjuri",
  "Ngalakan": "Ngalakan",
  "Ngalawangka": "Ngalawangka",
  "Ngalea": "Ngalea",
  "Ngaliwuru": "Ngaliwuru",
  "Ngalkbun": "Ngalkbun",
  "Ngambri": "Ngambri",
  "Ngamini": "Ngamini",
  "Nganasan": "Nganasan",
  "Ngandi": "Ngandi",
  "Ngandji": "Ngandji",
  "Nganyaywana": "Nganyaywana",
  "Ngan’gikurunggurr": "Ngan'gikurunggurr",
  "Ngan’giwumirri": "Ngan'giwumirri",
  "Ngarabal": "Ngarabal",
  "Ngargad": "Ngargad",
  "Ngarigo": "Ngarigo",
  "Ngarinman": "Ngarinman",
  "Ngarinyin": "Ngarinyin",
  "Ngarla": "Ngarla",
  "Ngarluma": "Ngarluma",
  "Ngarrindjeri": "Ngarrindjeri",
  "Ngarti": "Ngarti",
  "Ngatatjara": "Ngatatjara",
  "Ngatjumay": "Ngatjumay",
  "Ngawun": "Ngawun",
  "Ngombur": "Ngombur",
  "Nguburinji": "Nguburinji",
  "Ngumbarl": "Ngumbarl",
  "Ngunawal": "Ngunawal",
  "Nguni": "Nguni",
  "Nguri": "Nguri",
  "Ngurraiillam": "Ngurraiillam",
  "Ngwato": "Ngwato",
  "Nhanta": "Nhanta",
  "Nhuwala": "Nhuwala",
  "Nicaragua": "Nicarágua",
  "Niger": "Níger",
  "Nigeria": "Nigéria",
  "Nimanburu": "Nimanburu",
  "Ninticoy": "Ninticoy",
  "Niue": "Niue",
  "Nizam's Dominions": "Domínios do Nizam",
  "Nobatia": "Nobácia",
  "Nogai Horde": "Horda Nogai",
  "Norsemen": "Nórdicos",
  "North American Pacifi foraging, hunting and fishing peoples": "Povos coletores, caçadores e pescadores do Pacífico norte-americano",
  "Northern Paiute": "Paiute do Norte",
  "Northern Rhodesia": "Rodésia do Norte",
  "Northern Territory (UK)": "Território do Norte (Reino Unido)",
  "Nothumbria": "Nortúmbria",
  "Novgorod": "Novgorod",
  "Novgorod-Seversky": "Novgorod-Seversky",
  "Nukunu": "Nukunu",
  "Numidia": "Numídia",
  "Nungali": "Nungali",
  "Nunggubuyu": "Nunggubuyu",
  "Nyaki-nyaki": "Nyaki-nyaki",
  "Nyamal": "Nyamal",
  "Nyanganyatjara": "Nyanganyatjara",
  "Nyangumarda": "Nyangumarda",
  "Nyasaland": "Niassalândia",
  "Nyawaygi": "Nyawaygi",
  "Nyikina": "Nyikina",
  "Nyul Nyul": "Nyul Nyul",
  "Obiwa": "Obiwa",
  "Odrysian Kingdom": "Reino Odrísio",
  "Oghuz": "Oguzes",
  "Oirat Confederation": "Confederação Oirata",
  "Oldenburg": "Oldemburgo",
  "Omaha": "Omaha",
  "Oman": "Omã",
  "Oman (British Raj)": "Omã (Raj Britânico)",
  "Opobo": "Opobo",
  "Orange Free State": "Estado Livre de Orange",
  "Orissa": "Orissa",
  "Oromo": "Oromo",
  "Osage": "Osage",
  "Ostrogoths": "Ostrogodos",
  "Other Rus Principalities": "Outros Principados da Rus",
  "Oto": "Oto",
  "Otomies": "Otomis",
  "Ottoman Sultanate": "Sultanato Otomano",
  "Oudh": "Oudh",
  "Ouighurs": "Uigures",
  "Ovimbundu": "Ovimbundu",
  "Oyo": "Oyo",
  "Paekche": "Baekje",
  "Pagan": "Pagan",
  "Pakistan": "Paquistão",
  "Palas": "Palas",
  "Paleo-Inuit": "Paleo-Inuítes",
  "Paleo-Koreans": "Paleo-Coreanos",
  "Paleo-Siberian hunter-gatherers": "Caçadores-coletores paleossiberianos",
  "Pallava": "Pallava",
  "Pallavas": "Pallavas",
  "Palyku": "Palyku",
  "Pampas cultures": "Culturas pampeanas",
  "Panama": "Panamá",
  "Pancala": "Panchala",
  "Pandya state": "Estado Pandya",
  "Pandyas": "Pandyas",
  "Papago": "Papago",
  "Papou": "Papua",
  "Papous": "Papuas",
  "Papua New Guinea": "Papua-Nova Guiné",
  "Papuan": "Papua",
  "Papuan neolithic farmers": "Agricultores neolíticos papuas",
  "Papuans": "Papuas",
  "Paracas": "Paracas",
  "Paraguay": "Paraguai",
  "Paramas": "Paramas",
  "Parma": "Parma",
  "Parthia": "Pártia",
  "Patagonian shellfish and marine mammal hunters": "Caçadores de marisco e mamíferos marinhos da Patagônia",
  "Patwin": "Patwin",
  "Pawnee": "Pawnee",
  "Payungu": "Payungu",
  "Pechenegs": "Pechenegues",
  "Pegu": "Pegu",
  "Pennacook": "Pennacook",
  "Peramangk": "Peramangk",
  "Pergamon": "Pérgamo",
  "Peru": "Peru",
  "Peshemegs": "Peshemegs",
  "Pewa": "Pewa",
  "Philippines": "Filipinas",
  "Picts": "Pictos",
  "Pima": "Pima",
  "Pinikura": "Pinikura",
  "Pinjarup": "Pinjarup",
  "Pintupi": "Pintupi",
  "Pirlatapa": "Pirlatapa",
  "Pisones": "Pisones",
  "Pitjantjatjara": "Pitjantjatjara",
  "Pitta-Pitta": "Pitta-Pitta",
  "Plain bison hunters": "Caçadores de bisões das planícies",
  "Plain-Pottery culture": "Cultura Plain-Pottery",
  "Plateau fichers and hunter gatherers": "Pescadores e caçadores-coletores do planalto",
  "Pocumtuk": "Pocumtuk",
  "Point Peninsula": "Point Peninsula",
  "Poland-Lithuania": "Polônia-Lituânia",
  "Poland-Llituania": "Polônia-Lituânia",
  "Polanes": "Polanos",
  "Polish–Lithuanian Commonwealth": "Comunidade Polaco-Lituana",
  "Polyanians": "Polianos",
  "Polynesians": "Polinésios",
  "Pomerania": "Pomerânia",
  "Pomeranian culture ": "Cultura Pomerana",
  "Pomo": "Pomo",
  "Ponca": "Ponca",
  "Pontremoli": "Pontremoli",
  "Porter": "Porter",
  "Portuguese Brazil": "Brasil Português",
  "Portuguese East Africa": "África Oriental Portuguesa",
  "Portuguese Guinea": "Guiné Portuguesa",
  "Post-Ming Warlords": "Senhores da Guerra Pós-Ming",
  "Potawatomi": "Potawatomi",
  "Poverty point culture": "Cultura Poverty Point",
  "Pratiharas": "Pratiharas",
  "Principality of Galicia-Volhynia": "Principado de Galícia-Volínia",
  "Principality of Kyiv": "Principado de Kiev",
  "Principality of Novgorod": "Principado de Novgorod",
  "Principality of Polotsk": "Principado de Polotsk",
  "Principality of Vladimir-Suzdal": "Principado de Vladimir-Suzdal",
  "Principality of Wallachia": "Principado da Valáquia",
  "Prot-Altaic pastoralists": "Pastores Proto-Altaicos",
  "Proto-Altaic pastoralists": "Pastores Proto-Altaicos",
  "Proto-Slavs": "Proto-eslavos",
  "Prussia": "Prússia",
  "Prussians": "Prússios",
  "Pskov": "Pskov",
  "Puerto Rico": "Porto Rico",
  "Punuba": "Punuba",
  "Purduna": "Purduna",
  "Pyu state": "Estado Pyu",
  "Qataban": "Qataban",
  "Qatar": "Catar",
  "Qin": "Qin",
  "Quapaw": "Quapaw",
  "Quazaq Khanate": "Canato Cazaque",
  "Quebec": "Quebec",
  "Queensland (UK)": "Queensland (Reino Unido)",
  "Rajastan": "Rajastão",
  "Rajput Kingdoms": "Reinos Rajput",
  "Rajput kingdoms": "Reinos rajput",
  "Rajputana": "Rajputana",
  "Rajputs": "Rajputes",
  "Rapa Nui": "Rapa Nui",
  "Rashtrakuta": "Rashtrakuta",
  "Rattanakosin Kingdom": "Reino de Rattanakosin",
  "Raška": "Rascia",
  "Rembarnga": "Rembarnga",
  "Republic of the Seven Zenden": "República dos Sete Zenden",
  "Rhodesia": "Rodésia",
  "Rift Valley States": "Estados do Vale do Rift",
  "Rio De Oro": "Rio de Ouro",
  "Riro": "Riro",
  "Romania": "Romênia",
  "Rome (Galerius)": "Roma (Galério)",
  "Rozwi": "Rozwi",
  "Rwanda": "Ruanda",
  "Rwanda (Belgium)": "Ruanda (Bélgica)",
  "Ryazan": "Ryazan",
  "Saar Protectorate": "Protetorado do Sarre",
  "Saba": "Sabá",
  "Sabines": "Sabinos",
  "Sabini": "Sabinos",
  "Sabirs": "Sabires",
  "Saces": "Sacas",
  "Saffarids": "Safáridas",
  "Saharan Nomadic Tribes": "Tribos Nômades do Saara",
  "Saharan Pastoral Nomads": "Nômades Pastores do Saara",
  "Saharan pastoral nomads": "nômades pastores do Saara",
  "Sahtu": "Sahtu",
  "Saint Barthelemy": "São Bartolomeu",
  "Saint Kitts and Nevis": "São Cristóvão e Neves",
  "Saint Lucia": "Santa Lúcia",
  "Saint Martin": "São Martinho",
  "Saint Vincent and the Grenadines": "São Vicente e Granadinas",
  "Saipan": "Saipan",
  "Sakhalin (RU)": "Sacalina (Rússia)",
  "Samanid Empire": "Império Samânida",
  "Sambian-Nothangian culture": "Cultura Sambian-Nothangian",
  "Sami": "Sami",
  "Samis": "Samis",
  "Samnites": "Samnitas",
  "Samoa": "Samoa",
  "Samoyèdes": "Samoiedos",
  "Santee": "Santee",
  "Sardinia": "Sardenha",
  "Sardinia-Piedmont": "Sardenha-Piemonte",
  "Sasanian dependencies": "Dependências Sassânidas",
  "Saugeen Complex": "Complexo Saugeen",
  "Saunan": "Saunan",
  "Savanna hunter-gatherers": "Caçadores-coletores da savana",
  "Savoy": "Saboia",
  "Saxons": "Saxões",
  "Saxony": "Saxônia",
  "Saylan": "Ceilão",
  "Schaumburg-Lippe": "Schaumburg-Lippe",
  "Scotland": "Escócia",
  "Scots": "Escoceses",
  "Scottalnd": "Escócia",
  "Scottland": "Escócia",
  "Second Samori Empire": "Segundo Império de Samori",
  "Segu": "Segu",
  "Seljuk Caliphate": "Califado Seljúcida",
  "Seljuk Empire": "Império Seljúcida",
  "Semites": "Semitas",
  "Senas": "Senas",
  "Senegal": "Senegal",
  "Serano": "Serrano",
  "Serbia": "Sérvia",
  "Severians": "Severianos",
  "Shan states": "Estados Shan",
  "Shawnee": "Shawnee",
  "Shellfish gatherers": "Coletores de mariscos",
  "Shirvan": "Xirvã",
  "Shoa": "Xoa",
  "Shogun Japan (Kamakura)": "Japão Xogunato (Kamakura)",
  "Shona": "Shona",
  "Shoshoni": "Shoshones",
  "Shuar": "Shuar",
  "Siam": "Sião",
  "Siberians": "Siberianos",
  "Sicily": "Sicília",
  "Sierra Leone": "Serra Leoa",
  "Sikhs": "Sikhs",
  "Silla": "Silla",
  "Simhala": "Simhala",
  "Sindh": "Sindh",
  "Sinhalese kingdom": "Reino Cingalês",
  "Sinhalese kingdoms": "Reinos Cingaleses",
  "Slavic tribes": "Tribos Eslavas",
  "Slavs": "Eslavos",
  "Slovakia": "Eslováquia",
  "Slovenia": "Eslovênia",
  "Sokoto Caliphate": "Califado de Socoto",
  "Solankis": "Solankis",
  "Somalia": "Somália",
  "Somvamsis": "Somvamsis",
  "Soomra Emirate": "Emirado Soomra",
  "Sotho": "Sotho",
  "South Africa": "África do Sul",
  "South Australia (UK)": "Austrália do Sul (Reino Unido)",
  "South Carolina": "Carolina do Sul",
  "South Russia": "Rússia do Sul",
  "Southern Cameroon": "Camarões do Sul",
  "Southern Paiute": "Paiute do Sul",
  "Southern Rhodesia": "Rodésia do Sul",
  "Southern Xiongnu": "Xiongnu do Sul",
  "Spanish Guinea": "Guiné Espanhola",
  "Spanish Morocco": "Marrocos Espanhol",
  "Spanish Sahara": "Saara Espanhol",
  "Spokane": "Spokane",
  "Sri Lanka": "Sri Lanka",
  "Subarctic forest hunter-gatherers": "Caçadores-coletores da floresta subártica",
  "Sukhothai": "Sukhothai",
  "Sultanate of Utetera": "Sultanato de Utetera",
  "Sultinate of Zanzibar": "Sultanato de Zanzibar",
  "Suomi": "Suomi",
  "Surasena": "Surasena",
  "Surinam": "Suriname",
  "Suriname": "Suriname",
  "Suspiaq": "Suspiaq",
  "Susquehanna": "Susquehanna",
  "Sveves": "Suevos",
  "Swabia": "Suábia",
  "Swaziland": "Suazilândia",
  "Sweden–Norway": "Suécia-Noruega",
  "Swedes": "Suecos",
  "Swedes and Goths": "Suecos e Godos",
  "Swift Creek Culture": "Cultura Swift Creek",
  "Swiss Confederation": "Confederação Suíça",
  "Switzerland": "Suíça",
  "Syria": "Síria",
  "Syria (France)": "Síria (França)",
  "Syunik": "Syunik",
  "Sámi": "Sámi",
  "T'atsaot'ine": "T'atsaot'ine",
  "Taino": "Taínos",
  "Taiwan": "Taiwan",
  "Taiwanese Tribes": "Tribos Taiwanesas",
  "Tajikistan": "Tajiquistão",
  "Takalak": "Takalak",
  "Takrur": "Takrur",
  "Tamalipueca": "Tamalipueca",
  "Tancalba": "Tancalba",
  "Tano": "Tano",
  "Tanzania, United Republic of": "Tanzânia, República Unida da",
  "Tashir": "Tashir",
  "Tasmanian hunter-gatherers": "Caçadores-coletores da Tasmânia",
  "Taungurung": "Taungurung",
  "Tecuexe": "Tecuexe",
  "Teke": "Teke",
  "Tenimo": "Tenimo",
  "Tepehuane": "Tepehuane",
  "Teppathiggi": "Teppathiggi",
  "Teton": "Teton",
  "Teutonic Knights": "Ordem Teutônica",
  "Thaayorre": "Thaayorre",
  "Thai Kingdoms": "Reinos Tailandeses",
  "Thailand": "Tailândia",
  "Thalanyji": "Thalanyji",
  "Tharawal": "Tharawal",
  "Tharrgari": "Tharrgari",
  "Thiin": "Thiin",
  "Thompson": "Thompson",
  "Thul Garrie Waja (Bindal)": "Thul Garrie Waja (Bindal)",
  "Thule": "Thule",
  "Thuringia": "Turíngia",
  "Tiahuanaco Empire": "Império de Tiahuanaco",
  "Tibet": "Tibete",
  "Timucua": "Timucua",
  "Timurid Emirates": "Emirados Timúridas",
  "Tjalkanti": "Tjalkanti",
  "Tjerratj": "Tjerratj",
  "Tjungundji": "Tjungundji",
  "Tjupany": "Tjupany",
  "Tlinoit": "Tlinoit",
  "Toboso": "Toboso",
  "Togo": "Togo",
  "Togoland": "Togolândia",
  "Tokugawa Shogunate": "Xogunato Tokugawa",
  "Tonga": "Tonga",
  "Tonkawa": "Tonkawa",
  "Tonkin": "Tonquim",
  "Touareg": "Tuaregues",
  "Transvaal": "Transvaal",
  "Travancore": "Travancore",
  "Trebizond": "Trebizonda",
  "Trinidad": "Trindade",
  "Tripolitana (UK Lybia)": "Tripolitânia (Líbia sob o Reino Unido)",
  "Tripolitania": "Tripolitânia",
  "Trucial Oman": "Omã Trucial",
  "Tuareg Nomadic Tribes": "Tribos Nômades Tuaregues",
  "Tukular Caliphate": "Califado Tukular",
  "Tungusic Tribes": "Tribos Tungúsicas",
  "Tunica": "Tunica",
  "Tunis": "Tunes",
  "Tunisia": "Tunísia",
  "Tupis": "Tupis",
  "Turcik tribes": "Tribos Túrquicas",
  "Turingians": "Turíngios",
  "Turkey": "Turquia",
  "Turkish Cypriot-administered area": "Área administrada pelos cipriotas turcos",
  "Turkmenistan": "Turcomenistão",
  "Turks and Caicos Islands": "Ilhas Turcas e Caicos",
  "Turrbal": "Turrbal",
  "Tuscany": "Toscana",
  "Tutelo": "Tutelo",
  "Tuʻi Tonga Empire": "Império Tuʻi Tonga",
  "Uganda": "Uganda",
  "Ukraine": "Ucrânia",
  "Umatilla": "Umatilla",
  "Umbindhamu": "Umbindhamu",
  "Umida": "Umida",
  "Umpila": "Umpila",
  "Unggarangi": "Unggarangi",
  "Unggumi": "Unggumi",
  "Union of South Africa": "União Sul-Africana",
  "United Arab Emirates": "Emirados Árabes Unidos",
  "United States Virgin Islands": "Ilhas Virgens Americanas",
  "Urnfield cultures": "Culturas dos Campos de Urnas",
  "Uruguay": "Uruguai",
  "Ute": "Ute",
  "Uutaalnganu": "Uutaalnganu",
  "Uyghurs": "Uigures",
  "Uzbekistan": "Uzbequistão",
  "Vakataka": "Vakataka",
  "Vallabhi": "Vallabhi",
  "Vandals": "Vândalos",
  "Vasconia": "Vasconia",
  "Vatsa": "Vatsa",
  "Vazimba": "Vazimba",
  "Vedic Aryans": "Arianos Védicos",
  "Venetia": "Venécia",
  "Venezuela": "Venezuela",
  "Vengi": "Vengi",
  "Venice": "Veneza",
  "Veracruz civilization": "Civilização de Veracruz",
  "Vice Royalty of New Spain": "Vice-Reino da Nova Espanha",
  "Victoria (UK)": "Vitória (Reino Unido)",
  "Virginia": "Virgínia",
  "Vishnu-Kundins": "Vishnu-Kundins",
  "Visigothic Kingdom": "Reino Visigodo",
  "Visigoths": "Visigodos",
  "Volga Bulgars": "Búlgaros do Volga",
  "Waanyi": "Waanyi",
  "Wadai": "Wadai",
  "Wadi Wadi": "Wadi Wadi",
  "Wadigali": "Wadigali",
  "Wadjigu": "Wadjigu",
  "Wagiman": "Wagiman",
  "Wailwan": "Wailwan",
  "Wajuk": "Wajuk",
  "Waka Waka": "Waka Waka",
  "Wakabunga": "Wakabunga",
  "Wakaya": "Wakaya",
  "Walangama": "Walangama",
  "Walapai": "Walapai",
  "Walbis Bay": "Walbis Bay",
  "Waldeck": "Waldeck",
  "Wallis and Futuna Islands": "Ilhas Wallis e Futuna",
  "Walmatjarri": "Walmatjarri",
  "Wambaya": "Wambaya",
  "Wandjiwalgu": "Wandjiwalgu",
  "Wangan": "Wangan",
  "Wangkamana": "Wangkamana",
  "Wangkangurru": "Wangkangurru",
  "Wangkathaa": "Wangkathaa",
  "Wangkumara": "Wangkumara",
  "Wankarani": "Wankarani",
  "Wappynger": "Wappynger",
  "Wardaman": "Wardaman",
  "Wardandi": "Wardandi",
  "Wargamaygan": "Wargamaygan",
  "Warlmanpa": "Warlmanpa",
  "Warlpiri": "Warlpiri",
  "Warluwarra": "Warluwarra",
  "Warray": "Warray",
  "Warriyangga": "Warriyangga",
  "Warsenis": "Warsenis",
  "Warumungu": "Warumungu",
  "Warwa": "Warwa",
  "Watassid Morocco": "Marrocos Uatácida",
  "Wathaurong": "Wathaurong",
  "Watjarri": "Watjarri",
  "Wattasid Caliphate": "Califado Uatácida",
  "Waveroo": "Waveroo",
  "Wawula": "Wawula",
  "Welsh": "Galeses",
  "Wemba Wemba": "Wemba Wemba",
  "Wergaia": "Wergaia",
  "Wessex": "Wessex",
  "West African cereal farmers": "Agricultores de cereais da África Ocidental",
  "West Francia": "Francia Ocidental",
  "West Germany": "Alemanha Ocidental",
  "West Getaes": "Getas Ocidentais",
  "Western Chalukyas": "Chalukyas Ocidentais",
  "Western Gangas": "Gangas Ocidentais",
  "Western Masurian culture": "Cultura da Masúria Ocidental",
  "Western Roman Empire": "Império Romano do Ocidente",
  "Western Sahara": "Saara Ocidental",
  "White Russia": "Rússia Branca",
  "Wichita": "Wichita",
  "Wiilman": "Wiilman",
  "Wik": "Wik",
  "Wiljali": "Wiljali",
  "Winda Winda": "Winda Winda",
  "Winebago": "Winebago",
  "Wiradjuri": "Wiradjuri",
  "Wirangu": "Wirangu",
  "Wongaibon": "Wongaibon",
  "Wonnarua": "Wonnarua",
  "Woolna": "Woolna",
  "Worimi": "Worimi",
  "Worla": "Worla",
  "Worora": "Worora",
  "Wu": "Wu",
  "Wudjari": "Wudjari",
  "Wulgurukaba": "Wulgurukaba",
  "Wuli-wuli": "Wuli-wuli",
  "Wunambul": "Wunambul",
  "Wuningangk": "Wuningangk",
  "Wunumara": "Wunumara",
  "Wurundjeri": "Wurundjeri",
  "Wuthathi": "Wuthathi",
  "Württemberg": "Vurtemberga",
  "Xecora": "Xecora",
  "Xhosa": "Xhosa",
  "Xinjiang": "Xinjiang",
  "Xixia": "Xia Ocidental",
  "Yadhaigana": "Yadhaigana",
  "Yagalingu": "Yagalingu",
  "Yaka": "Yaka",
  "Yakima": "Yakima",
  "Yalarrnga": "Yalarrnga",
  "Yamato": "Yamato",
  "Yambina": "Yambina",
  "Yanda": "Yanda",
  "Yandruwandha": "Yandruwandha",
  "Yanga": "Yanga",
  "Yangga": "Yangga",
  "Yangman": "Yangman",
  "Yankontai": "Yankontai",
  "Yankton": "Yankton",
  "Yankuntjatjara": "Yankuntjatjara",
  "Yanyuwa": "Yanyuwa",
  "Yarluyandi": "Yarluyandi",
  "Yavapai": "Yavapai",
  "Yawarawarka": "Yawarawarka",
  "Yawuru": "Yawuru",
  "Yayoi": "Yayoi",
  "Yeke": "Yeke",
  "Yemen": "Iêmen",
  "Yemen (UK)": "Iêmen (Reino Unido)",
  "Yidinjdji": "Yidinjdji",
  "Yiiji": "Yiiji",
  "Yilba": "Yilba",
  "Yiman": "Yiman",
  "Yindjibarndi": "Yindjibarndi",
  "Yinggarda": "Yinggarda",
  "Yinhawangka": "Yinhawangka",
  "Yinwum": "Yinwum",
  "Yir Yoront": "Yir Yoront",
  "Yirandali": "Yirandali",
  "Yitha Yitha": "Yitha Yitha",
  "Yokuts": "Yokuts",
  "Yolngu": "Yolngu",
  "Yorta Yorta": "Yorta Yorta",
  "Yuat": "Yuat",
  "Yuchi": "Yuchi",
  "Yue": "Yue",
  "Yueban": "Yueban",
  "Yugambeh": "Yugambeh",
  "Yuggera": "Yuggera",
  "Yugoslavia": "Iugoslávia",
  "Yuin": "Yuin",
  "Yukagir": "Iucaguires",
  "Yulparitja": "Yulparitja",
  "Yuma": "Yuma",
  "Yup'ik & Cup'ik": "Yup'ik & Cup'ik",
  "Yupangathi": "Yupangathi",
  "Yuru": "Yuru",
  "Yuwi": "Yuwi",
  "Zacatecs": "Zacatecs",
  "Zambia": "Zâmbia",
  "Zanzibar": "Zanzibar",
  "Zayyanid Caliphate": "Califado Zayânida",
  "Zuni": "Zuni",
  "minor Hindu & Buddhist states": "pequenos estados hindus e budistas",
  "minor Hindu and Buddhist kingdoms": "pequenos reinos hindus e budistas",
  "minor Hindu and Buddhist states": "pequenos estados hindus e budistas",
  "minor Hindu kingdoms": "pequenos reinos hindus",
  "minor states under Indian influence": "pequenos estados sob influência indiana",
  "Akatziri": "Acátziros",
  "Alamans": "Alamanos",
  "Algeria (FR)": "Argélia (FR)",
  "Amuq D": "Amuq D",
  "Astrakhan Khanate": "Canato de Astracã",
  "Bithynia": "Bitínia",
  "Brandenburg": "Brandemburgo",
  "Caucasian Alans": "Alanos do Cáucaso",
  "Celltic Hallsatt culture": "Cultura Celta de Hallstatt",
  "Chernoles culture": "Cultura Chernoles",
  "Coastal and Woodland Mesolithic Hunter-Foragers": "Caçadores-coletores mesolíticos do litoral e das florestas",
  "Crete": "Creta",
  "Danzig": "Danzig",
  "Dimini": "Cultura Dimini",
  "Early combware": "Cerâmica de Pente Antiga",
  "Electoral Hesse": "Hesse Eleitoral",
  "Ests": "Estônios",
  "Finns": "Finlandeses",
  "Funnel-Beaker": "Cultura dos Vasos de Funil",
  "Geats": "Gautas",
  "Gepids": "Gépidas",
  "Germanic tribes": "Tribos Germânicas",
  "Grand Duchy of Hesse": "Grão-Ducado de Hesse",
  "Greek colonies": "Colônias Gregas",
  "Highland Mesolithic Hunter-Foragers": "Caçadores-coletores mesolíticos das terras altas",
  "Hunnic Empire": "Império Huno",
  "Kelteminar culture": "Cultura de Kelteminar",
  "Kingdom of Antigonus": "Reino de Antígono",
  "Kingdom of Kassander": "Reino de Cassandro",
  "Kingdom of Lysimachus": "Reino de Lisímaco",
  "La Almagra culture": "Cultura de La Almagra",
  "La Tène culture": "Cultura de La Tène",
  "Lusatian culture": "Cultura Lusaciana",
  "Mari": "Marís",
  "Milano (Austria)": "Milão (Áustria)",
  "Mordvinians": "Mordvinos",
  "Narva": "Cultura de Narva",
  "Nassau": "Nassau",
  "Neanderthal": "Neandertais",
  "Nemay": "Cultura de Nemay",
  "Neolithic Farmers": "Agricultores neolíticos",
  "Northmen": "Nórdicos",
  "Palatinate": "Palatinado",
  "Permians": "Permianos",
  "Proto-Scythian culture": "Cultura Proto-Cita",
  "Republic of Kraków": "República de Cracóvia",
  "Rus' Khaganate": "Canato da Rus",
  "San Marino": "San Marino",
  "Schleswig": "Schleswig",
  "Skirii": "Esciros",
  "Slavonic tribes": "Tribos eslavas",
  "Stentinello culture": "Cultura de Stentinello",
  "Steppe Mesolithic Hunter-Foragers": "Caçadores-coletores mesolíticos da estepe",
  "Veps": "Vepsianos",
  "Volga-Kamm": "Cultura Volga-Kama",
  "Wetzlar": "Wetzlar",
};

export function translateTerritoryName(name: string): string {
  return CURATED_TERRITORIES[name] ?? name;
}
