// Curated point markers for well-documented historical peoples/states
// that our main dataset (historical-basemaps) leaves as blank "sem
// dados" land for a given snapshot year. Originally we wanted to pull
// these live from Wikidata's SPARQL endpoint, but that host is blocked
// by this environment's network policy -- so, like curatedTerritories.ts
// and colonialClaims.ts, this is manually researched and curated by us.
//
// Deliberately just POINTS, not polygons: we don't have (and don't want
// to fabricate) precise borders for these -- the goal is only to signal
// "historians know someone specific lived here", not to claim exact
// territory shapes. Keyed by the snapshot year they apply to, same
// pattern as COLONIAL_CLAIMS.
export type KnownGapMarker = {
  name: string;
  lng: number;
  lat: number;
  note: string;
};

export const KNOWN_GAP_MARKERS: Record<number, KnownGapMarker[]> = {
  [-2000]: [
    { name: "Cultura Únětice", lng: 15.5, lat: 50.3, note: "A cultura de Únětice floresceu na Boêmia, na Silésia e no centro da Alemanha durante o início da Idade do Bronze, entre cerca de 2300 e 1600 a.C. Seus artesãos produziam objetos sofisticados de bronze e ouro, como o famoso Disco Celeste de Nebra, e mantinham redes de comércio que ligavam o Báltico ao Mediterrâneo. Sucedeu localmente as tradições da cerâmica cordada (Corded Ware)." },
    { name: "Cultura de Fatyanovo-Balanovo", lng: 40, lat: 56.5, note: "A cultura de Fatyanovo-Balanovo foi o ramo florestal oriental do horizonte da cerâmica cordada, ocupando as bacias dos rios Volga e Oka, no centro da Rússia europeia, entre aproximadamente 2900 e 1900 a.C. Seus portadores eram agricultores e pastores que enterravam os mortos com machados de pedra polida e cerâmica cordada característica. Muitos pesquisadores associam essas populações à difusão inicial de línguas indo-europeias na zona florestal russa." },
    { name: "Cultura de Abashevo", lng: 50, lat: 54, note: "A cultura de Abashevo ocupou a região entre o Volga médio e os Urais meridionais durante a Idade do Bronze, por volta de 2200 a 1900 a.C. Seus povos eram metalúrgicos hábeis que exploravam depósitos de cobre locais, contribuindo para o surgimento das culturas de Sintashta e Srubnaya que se seguiram na mesma região." },
    { name: "Cultura de Sintashta", lng: 60.75, lat: 52.65, note: "A cultura de Sintashta desenvolveu-se nos Urais meridionais entre cerca de 2100 e 1800 a.C., conhecida por assentamentos fortificados de planta circular, como Arkaim, e pelas evidências arqueológicas mais antigas de carros de guerra com rodas raiadas. É amplamente associada às origens dos povos de língua indo-iraniana que mais tarde migrariam para a Ásia Central e o subcontinente indiano." },
    { name: "Cultura do Sino Campaniforme (Bell Beaker)", lng: -1.83, lat: 51.18, note: "A cultura do Sino Campaniforme espalhou-se pelas Ilhas Britânicas e por boa parte da Europa atlântica entre cerca de 2500 e 1800 a.C., reconhecida por seus característicos vasos cerâmicos em forma de sino. Na Grã-Bretanha, seus portadores construíram as fases finais de Stonehenge e protagonizaram uma substituição demográfica significativa, hoje atestada por estudos de DNA antigo." },
  ],
  [-323]: [
    { name: "Reino de Lihyan (Dedã)", lng: 37.91, lat: 26.63, note: "Reino centrado no oásis de Dedã (atual Al-Ula), no noroeste da Arábia, que floresceu entre os séculos V e II a.C. controlando trechos da rota das especiarias e do incenso. Deixou numerosas inscrições em escrita lihyanita e tumbas monumentais escavadas na rocha. Foi posteriormente absorvido pelo reino nabateu." },
  ],
  [-200]: [
    { name: "Eduos (Aedui)", lng: 4, lat: 46.9, note: "Os eduos eram um dos povos gauleses mais poderosos do centro da Gália, na região da atual Borgonha, com capital em Bibracte. Já no século II a.C. mantinham relações privilegiadas com Roma, sendo depois reconhecidos oficialmente como aliados especiais do povo romano. Fontes antigas, como os relatos de César, descrevem-nos como rivais tradicionais dos arvernos pela hegemonia sobre a Gália." },
    { name: "Arvernos (Arverni)", lng: 3.1, lat: 45.6, note: "Os arvernos dominavam a região da atual Auvergne, no centro da Gália, e por volta de 200 a.C. já eram um dos povos celtas mais influentes da região. No século seguinte chegariam a liderar uma ampla confederação de tribos gaulesas sob o rei Bituito, antes de serem derrotados por Roma. Sua capital, Gergóvia, tornou-se célebre mais tarde na resistência à conquista de Júlio César." },
    { name: "Helvécios (Helvetii)", lng: 7.4, lat: 47, note: "Os helvécios eram um povo celta estabelecido no planalto suíço desde pelo menos o século III a.C., entre o Jura e os Alpes. Ocupavam posição estratégica nas rotas que ligavam a Gália ao norte da Itália. Décadas mais tarde, sua tentativa de migração em massa para o oeste seria barrada por Júlio César, episódio com que se abrem os seus Comentários sobre a Guerra da Gália." },
    { name: "Lusitanos", lng: -7.9, lat: 39.6, note: "Os lusitanos habitavam a região que corresponde ao centro de Portugal e à Estremadura espanhola, entre os rios Douro e Tejo. Por volta de 200 a.C. já formavam um povo bem estabelecido, ainda fora do alcance direto de Roma. Décadas depois, sob a liderança de Viriato, ofereceriam a mais longa e eficaz resistência armada à conquista romana da península Ibérica." },
    { name: "Celtiberos", lng: -2.5, lat: 41.8, note: "Os celtiberos formavam um conjunto de povos de cultura mista celta e ibérica que ocupava o planalto central da Hispânia, organizados em tribos como arévacos, belos e títios, em torno de cidades como Numância. Por volta de 200 a.C. seu território já estava bem definido, pouco antes de se tornar alvo direto da expansão romana na península. Ficariam conhecidos pela fereza da resistência às campanhas de Roma nos séculos II e I a.C." },
    { name: "Vascões (Vascones)", lng: -1.6, lat: 42.8, note: "Os vascões ocupavam a região dos atuais Navarra e País Basco, no norte da península Ibérica, sendo um dos poucos povos pré-romanos da região de origem não indo-europeia, ancestrais dos bascos atuais. Autores antigos como Estrabão e Plínio, o Velho, registraram seu território e costumes. Mantiveram sua língua e identidade mesmo após séculos de presença romana, um caso raro de continuidade cultural na Europa ocidental." },
    { name: "Boios (Boii)", lng: 14.5, lat: 50, note: "Os boios eram uma tribo celta que se estabeleceu na Boêmia, região que herda seu nome até hoje, tornando-se um dos principais centros de poder celta na Europa central por volta do século III a.C. Também presentes na Gália Cisalpina e na Panônia, os boios da Boêmia só foram derrotados pelos marcomanos germânicos no final do século I a.C." },
    { name: "Escórdiscos (Scordisci)", lng: 20.46, lat: 44.8, note: "Os escórdiscos formaram uma confederação tribal de origem celta e ilíria na confluência dos rios Sava e Danúbio, próximo à atual Belgrado, após a invasão celta dos Bálcãs em 279 a.C. Por volta de 200 a.C. eram uma das potências militares mais temidas da região, realizando incursões contra a Macedônia e a Grécia antes de serem finalmente subjugados por Roma no século I a.C." },
    { name: "Reino Ilírio dos Ardieus", lng: 19.5, lat: 42.1, note: "O reino ilírio dos ardieus, com capital em Escódera (atual Shkodër), dominava a costa oriental do Adriático desde o final do século III a.C. Ficou famoso pelo reinado da rainha Teuta, que provocou as Guerras Ilíricas contra Roma, e manteve-se como potência regional até sua derrota final sob o rei Gêncio, em 168 a.C." },
    { name: "Getas (Getae)", lng: 25.5, lat: 44.5, note: "Os getas eram um povo trácio que habitava a planície da Valáquia, ao sul dos Cárpatos, conhecido desde os relatos de Heródoto. Por volta de 200 a.C. estavam organizados em reinos tribais, como o do rei Zalmodegicos, atestado por uma inscrição grega da cidade de Histria, antecedendo a unificação dácia sob Burebista no século seguinte." },
    { name: "Bastarnas (Bastarnae)", lng: 27.5, lat: 47.5, note: "Os bastarnas eram um povo de provável origem germânica, com forte influência celta, que se estabeleceu entre os Cárpatos e o rio Dniester a partir do final do século III a.C. Atuaram como mercenários e aliados de reinos helenísticos, como a Macedônia, sendo um dos primeiros povos de possível origem germânica documentados tão a sudeste na Europa." },
    { name: "Cultura de Jastorf", lng: 10, lat: 53.5, note: "A cultura de Jastorf floresceu no norte da Alemanha e na península da Jutlândia durante a Idade do Ferro pré-romana, entre cerca de 600 a.C. e o início da era comum. É amplamente considerada pelos arqueólogos o berço material dos povos germânicos históricos, antecedendo migrações posteriores como as dos cimbros e teutões." },
    { name: "Cultura de Przeworsk", lng: 19, lat: 51.5, note: "A cultura de Przeworsk surgiu por volta de 200 a.C. no território da atual Polônia, associada por muitos pesquisadores aos vândalos, aos lúgios e a outros povos germânicos orientais. Caracteriza-se por cemitérios de cremação com rico ajuar de armas e influências da cultura de La Tène, mantendo-se em uso até o século IV ou V d.C." },
  ],
  [-100]: [
    { name: "Cultura Huasteca", lng: -98.85, lat: 22, note: "Povo mesoamericano da planície costeira do Golfo do México, na região historicamente chamada Huasteca (atuais Tamaulipas, San Luis Potosí e norte de Veracruz). Falantes de uma língua aparentada ao maia, mas geograficamente isolados dos demais povos maias, desenvolveram centros como Tamtoc. A região seria posteriormente incorporada, em parte, ao Império Asteca no século XV." },
    { name: "Tradição de Teuchitlán", lng: -103.85, lat: 20.75, note: "Complexo cultural do oeste do México, centrado na região do vulcão de Tequila, em Jalisco, conhecido por suas características tumbas de tiro e por arquitetura circular única na Mesoamérica, como os montículos de Guachimontones. Floresceu aproximadamente entre 300 a.C. e 900 d.C., mantendo redes de trocas com outras regiões mesoamericanas. Distingue-se claramente das tradições arquitetônicas do centro do México, como Teotihuacan." },
  ],
  [-1]: [
    { name: "Cultura de San Agustín", lng: -76.26, lat: 1.88, note: "A cultura de San Agustín floresceu nas nascentes do rio Madalena, no sul dos Andes colombianos, entre aproximadamente o século I e o século IX d.C. É famosa por centenas de estátuas monolíticas antropomorfas e zoomorfas, esculpidas em pedra vulcânica e associadas a complexos funerários e cerimoniais. Constitui um dos conjuntos escultóricos pré-colombianos mais impressionantes da América do Sul." },
    { name: "Cultura Zenú (Sinú)", lng: -75.75, lat: 8.75, note: "O povo zenu ocupou as várzeas dos rios Sinú, San Jorge e Cauca, no norte da atual Colômbia, entre cerca de 200 a.C. e a chegada dos espanhóis. Desenvolveu um extenso sistema de canais e camalhões de terra para controlar as cheias sazonais e cultivar em terras alagadiças, além de produzir refinada ourivesaria. Formava cacicados organizados regionalmente, sem constituir um estado centralizado único." },
    { name: "Geoglifos do Acre", lng: -67.8, lat: -9.9, note: "No sudoeste da Amazônia, no atual estado brasileiro do Acre, populações indígenas escavaram, a partir de cerca de mil anos antes de Cristo, centenas de grandes estruturas geométricas de terra — valas, taludes e recintos circulares ou quadrangulares — hoje visíveis sobretudo após desmatamento e por sensoriamento remoto. A função exata dos geoglifos ainda é debatida entre uso cerimonial, habitacional e de gestão da paisagem florestal. Revelam ocupação humana antiga e organizada na floresta muito antes da chegada europeia." },
    { name: "Tamudeus", lng: 37.95, lat: 26.79, note: "Povo árabe antigo do noroeste e centro-norte da Arábia, mencionado desde o século VIII a.C. em anais assírios e depois em fontes romanas e na tradição corânica (povo de Salih). Sem um reino centralizado, forneceram inclusive tropas auxiliares ao Império Romano, registradas como 'Equites Saraceni Thamudeni'. Desapareceram das fontes históricas por volta do século V d.C." },
    { name: "Sushen (Yilou)", lng: 134, lat: 47.8, note: "Povo tungúsico documentado em fontes chinesas da dinastia Han, habitando a bacia dos rios Amur e Ussuri, na região onde hoje ficam o Extremo Oriente russo e o nordeste da China. Eram caçadores-coletores conhecidos por suas flechas de ponta de pedra, oferecidas como tributo às cortes chinesas desde períodos ainda mais antigos. São considerados ancestrais diretos dos mohe, dos jurchens e, por fim, dos manchus, que séculos depois fundariam a dinastia Qing." },
  ],
  [100]: [
    { name: "Cultura de San Agustín", lng: -76.26, lat: 1.88, note: "A cultura de San Agustín floresceu nas nascentes do rio Madalena, no sul dos Andes colombianos, entre aproximadamente o século I e o século IX d.C. É famosa por centenas de estátuas monolíticas antropomorfas e zoomorfas, esculpidas em pedra vulcânica e associadas a complexos funerários e cerimoniais. Constitui um dos conjuntos escultóricos pré-colombianos mais impressionantes da América do Sul." },
    { name: "Cultura Zenú (Sinú)", lng: -75.75, lat: 8.75, note: "O povo zenu ocupou as várzeas dos rios Sinú, San Jorge e Cauca, no norte da atual Colômbia, entre cerca de 200 a.C. e a chegada dos espanhóis. Desenvolveu um extenso sistema de canais e camalhões de terra para controlar as cheias sazonais e cultivar em terras alagadiças, além de produzir refinada ourivesaria. Formava cacicados organizados regionalmente, sem constituir um estado centralizado único." },
    { name: "Geoglifos do Acre", lng: -67.8, lat: -9.9, note: "No sudoeste da Amazônia, no atual estado brasileiro do Acre, populações indígenas escavaram, a partir de cerca de mil anos antes de Cristo, centenas de grandes estruturas geométricas de terra — valas, taludes e recintos circulares ou quadrangulares — hoje visíveis sobretudo após desmatamento e por sensoriamento remoto. A função exata dos geoglifos ainda é debatida entre uso cerimonial, habitacional e de gestão da paisagem florestal. Revelam ocupação humana antiga e organizada na floresta muito antes da chegada europeia." },
    { name: "Cultura Huasteca", lng: -98.85, lat: 22, note: "Povo mesoamericano da planície costeira do Golfo do México, na região historicamente chamada Huasteca (atuais Tamaulipas, San Luis Potosí e norte de Veracruz). Falantes de uma língua aparentada ao maia, mas geograficamente isolados dos demais povos maias, desenvolveram centros como Tamtoc. A região seria posteriormente incorporada, em parte, ao Império Asteca no século XV." },
    { name: "Tradição de Teuchitlán", lng: -103.85, lat: 20.75, note: "Complexo cultural do oeste do México, centrado na região do vulcão de Tequila, em Jalisco, conhecido por suas características tumbas de tiro e por arquitetura circular única na Mesoamérica, como os montículos de Guachimontones. Floresceu aproximadamente entre 300 a.C. e 900 d.C., mantendo redes de trocas com outras regiões mesoamericanas. Distingue-se claramente das tradições arquitetônicas do centro do México, como Teotihuacan." },
    { name: "Tamudeus", lng: 37.95, lat: 26.79, note: "Povo árabe antigo do noroeste e centro-norte da Arábia, mencionado desde o século VIII a.C. em anais assírios e depois em fontes romanas e na tradição corânica (povo de Salih). Sem um reino centralizado, forneceram inclusive tropas auxiliares ao Império Romano, registradas como 'Equites Saraceni Thamudeni'. Desapareceram das fontes históricas por volta do século V d.C." },
    { name: "Langkasuka", lng: 101.3, lat: 6.8, note: "Langkasuka foi um dos mais antigos reinos malaios, situado no norte da península Malaia, na região que hoje corresponde a Kedah e Pattani. Registros chineses da dinastia Liang afirmam que o reino já existia havia cerca de 400 anos quando enviou sua primeira embaixada à China em 515 d.C., o que situa sua fundação por volta do século I ou II. Prosperou como entreposto comercial hindu-budista até entrar na órbita de influência de Srivijaya por volta do século VII." },
  ],
  [300]: [
    { name: "Cultura de San Agustín", lng: -76.26, lat: 1.88, note: "A cultura de San Agustín floresceu nas nascentes do rio Madalena, no sul dos Andes colombianos, entre aproximadamente o século I e o século IX d.C. É famosa por centenas de estátuas monolíticas antropomorfas e zoomorfas, esculpidas em pedra vulcânica e associadas a complexos funerários e cerimoniais. Constitui um dos conjuntos escultóricos pré-colombianos mais impressionantes da América do Sul." },
    { name: "Cultura Zenú (Sinú)", lng: -75.75, lat: 8.75, note: "O povo zenu ocupou as várzeas dos rios Sinú, San Jorge e Cauca, no norte da atual Colômbia, entre cerca de 200 a.C. e a chegada dos espanhóis. Desenvolveu um extenso sistema de canais e camalhões de terra para controlar as cheias sazonais e cultivar em terras alagadiças, além de produzir refinada ourivesaria. Formava cacicados organizados regionalmente, sem constituir um estado centralizado único." },
    { name: "Cultura Tairona", lng: -73.9, lat: 11.2, note: "Instalada nas encostas e no litoral da Serra Nevada de Santa Marta, no norte da Colômbia, a cultura tairona desenvolveu-se a partir de cerca do ano 200 d.C., construindo aldeias em terraços de pedra ligadas por escadarias, como a posteriormente chamada 'Cidade Perdida'. Destacou-se pela metalurgia do ouro e por uma intensa rede de trocas entre as terras altas e a costa caribenha. Resistiu à conquista espanhola até o final do século XVI." },
    { name: "Geoglifos do Acre", lng: -67.8, lat: -9.9, note: "No sudoeste da Amazônia, no atual estado brasileiro do Acre, populações indígenas escavaram, a partir de cerca de mil anos antes de Cristo, centenas de grandes estruturas geométricas de terra — valas, taludes e recintos circulares ou quadrangulares — hoje visíveis sobretudo após desmatamento e por sensoriamento remoto. A função exata dos geoglifos ainda é debatida entre uso cerimonial, habitacional e de gestão da paisagem florestal. Revelam ocupação humana antiga e organizada na floresta muito antes da chegada europeia." },
    { name: "Cultura Huasteca", lng: -98.85, lat: 22, note: "Povo mesoamericano da planície costeira do Golfo do México, na região historicamente chamada Huasteca (atuais Tamaulipas, San Luis Potosí e norte de Veracruz). Falantes de uma língua aparentada ao maia, mas geograficamente isolados dos demais povos maias, desenvolveram centros como Tamtoc. A região seria posteriormente incorporada, em parte, ao Império Asteca no século XV." },
    { name: "Tradição de Teuchitlán", lng: -103.85, lat: 20.75, note: "Complexo cultural do oeste do México, centrado na região do vulcão de Tequila, em Jalisco, conhecido por suas características tumbas de tiro e por arquitetura circular única na Mesoamérica, como os montículos de Guachimontones. Floresceu aproximadamente entre 300 a.C. e 900 d.C., mantendo redes de trocas com outras regiões mesoamericanas. Distingue-se claramente das tradições arquitetônicas do centro do México, como Teotihuacan." },
    { name: "Tamudeus", lng: 37.95, lat: 26.79, note: "Povo árabe antigo do noroeste e centro-norte da Arábia, mencionado desde o século VIII a.C. em anais assírios e depois em fontes romanas e na tradição corânica (povo de Salih). Sem um reino centralizado, forneceram inclusive tropas auxiliares ao Império Romano, registradas como 'Equites Saraceni Thamudeni'. Desapareceram das fontes históricas por volta do século V d.C." },
    { name: "Langkasuka", lng: 101.3, lat: 6.8, note: "Langkasuka foi um dos mais antigos reinos malaios, situado no norte da península Malaia, na região que hoje corresponde a Kedah e Pattani. Registros chineses da dinastia Liang afirmam que o reino já existia havia cerca de 400 anos quando enviou sua primeira embaixada à China em 515 d.C., o que situa sua fundação por volta do século I ou II. Prosperou como entreposto comercial hindu-budista até entrar na órbita de influência de Srivijaya por volta do século VII." },
  ],
  [500]: [
    { name: "Cultura de San Agustín", lng: -76.26, lat: 1.88, note: "A cultura de San Agustín floresceu nas nascentes do rio Madalena, no sul dos Andes colombianos, entre aproximadamente o século I e o século IX d.C. É famosa por centenas de estátuas monolíticas antropomorfas e zoomorfas, esculpidas em pedra vulcânica e associadas a complexos funerários e cerimoniais. Constitui um dos conjuntos escultóricos pré-colombianos mais impressionantes da América do Sul." },
    { name: "Cultura Zenú (Sinú)", lng: -75.75, lat: 8.75, note: "O povo zenu ocupou as várzeas dos rios Sinú, San Jorge e Cauca, no norte da atual Colômbia, entre cerca de 200 a.C. e a chegada dos espanhóis. Desenvolveu um extenso sistema de canais e camalhões de terra para controlar as cheias sazonais e cultivar em terras alagadiças, além de produzir refinada ourivesaria. Formava cacicados organizados regionalmente, sem constituir um estado centralizado único." },
    { name: "Cultura Tairona", lng: -73.9, lat: 11.2, note: "Instalada nas encostas e no litoral da Serra Nevada de Santa Marta, no norte da Colômbia, a cultura tairona desenvolveu-se a partir de cerca do ano 200 d.C., construindo aldeias em terraços de pedra ligadas por escadarias, como a posteriormente chamada 'Cidade Perdida'. Destacou-se pela metalurgia do ouro e por uma intensa rede de trocas entre as terras altas e a costa caribenha. Resistiu à conquista espanhola até o final do século XVI." },
    { name: "Cultura Casarabe (Llanos de Mojos)", lng: -64.9, lat: -14.8, note: "Nas savanas alagáveis dos Llanos de Mojos, na Amazônia boliviana, a cultura Casarabe construiu, entre cerca de 500 e 1400 d.C., uma extensa paisagem de montículos monumentais interligados por calçadas e canais de drenagem. Esse sistema hidráulico sustentava o cultivo intensivo de milho e revela uma sociedade amazônica pré-colombiana com urbanismo e hierarquia territorial complexos, muito além do modelo de pequenas aldeias dispersas." },
    { name: "Cultura Marajoara", lng: -49.5, lat: -0.9, note: "Na Ilha de Marajó, na foz do rio Amazonas, floresceu entre cerca de 400 e 1300 d.C. a cultura marajoara, um cacicado estratificado que construiu grandes montes artificiais (tesos) para moradia, cerimônias e sepultamentos. É famosa por sua cerâmica polícroma finamente decorada, uma das mais elaboradas da América pré-colombiana. Contraria a ideia de que a Amazônia só abrigou pequenos grupos dispersos, revelando complexidade social significativa." },
    { name: "Geoglifos do Acre", lng: -67.8, lat: -9.9, note: "No sudoeste da Amazônia, no atual estado brasileiro do Acre, populações indígenas escavaram, a partir de cerca de mil anos antes de Cristo, centenas de grandes estruturas geométricas de terra — valas, taludes e recintos circulares ou quadrangulares — hoje visíveis sobretudo após desmatamento e por sensoriamento remoto. A função exata dos geoglifos ainda é debatida entre uso cerimonial, habitacional e de gestão da paisagem florestal. Revelam ocupação humana antiga e organizada na floresta muito antes da chegada europeia." },
    { name: "Cultura de La Aguada", lng: -66.1, lat: -28.4, note: "Nos vales pré-andinos de Catamarca e La Rioja, no noroeste da Argentina, floresceu entre aproximadamente 500 e 900 d.C. a cultura de La Aguada, conhecida por sua cerâmica e metalurgia de bronze e cobre com iconografia xamânica de felinos e figuras híbridas. Praticava agricultura em terraços e mantinha centros cerimoniais organizados, representando um dos desenvolvimentos sociais mais complexos do período de integração regional andina no sul do continente." },
    { name: "Cultura Huasteca", lng: -98.85, lat: 22, note: "Povo mesoamericano da planície costeira do Golfo do México, na região historicamente chamada Huasteca (atuais Tamaulipas, San Luis Potosí e norte de Veracruz). Falantes de uma língua aparentada ao maia, mas geograficamente isolados dos demais povos maias, desenvolveram centros como Tamtoc. A região seria posteriormente incorporada, em parte, ao Império Asteca no século XV." },
    { name: "Tradição de Teuchitlán", lng: -103.85, lat: 20.75, note: "Complexo cultural do oeste do México, centrado na região do vulcão de Tequila, em Jalisco, conhecido por suas características tumbas de tiro e por arquitetura circular única na Mesoamérica, como os montículos de Guachimontones. Floresceu aproximadamente entre 300 a.C. e 900 d.C., mantendo redes de trocas com outras regiões mesoamericanas. Distingue-se claramente das tradições arquitetônicas do centro do México, como Teotihuacan." },
    { name: "Reino de Cinda (Kindah)", lng: 44.72, lat: 20.5, note: "Confederação tribal árabe do Nejd, fundada por volta de 425 d.C. sob patrocínio himiarita, com capital em Qaryat al-Faw. Foi a primeira monarquia beduína centralizada conhecida na Arábia central, tendo como um de seus membros mais famosos o poeta pré-islâmico Imru' al-Qais. Entrou em colapso em meados do século VI, após perder o apoio himiarita e sofrer revoltas tribais." },
  ],
  [600]: [
    { name: "Antes (Ucrânia)", lng: 32, lat: 49, note: "Os antes formavam uma confederação tribal eslava oriental estabelecida entre os rios Dniester e Dniepre, na atual Ucrânia, conhecida por fontes bizantinas e góticas (como Jordanes e Procópio) desde o século VI. Mantinham relações ora hostis, ora de aliança com o Império Bizantino contra ávaros e outros povos das estepes. Por volta de 602, pouco depois do ano aqui indicado, os antes foram derrotados e dispersos por uma expedição do Canato Ávaro, desaparecendo das fontes históricas como entidade distinta." },
    { name: "Sogdiana", lng: 66.9, lat: 39.65, note: "A Sogdiana era uma região de cidades-estado de língua e cultura iranianas no coração da Ásia Central, com centros prósperos como Samarcanda e Bucara. Seus mercadores dominavam boa parte do comércio terrestre da Rota da Seda entre a China, a Índia e o mundo persa-bizantino, formando extensas redes de colônias mercantis. Politicamente fragmentada entre príncipes locais, a região reconhecia nominalmente a supremacia do Canato Turco, sem perder sua notável autonomia comercial e cultural." },
    { name: "Corásmia (Khwarazm)", lng: 60.6, lat: 42.3, note: "Corásmia era um antigo reino iraniano situado ao sul do mar de Aral, ao longo do baixo curso do rio Amu Dária, governado pela dinastia local afríguida desde cerca do ano 305. Posição estratégica nas rotas entre as estepes, a Pérsia e a Ásia Central lhe garantia papel comercial relevante, com moeda e escrita próprias. Manteve considerável autonomia política ao longo dos séculos seguintes, apesar da pressão de vizinhos mais poderosos." },
    { name: "Tocaristão (iabgus pós-heftalitas)", lng: 67.25, lat: 37.2, note: "O Tocaristão, a antiga Báctria, fragmentou-se em pequenos principados após o colapso do Império Heftalita por volta de 560, esmagado pela aliança entre o Império Sassânida e o Canato Turco. Esses principados eram governados por iabgus (título turco-heftalita) que reconheciam a supremacia turca, mas mantinham considerável autonomia local numa região historicamente budista e cruzamento de rotas da Rota da Seda." },
    { name: "Zhangzhung", lng: 81.3, lat: 31.1, note: "Zhangzhung foi um antigo reino do oeste do planalto tibetano, centro da religião bon pré-budista e de rotas comerciais que ligavam a Índia, a Pérsia e a China através do Himalaia. Por volta de 600 ainda era politicamente independente e rival da dinastia Yarlung, que dominava o Tibete central. Décadas mais tarde, entre 634 e 645, seria conquistado pelo rei tibetano Songtsen Gampo, sendo incorporado ao recém-unificado Império Tibetano." },
  ],
  [700]: [
    { name: "Wessex", lng: -1.5, lat: 51.05, note: "Reino dos saxões ocidentais, um dos sete reinos da Heptarquia anglo-saxônica, centrado em torno de Winchester, no sul da Inglaterra. Viria a se tornar, séculos depois, o núcleo em torno do qual a Inglaterra se unificou." },
    { name: "Mércia", lng: -1.7, lat: 52.6, note: "Reino anglo-saxão das Midlands inglesas, centrado em Tamworth. Sob reis como Penda e, mais tarde, Offa, foi por vezes o mais poderoso dos reinos da Heptarquia." },
    { name: "Nortúmbria", lng: -1.8, lat: 55, note: "Reino anglo-saxão formado pela união de Bernícia e Deira, estendendo-se do rio Humber até a fronteira com os pictos, ao norte. Foi um importante centro de erudição cristã no período, sediando figuras como Beda, o Venerável." },
    { name: "Ânglia Oriental", lng: 1, lat: 52.4, note: "Reino anglo-saxão dos anglos orientais, correspondendo aproximadamente a Norfolk e Suffolk, no leste da Inglaterra. O célebre tesouro funerário de Sutton Hoo pertence a um de seus reis." },
    { name: "Essex", lng: 0.6, lat: 51.75, note: "Reino anglo-saxão dos saxões orientais, cobrindo a região que hoje leva seu nome e, por períodos, Londres. Um dos reinos menores e mais instáveis da Heptarquia, frequentemente sob a influência de vizinhos mais poderosos." },
    { name: "Sussex", lng: -0.5, lat: 50.87, note: "Reino anglo-saxão dos saxões do sul, na costa sul da Inglaterra em torno de Chichester. Um dos reinos mais antigos da Heptarquia, embora com influência limitada na política inglesa por estar geograficamente isolado." },
    { name: "Canato Cázaro", lng: 47.5, lat: 45.5, note: "Canato turco que dominava as estepes do baixo Volga e do norte do Cáucaso, com capital em Atil. Controlava rotas comerciais entre o mundo eslavo, bizantino e islâmico, e sua elite viria a se converter ao judaísmo décadas mais tarde." },
    { name: "Búlgaros do Volga", lng: 49.1, lat: 55.2, note: "Povo turco em processo de estabelecimento na confluência dos rios Volga e Kama, após migrar das estepes pônticas. Nos séculos seguintes formariam um Estado próprio, a Bulgária do Volga, importante entreposto comercial entre a Rússia e o mundo islâmico." },
    { name: "Cultura de San Agustín", lng: -76.26, lat: 1.88, note: "A cultura de San Agustín floresceu nas nascentes do rio Madalena, no sul dos Andes colombianos, entre aproximadamente o século I e o século IX d.C. É famosa por centenas de estátuas monolíticas antropomorfas e zoomorfas, esculpidas em pedra vulcânica e associadas a complexos funerários e cerimoniais. Constitui um dos conjuntos escultóricos pré-colombianos mais impressionantes da América do Sul." },
    { name: "Cultura Zenú (Sinú)", lng: -75.75, lat: 8.75, note: "O povo zenu ocupou as várzeas dos rios Sinú, San Jorge e Cauca, no norte da atual Colômbia, entre cerca de 200 a.C. e a chegada dos espanhóis. Desenvolveu um extenso sistema de canais e camalhões de terra para controlar as cheias sazonais e cultivar em terras alagadiças, além de produzir refinada ourivesaria. Formava cacicados organizados regionalmente, sem constituir um estado centralizado único." },
    { name: "Cultura Tairona", lng: -73.9, lat: 11.2, note: "Instalada nas encostas e no litoral da Serra Nevada de Santa Marta, no norte da Colômbia, a cultura tairona desenvolveu-se a partir de cerca do ano 200 d.C., construindo aldeias em terraços de pedra ligadas por escadarias, como a posteriormente chamada 'Cidade Perdida'. Destacou-se pela metalurgia do ouro e por uma intensa rede de trocas entre as terras altas e a costa caribenha. Resistiu à conquista espanhola até o final do século XVI." },
    { name: "Cultura Casarabe (Llanos de Mojos)", lng: -64.9, lat: -14.8, note: "Nas savanas alagáveis dos Llanos de Mojos, na Amazônia boliviana, a cultura Casarabe construiu, entre cerca de 500 e 1400 d.C., uma extensa paisagem de montículos monumentais interligados por calçadas e canais de drenagem. Esse sistema hidráulico sustentava o cultivo intensivo de milho e revela uma sociedade amazônica pré-colombiana com urbanismo e hierarquia territorial complexos, muito além do modelo de pequenas aldeias dispersas." },
    { name: "Cultura Marajoara", lng: -49.5, lat: -0.9, note: "Na Ilha de Marajó, na foz do rio Amazonas, floresceu entre cerca de 400 e 1300 d.C. a cultura marajoara, um cacicado estratificado que construiu grandes montes artificiais (tesos) para moradia, cerimônias e sepultamentos. É famosa por sua cerâmica polícroma finamente decorada, uma das mais elaboradas da América pré-colombiana. Contraria a ideia de que a Amazônia só abrigou pequenos grupos dispersos, revelando complexidade social significativa." },
    { name: "Geoglifos do Acre", lng: -67.8, lat: -9.9, note: "No sudoeste da Amazônia, no atual estado brasileiro do Acre, populações indígenas escavaram, a partir de cerca de mil anos antes de Cristo, centenas de grandes estruturas geométricas de terra — valas, taludes e recintos circulares ou quadrangulares — hoje visíveis sobretudo após desmatamento e por sensoriamento remoto. A função exata dos geoglifos ainda é debatida entre uso cerimonial, habitacional e de gestão da paisagem florestal. Revelam ocupação humana antiga e organizada na floresta muito antes da chegada europeia." },
    { name: "Cultura de La Aguada", lng: -66.1, lat: -28.4, note: "Nos vales pré-andinos de Catamarca e La Rioja, no noroeste da Argentina, floresceu entre aproximadamente 500 e 900 d.C. a cultura de La Aguada, conhecida por sua cerâmica e metalurgia de bronze e cobre com iconografia xamânica de felinos e figuras híbridas. Praticava agricultura em terraços e mantinha centros cerimoniais organizados, representando um dos desenvolvimentos sociais mais complexos do período de integração regional andina no sul do continente." },
    { name: "Cultura Huasteca", lng: -98.85, lat: 22, note: "Povo mesoamericano da planície costeira do Golfo do México, na região historicamente chamada Huasteca (atuais Tamaulipas, San Luis Potosí e norte de Veracruz). Falantes de uma língua aparentada ao maia, mas geograficamente isolados dos demais povos maias, desenvolveram centros como Tamtoc. A região seria posteriormente incorporada, em parte, ao Império Asteca no século XV." },
    { name: "Tradição de Teuchitlán", lng: -103.85, lat: 20.75, note: "Complexo cultural do oeste do México, centrado na região do vulcão de Tequila, em Jalisco, conhecido por suas características tumbas de tiro e por arquitetura circular única na Mesoamérica, como os montículos de Guachimontones. Floresceu aproximadamente entre 300 a.C. e 900 d.C., mantendo redes de trocas com outras regiões mesoamericanas. Distingue-se claramente das tradições arquitetônicas do centro do México, como Teotihuacan." },
    { name: "Langkasuka", lng: 101.3, lat: 6.8, note: "Langkasuka foi um dos mais antigos reinos malaios, situado no norte da península Malaia, na região que hoje corresponde a Kedah e Pattani. Registros chineses da dinastia Liang afirmam que o reino já existia havia cerca de 400 anos quando enviou sua primeira embaixada à China em 515 d.C., o que situa sua fundação por volta do século I ou II. Prosperou como entreposto comercial hindu-budista até entrar na órbita de influência de Srivijaya por volta do século VII." },
    { name: "Srivijaya", lng: 104.75, lat: -2.99, note: "Srivijaya foi um império talassocrático budista centrado em Palembang, no sudeste de Sumatra, que viria a dominar as rotas comerciais do estreito de Malaca nos séculos seguintes. Por volta de 700 d.C. já despontava como potência regional, período de sua inscrição fundadora de Kedukan Bukit (683 d.C.). No dataset, essa área de Sumatra aparece como espaço em branco no ano 700, sem nome atribuído." },
    { name: "Cidades-Estado Pyu", lng: 95.3, lat: 18.8, note: "Povo de língua tibeto-birmanesa que ocupava o vale do rio Irrawaddy, na atual Mianmar, desde cerca do século II a.C. Por volta do ano 700, Sri Ksetra (perto da atual Pyay) despontava como a principal cidade-estado pyu, mantendo contatos diplomáticos registrados com a China Tang. O sistema de cidades-estado pyu entrou em declínio após incursões do reino de Nanzhao no século IX e foi sucedido pelo Reino de Pagan, já formado pelos birmaneses por volta do ano 1000." },
  ],
  [900]: [
    { name: "Cultura de San Agustín", lng: -76.26, lat: 1.88, note: "A cultura de San Agustín floresceu nas nascentes do rio Madalena, no sul dos Andes colombianos, entre aproximadamente o século I e o século IX d.C. É famosa por centenas de estátuas monolíticas antropomorfas e zoomorfas, esculpidas em pedra vulcânica e associadas a complexos funerários e cerimoniais. Constitui um dos conjuntos escultóricos pré-colombianos mais impressionantes da América do Sul." },
    { name: "Cultura Zenú (Sinú)", lng: -75.75, lat: 8.75, note: "O povo zenu ocupou as várzeas dos rios Sinú, San Jorge e Cauca, no norte da atual Colômbia, entre cerca de 200 a.C. e a chegada dos espanhóis. Desenvolveu um extenso sistema de canais e camalhões de terra para controlar as cheias sazonais e cultivar em terras alagadiças, além de produzir refinada ourivesaria. Formava cacicados organizados regionalmente, sem constituir um estado centralizado único." },
    { name: "Confederação Muísca", lng: -74.07, lat: 4.71, note: "No planalto cundiboyacense dos Andes colombianos, os muíscas formaram, a partir de cerca do século IX, uma confederação de cacicados encabeçada pelo zipa de Bacatá (atual Bogotá) e pelo zaque de Hunza (atual Tunja). Praticavam agricultura em terraços, mineração de sal e esmeraldas e uma sofisticada metalurgia de ouro e tumbaga, associada à lenda de El Dorado. Foi conquistada pelos espanhóis apenas no século XVI." },
    { name: "Cultura Tairona", lng: -73.9, lat: 11.2, note: "Instalada nas encostas e no litoral da Serra Nevada de Santa Marta, no norte da Colômbia, a cultura tairona desenvolveu-se a partir de cerca do ano 200 d.C., construindo aldeias em terraços de pedra ligadas por escadarias, como a posteriormente chamada 'Cidade Perdida'. Destacou-se pela metalurgia do ouro e por uma intensa rede de trocas entre as terras altas e a costa caribenha. Resistiu à conquista espanhola até o final do século XVI." },
    { name: "Cultura Casarabe (Llanos de Mojos)", lng: -64.9, lat: -14.8, note: "Nas savanas alagáveis dos Llanos de Mojos, na Amazônia boliviana, a cultura Casarabe construiu, entre cerca de 500 e 1400 d.C., uma extensa paisagem de montículos monumentais interligados por calçadas e canais de drenagem. Esse sistema hidráulico sustentava o cultivo intensivo de milho e revela uma sociedade amazônica pré-colombiana com urbanismo e hierarquia territorial complexos, muito além do modelo de pequenas aldeias dispersas." },
    { name: "Cultura Marajoara", lng: -49.5, lat: -0.9, note: "Na Ilha de Marajó, na foz do rio Amazonas, floresceu entre cerca de 400 e 1300 d.C. a cultura marajoara, um cacicado estratificado que construiu grandes montes artificiais (tesos) para moradia, cerimônias e sepultamentos. É famosa por sua cerâmica polícroma finamente decorada, uma das mais elaboradas da América pré-colombiana. Contraria a ideia de que a Amazônia só abrigou pequenos grupos dispersos, revelando complexidade social significativa." },
    { name: "Geoglifos do Acre", lng: -67.8, lat: -9.9, note: "No sudoeste da Amazônia, no atual estado brasileiro do Acre, populações indígenas escavaram, a partir de cerca de mil anos antes de Cristo, centenas de grandes estruturas geométricas de terra — valas, taludes e recintos circulares ou quadrangulares — hoje visíveis sobretudo após desmatamento e por sensoriamento remoto. A função exata dos geoglifos ainda é debatida entre uso cerimonial, habitacional e de gestão da paisagem florestal. Revelam ocupação humana antiga e organizada na floresta muito antes da chegada europeia." },
    { name: "Cultura de La Aguada", lng: -66.1, lat: -28.4, note: "Nos vales pré-andinos de Catamarca e La Rioja, no noroeste da Argentina, floresceu entre aproximadamente 500 e 900 d.C. a cultura de La Aguada, conhecida por sua cerâmica e metalurgia de bronze e cobre com iconografia xamânica de felinos e figuras híbridas. Praticava agricultura em terraços e mantinha centros cerimoniais organizados, representando um dos desenvolvimentos sociais mais complexos do período de integração regional andina no sul do continente." },
  ],
  [1000]: [
    { name: "Cultura Hohokam", lng: -111.9, lat: 33.2, note: "Povo agricultor do deserto de Sonora, no atual Arizona, famoso por construir extensos sistemas de canais de irrigação a partir do rio Gila e do rio Salt. Prosperou entre cerca de 300 e 1450 d.C., com grandes aldeias como Snaketown e, mais tarde, estruturas monumentais como a Casa Grande. Distinta dos povos ancestrais Pueblo mais ao norte, a cultura Hohokam entrou em declínio no século XV, antes da chegada dos espanhóis." },
    { name: "Cultura Mogollon", lng: -108.1, lat: 32.85, note: "Cultura pré-histórica do sudoeste norte-americano, nas montanhas e vales do atual Novo México e leste do Arizona, que combinava agricultura de milho com caça e coleta. Ficou famosa pela cerâmica Mimbres, com desenhos geométricos e figurativos de grande refinamento, produzida sobretudo entre 1000 e 1130 d.C. A tradição Mogollon persistiu, com transformações locais, até cerca de 1450." },
    { name: "Banu Hilal", lng: 46.5, lat: 24.5, note: "Grande confederação de tribos beduínas originária do Nejd e do Hejaz, na Arábia central, antes de sua migração em massa para o Egito e o Magrebe a partir de 1051, a mando dos fatímidas. Essa migração, narrada na epopeia popular 'Taghribat Bani Hilal', teve papel central na arabização do norte da África. Em 1000, ainda habitavam suas terras originárias na Arábia." },
  ],
  [1100]: [
    { name: "Puebloanos Ancestrais (Chaco Canyon)", lng: -107.92, lat: 36.06, note: "Entre os séculos IX e XII, o Chaco Canyon, no atual Novo México, foi o centro de uma sofisticada cultura ancestral puebloana (também chamada Anasazi), com grandes complexos multiandares de alvenaria como o Pueblo Bonito e uma rede de estradas cerimoniais ligando dezenas de povoados satélites. Por volta de 1100 essa civilização estava próxima do apogeu político e religioso, antes de entrar em declínio no século seguinte devido a secas prolongadas." },
    { name: "Cultura Hohokam", lng: -111.9, lat: 33.2, note: "Povo agricultor do deserto de Sonora, no atual Arizona, famoso por construir extensos sistemas de canais de irrigação a partir do rio Gila e do rio Salt. Prosperou entre cerca de 300 e 1450 d.C., com grandes aldeias como Snaketown e, mais tarde, estruturas monumentais como a Casa Grande. Distinta dos povos ancestrais Pueblo mais ao norte, a cultura Hohokam entrou em declínio no século XV, antes da chegada dos espanhóis." },
    { name: "Cultura Mogollon", lng: -108.1, lat: 32.85, note: "Cultura pré-histórica do sudoeste norte-americano, nas montanhas e vales do atual Novo México e leste do Arizona, que combinava agricultura de milho com caça e coleta. Ficou famosa pela cerâmica Mimbres, com desenhos geométricos e figurativos de grande refinamento, produzida sobretudo entre 1000 e 1130 d.C. A tradição Mogollon persistiu, com transformações locais, até cerca de 1450." },
    { name: "Cultura Fremont", lng: -112.5, lat: 37.9, note: "No centro e sul do atual Utah, a cultura fremont combinava pequena agricultura de milho com caça e coleta, deixando marcas distintas como cestaria de fibra vegetal, mocassins de couro de bisão e numerosos petróglifos e pinturas rupestres. Contemporânea e vizinha dos povos ancestrais puebloanos, permaneceu mais dispersa e menos urbanizada, ocupando a região aproximadamente entre 400 e 1300 d.C." },
  ],
  [1200]: [
    { name: "Cultura Hohokam", lng: -111.9, lat: 33.2, note: "Povo agricultor do deserto de Sonora, no atual Arizona, famoso por construir extensos sistemas de canais de irrigação a partir do rio Gila e do rio Salt. Prosperou entre cerca de 300 e 1450 d.C., com grandes aldeias como Snaketown e, mais tarde, estruturas monumentais como a Casa Grande. Distinta dos povos ancestrais Pueblo mais ao norte, a cultura Hohokam entrou em declínio no século XV, antes da chegada dos espanhóis." },
    { name: "Cultura Mogollon", lng: -108.1, lat: 32.85, note: "Cultura pré-histórica do sudoeste norte-americano, nas montanhas e vales do atual Novo México e leste do Arizona, que combinava agricultura de milho com caça e coleta. Ficou famosa pela cerâmica Mimbres, com desenhos geométricos e figurativos de grande refinamento, produzida sobretudo entre 1000 e 1130 d.C. A tradição Mogollon persistiu, com transformações locais, até cerca de 1450." },
  ],
  [1279]: [
    { name: "Reino Daju de Darfur", lng: 24.3, lat: 12.8, note: "Antiga monarquia da região de Darfur, no atual oeste do Sudão, com centro nas terras altas do Jebel Marra. Por volta de 1279 os Daju já dominavam a área havia gerações, tendo sucedido os antigos Tora; o cronista egípcio Al-Maqrizi descreveu-o mais tarde como um reino relativamente forte situado entre Kanem e o vale do Nilo. O reino Daju perduraria até ser substituído pela dinastia Tunjur, já no século XV." },
    { name: "Reino de Gapi (Ternate)", lng: 127.38, lat: 0.8, note: "Segundo a tradição local, o reino de Ternate foi fundado em 1257 sob o título de kolano (rei), sendo então chamado de Reino de Gapi. Situado numa pequena ilha vulcânica do norte das Molucas, prosperou com o cultivo e comércio do cravo-da-índia e, por volta de 1322, uniu-se a Tidore, Bacã e Jailolo na confederação conhecida como Moloku Kie Raha. Somente no final do século XV, com a conversão ao islamismo, o reino adotaria o título de sultanato." },
  ],
  [1300]: [
    { name: "Reino de Gapi (Ternate)", lng: 127.38, lat: 0.8, note: "Segundo a tradição local, o reino de Ternate foi fundado em 1257 sob o título de kolano (rei), sendo então chamado de Reino de Gapi. Situado numa pequena ilha vulcânica do norte das Molucas, prosperou com o cultivo e comércio do cravo-da-índia e, por volta de 1322, uniu-se a Tidore, Bacã e Jailolo na confederação conhecida como Moloku Kie Raha. Somente no final do século XV, com a conversão ao islamismo, o reino adotaria o título de sultanato." },
    { name: "Reino de Tidore", lng: 127.4, lat: 0.65, note: "Tidore, ilha vizinha de Ternate no norte das Molucas, era sede de um reino governado por kolanos (reis) cuja origem é situada por tradições locais ainda no século XI, embora essa datação seja debatida pelos historiadores. Por volta de 1322, Tidore integrou-se à confederação Moloku Kie Raha, ao lado de Ternate, Bacã e Jailolo, tornando-se sua principal rival na disputa pelo lucrativo comércio do cravo-da-índia. A conversão ao islamismo e a criação formal do sultanato ocorreriam apenas no final do século XV." },
  ],
  [1400]: [
    { name: "Reino de Gapi (Ternate)", lng: 127.38, lat: 0.8, note: "Segundo a tradição local, o reino de Ternate foi fundado em 1257 sob o título de kolano (rei), sendo então chamado de Reino de Gapi. Situado numa pequena ilha vulcânica do norte das Molucas, prosperou com o cultivo e comércio do cravo-da-índia e, por volta de 1322, uniu-se a Tidore, Bacã e Jailolo na confederação conhecida como Moloku Kie Raha. Somente no final do século XV, com a conversão ao islamismo, o reino adotaria o título de sultanato." },
    { name: "Reino de Tidore", lng: 127.4, lat: 0.65, note: "Tidore, ilha vizinha de Ternate no norte das Molucas, era sede de um reino governado por kolanos (reis) cuja origem é situada por tradições locais ainda no século XI, embora essa datação seja debatida pelos historiadores. Por volta de 1322, Tidore integrou-se à confederação Moloku Kie Raha, ao lado de Ternate, Bacã e Jailolo, tornando-se sua principal rival na disputa pelo lucrativo comércio do cravo-da-índia. A conversão ao islamismo e a criação formal do sultanato ocorreriam apenas no final do século XV." },
  ],
  [1500]: [
    { name: "Estado Tarasco (Purépecha)", lng: -101.6, lat: 19.6, note: "Poderoso estado centrado na região dos lagos de Michoacán, com capital em Tzintzuntzan, às margens do lago Pátzcuaro. Os purépechas falavam uma língua isolada, sem parentesco com o náuatle ou outras línguas mesoamericanas vizinhas, e desenvolveram notável metalurgia do cobre e bronze. Foi um dos poucos estados mesoamericanos a resistir com sucesso às tentativas de conquista do Império Asteca, mantendo sua independência até a chegada dos espanhóis." },
    { name: "Confederação Powhatan", lng: -76.7, lat: 37.3, note: "Aliança de povos algonquinos da região da baía de Chesapeake, na Virgínia, unificada sob a liderança do chefe Powhatan (Wahunsenacawh) entre o final do século XVI e o início do XVII. Reunia cerca de trinta tribos tributárias e foi a primeira grande confederação indígena com que os colonos ingleses de Jamestown tiveram contato, em 1607." },
    { name: "Confederação Wampanoag", lng: -71.3, lat: 41.7, note: "Povo algonquino da costa sudeste da Nova Inglaterra, organizado em confederação de aldeias sob um sachem principal, com centro tradicional na região da baía de Narragansett e Monte Hope. Ficou historicamente marcado pela aliança com os peregrinos de Plymouth em 1620 e, décadas depois, pela liderança de Metacomet (Rei Filipe) na guerra de 1675-1676 contra os colonos ingleses." },
  ],
  [1700]: [
    { name: "Reduções jesuíticas guaranis", lng: -55.5, lat: -27.3, note: "A partir de 1609, jesuítas espanhóis organizaram populações guaranis em reduções — aldeias missionárias autônomas — na região entre os rios Paraná, Paraguai e Uruguai, no atual encontro de fronteiras entre Paraguai, Argentina e Brasil. Por volta de 1700, cerca de trinta reduções abrigavam mais de cem mil guaranis, com economia agrícola comunitária e relativa autonomia frente às autoridades coloniais espanholas. O sistema foi extinto com a expulsão dos jesuítas dos domínios espanhóis em 1767." },
    { name: "Confederação Powhatan", lng: -76.7, lat: 37.3, note: "Aliança de povos algonquinos da região da baía de Chesapeake, na Virgínia, unificada sob a liderança do chefe Powhatan (Wahunsenacawh) entre o final do século XVI e o início do XVII. Reunia cerca de trinta tribos tributárias e foi a primeira grande confederação indígena com que os colonos ingleses de Jamestown tiveram contato, em 1607." },
    { name: "Confederação Wampanoag", lng: -71.3, lat: 41.7, note: "Povo algonquino da costa sudeste da Nova Inglaterra, organizado em confederação de aldeias sob um sachem principal, com centro tradicional na região da baía de Narragansett e Monte Hope. Ficou historicamente marcado pela aliança com os peregrinos de Plymouth em 1620 e, décadas depois, pela liderança de Metacomet (Rei Filipe) na guerra de 1675-1676 contra os colonos ingleses." },
  ],
};

export function knownGapMarkersFor(year: number): KnownGapMarker[] {
  return KNOWN_GAP_MARKERS[year] ?? [];
}

export function knownGapNote(name: string): string | null {
  for (const markers of Object.values(KNOWN_GAP_MARKERS)) {
    const match = markers.find((marker) => marker.name === name);
    if (match) return match.note;
  }
  return null;
}
