// Pre-generated, era-aware historical summaries for the major
// territories/empires in the dataset. Keys match the GeoJSON
// NAME/SUBJECTO exactly (same convention as curatedTerritories.ts).
//
// Each entry is a list of periods; the side panel picks the period that
// contains the year currently shown on the slider, so clicking "Roman
// Empire" in 100 BC vs 400 AD gives era-appropriate text. Territories
// not listed here fall back to a generic message.
//
// This is a curated subset (the historically prominent states), not the
// full ~1700-name dataset — see README.
export type EraSummary = { from: number; to: number; text: string };

export const TERRITORY_SUMMARIES: Record<string, EraSummary[]> = {
  // === Ancient Near East / Mediterranean / classical world ===
  Ur: [{ from: -2900, to: -500, text: "Ur foi uma das mais importantes cidades-estado da Suméria, situada no sul da Mesopotâmia, perto do antigo curso do rio Eufrates, no atual Iraque. Alcançou seu apogeu durante a Terceira Dinastia de Ur, por volta de 2112 a.C., quando governou um vasto império e produziu grandes zigurates dedicados ao deus-lua Nanna. Foi também célebre por seus túmulos reais e por sua ligação tradicional ao patriarca bíblico Abraão." }],
  Elam: [{ from: -2700, to: -539, text: "Elam foi uma antiga civilização localizada no sudoeste do atual Irã, tendo como principais centros as cidades de Susa e Anshan. Rival e vizinha da Mesopotâmia, desenvolveu uma escrita própria e alternou períodos de guerra e comércio com sumérios, acádios e babilônios. Seu poder declinou após conquistas assírias e persas, sendo finalmente absorvida pelo Império Aquemênida." }],
  Babylonia: [
    { from: -1894, to: -1595, text: "A Babilônia foi um reino da baixa Mesopotâmia centrado na cidade de Babilônia, às margens do Eufrates. Sob o rei Hamurábi, no século XVIII a.C., unificou a região e ficou célebre por seu código de leis, um dos mais antigos conjuntos jurídicos conhecidos." },
    { from: -626, to: -539, text: "No período neobabilônico, a Babilônia renasceu como grande potência sob Nabopolassar e Nabucodonosor II, que reconstruíram a cidade com esplendor. Deste período datam os famosos jardins suspensos e a Porta de Ishtar, além do exílio dos judeus. O reino caiu diante de Ciro, o Grande, da Pérsia, em 539 a.C." },
  ],
  Assyria: [
    { from: -1350, to: -1050, text: "A Assíria foi um reino do norte da Mesopotâmia centrado na cidade de Assur, às margens do rio Tigre. No período médio-assírio afirmou-se como potência militar, expandindo-se sobre os territórios vizinhos e desenvolvendo uma poderosa tradição guerreira e administrativa." },
    { from: -911, to: -609, text: "No período neoassírio, a Assíria tornou-se o maior império do Oriente Próximo, dominando da Mesopotâmia ao Egito a partir de capitais como Nínive e Nimrud. Era temida por seu exército profissional e por sua administração implacável. Enfraquecida por revoltas, sucumbiu à aliança de medos e babilônios com a queda de Nínive em 612 a.C." },
  ],
  Egypt: [
    { from: -3100, to: -30, text: "O Egito Antigo foi uma das mais duradouras civilizações da história, desenvolvida ao longo do vale do rio Nilo, no nordeste da África. Governado por faraós considerados divinos, ergueu monumentos como as pirâmides de Gizé e a Esfinge, e legou uma rica escrita hieroglífica, religião e arte. Depois de milênios de esplendor, foi conquistado por persas, gregos e, por fim, incorporado a Roma após a morte de Cleópatra em 30 a.C." },
    { from: 641, to: 1798, text: "Após séculos de domínio romano e bizantino, o Egito foi conquistado pelos árabes muçulmanos no século VII, tornando-se um importante centro islâmico. Sob dinastias como os fatímidas, aiúbidas e mamelucos, o Cairo floresceu como polo de comércio, religião e cultura, antes de ser integrado ao Império Otomano em 1517." },
    { from: 1801, to: 2025, text: "No período moderno, o Egito passou pela modernização iniciada por Maomé Ali, pela ocupação britânica e, em 1922, pela independência. Tornou-se república em 1953 e figura central do mundo árabe, palco de eventos como a nacionalização do Canal de Suez e a Primavera Árabe de 2011." },
  ],
  Canaan: [{ from: -3000, to: -1200, text: "Canaã era a região do Levante meridional que corresponde aproximadamente ao atual Israel, Palestina, Líbano e partes da Síria e Jordânia. Habitada por povos cananeus organizados em cidades-estado, foi um vibrante entreposto comercial entre o Egito, a Mesopotâmia e o Mediterrâneo. É amplamente mencionada em textos egípcios e na tradição bíblica como a Terra Prometida." }],
  Minoan: [{ from: -3000, to: -1100, text: "A civilização minoica floresceu na ilha de Creta, no mar Egeu, sendo considerada a primeira grande civilização da Europa. Ficou célebre por seus palácios como o de Cnossos, por seus afrescos coloridos e por uma cultura marítima próspera. Seu declínio está associado à erupção vulcânica de Thera e à posterior ascensão dos micênicos." }],
  Cycladic: [{ from: -3200, to: -2000, text: "A civilização cicládica desenvolveu-se nas ilhas Cíclades, no mar Egeu, durante a Idade do Bronze. É especialmente conhecida por suas enigmáticas figuras de mármore de linhas geométricas e minimalistas, hoje admiradas como obras-primas da arte antiga. Sua sociedade marítima comerciava obsidiana e metais por todo o Egeu antes de ser eclipsada pelas culturas minoica e micênica." }],
  Hittites: [{ from: -1650, to: -1178, text: "Os hititas formaram um poderoso império na Anatólia central, com capital em Hattusa, no atual território da Turquia. Foram pioneiros no uso do ferro e rivais do Egito, com quem travaram a batalha de Cadesh e assinaram um dos primeiros tratados de paz conhecidos. Seu império entrou em colapso durante o grande desmoronamento da Idade do Bronze." }],
  Urartu: [{ from: -860, to: -590, text: "Urartu foi um reino da Idade do Ferro situado em torno do lago Van, no planalto armênio, entre a atual Turquia, Armênia e Irã. Rival da Assíria, destacou-se pela engenharia hidráulica, pela metalurgia e por suas fortalezas montanhosas. Enfraquecido por invasões, desapareceu diante do avanço dos medos e citas." }],
  Phrygians: [{ from: -1200, to: -700, text: "Os frígios foram um povo que se estabeleceu na Anatólia centro-ocidental após a queda do império hitita, com capital em Górdio. São lembrados na tradição pelos lendários reis Midas, do toque de ouro, e Górdio, do célebre nó górdio. Seu reino foi devastado por invasões cimérias e depois absorvido por lídios e persas." }],
  "Indus valley civilization": [{ from: -3300, to: -1300, text: "A civilização do vale do Indo foi uma das primeiras grandes civilizações urbanas do mundo, estendendo-se pelo atual Paquistão e noroeste da Índia. Suas cidades, como Harappa e Mohenjo-Daro, impressionam pelo planejamento urbano, sistemas de esgoto e uma escrita ainda não decifrada. Seu declínio, por volta de 1300 a.C., é atribuído a mudanças climáticas e ao deslocamento de rios." }],
  "Achaemenid Empire": [{ from: -550, to: -330, text: "O Império Aquemênida, fundado por Ciro, o Grande, foi o primeiro grande império persa e o maior do mundo antigo até então, estendendo-se do vale do Indo à Ásia Menor e ao Egito. Notável por sua tolerância cultural, sua rede de estradas e o sistema administrativo de satrapias, teve capitais como Persépolis e Susa. Foi conquistado por Alexandre, o Grande, em 330 a.C." }],
  "Empire of Alexander": [{ from: -336, to: -323, text: "O império de Alexandre, o Grande, foi forjado em pouco mais de uma década de campanhas militares que levaram o rei macedônio da Grécia ao Egito e até a Índia. Derrotando o Império Persa, criou o maior domínio já visto até então e difundiu a cultura grega pelo Oriente. Com sua morte precoce em 323 a.C., o império fragmentou-se entre seus generais, os diádocos, inaugurando o período helenístico." }],
  "Greek city-states": [{ from: -800, to: -146, text: "As cidades-estado gregas, ou póleis, como Atenas, Esparta, Corinto e Tebas, foram comunidades políticas independentes que definiram a civilização grega antiga. Berço da democracia, da filosofia, do teatro e dos Jogos Olímpicos, alternaram cooperação e rivalidade, como nas Guerras Médicas contra a Pérsia e na Guerra do Peloponeso. Perderam a independência para a Macedônia e, por fim, para Roma." }],
  Macedonia: [{ from: -808, to: -146, text: "A Macedônia foi um reino do norte da Grécia que ascendeu de potência periférica a hegemônica sob Filipe II, que unificou as cidades gregas. Seu filho, Alexandre, o Grande, transformou-a no centro de um vasto império que espalhou a cultura helênica pelo mundo antigo. Após as guerras contra Roma, o reino foi dissolvido e tornou-se província romana em 146 a.C." }],
  "Macedon and Hellenic League": [{ from: -338, to: -322, text: "A Liga Helênica, também chamada Liga de Corinto, foi uma federação de cidades gregas organizada por Filipe II da Macedônia após sua vitória em Queroneia em 338 a.C. Sob a liderança macedônia, uniu os gregos, exceto Esparta, com o objetivo declarado de invadir a Pérsia. Serviu de base política para as campanhas de Alexandre, mas desintegrou-se após sua morte." }],
  Carthage: [{ from: -814, to: -146, text: "Cartago foi uma cidade fundada por colonos fenícios de Tiro na costa do atual norte da Tunísia. Tornou-se a maior potência comercial e marítima do Mediterrâneo ocidental, com uma poderosa marinha e uma rede de colônias. Após as três Guerras Púnicas contra Roma, foi arrasada em 146 a.C., encerrando sua história como cidade independente." }],
  "Carthaginian Empire": [{ from: -575, to: -146, text: "O Império Cartaginês foi a rede de territórios, colônias e rotas comerciais dominada por Cartago no Mediterrâneo ocidental, abrangendo o norte da África, a Ibéria, a Sardenha e a Sicília. Baseava sua força no comércio e em exércitos de mercenários, e teve em Aníbal seu maior general durante a Segunda Guerra Púnica. Foi definitivamente destruído por Roma em 146 a.C." }],
  Rome: [
    { from: -753, to: -509, text: "Roma teve início, segundo a tradição, com sua fundação em 753 a.C. às margens do rio Tibre, na península Itálica. Em seus primeiros séculos foi governada por reis, período em que absorveu influências etruscas, latinas e sabinas e lançou as bases de suas instituições. A expulsão do último rei em 509 a.C. deu origem à República." },
    { from: -509, to: 476, text: "Ao longo de mais de um milênio, Roma cresceu de uma cidade-estado do Lácio até o maior império da Antiguidade, dominando todo o Mediterrâneo, a Europa ocidental e o Oriente Próximo. Legou ao mundo o direito, a engenharia, a língua latina e formas de organização política que moldaram a civilização ocidental. Sua história abrange a Monarquia, a República e o Império, até a queda do Ocidente em 476 d.C." },
  ],
  "Roman Empire": [{ from: -27, to: 476, text: "O Império Romano surgiu quando Otávio, sob o título de Augusto, tornou-se o primeiro imperador em 27 a.C., encerrando a República. No seu apogeu, estendeu-se da Britânia ao Egito e da Ibéria à Mesopotâmia, unido por estradas, legiões e uma administração comum. Após séculos de esplendor e a longa Pax Romana, o Império do Ocidente ruiu em 476 d.C. diante das invasões germânicas." }],
  "Roman Republic": [{ from: -509, to: -27, text: "A República Romana foi o regime instaurado em 509 a.C. após a expulsão dos reis, caracterizado por magistrados eleitos, pelo Senado e pela divisão de poderes entre patrícios e plebeus. Durante esse período, Roma conquistou toda a Itália e expandiu-se pelo Mediterrâneo, derrotando Cartago nas Guerras Púnicas. Abalada por guerras civis e pela ambição de generais como César, a República deu lugar ao Império em 27 a.C." }],
  "Rome (Diocletianus)": [{ from: 284, to: 305, text: "Sob o imperador Diocleciano, que reinou de 284 a 305 d.C., Roma passou por profundas reformas destinadas a conter a crise do século III. Ele instituiu a Tetrarquia, dividindo o governo entre quatro co-imperadores, reorganizou as províncias e a economia, e reforçou o caráter absolutista do poder imperial. Seu reinado também ficou marcado pela última grande perseguição aos cristãos." }],
  "Byzantine Empire": [{ from: 330, to: 1453, text: "O Império Bizantino foi a continuação do Império Romano no Oriente, com capital em Constantinopla, fundada por Constantino em 330 d.C. De língua grega e fé cristã ortodoxa, preservou o legado romano e helênico por mil anos, com auge sob Justiniano e seu código de leis. Após séculos de declínio, caiu diante dos turcos otomanos com a tomada de Constantinopla em 1453." }],
  "Eastern Roman Empire": [{ from: 395, to: 1453, text: "O Império Romano do Oriente originou-se da divisão definitiva do Império Romano em 395 d.C., com capital em Constantinopla. Mais rico e urbanizado que o Ocidente, sobreviveu à queda deste e evoluiu para o que os historiadores chamam de Império Bizantino. Perdurou até 1453, quando Constantinopla foi conquistada pelos otomanos." }],
  "Western Roman Empire": [{ from: 395, to: 476, text: "O Império Romano do Ocidente resultou da partilha do Império Romano em 395 d.C., reunindo os territórios de língua latina da Europa ocidental e do norte da África. Fragilizado por crises econômicas, pressões nas fronteiras e sucessivas invasões germânicas, teve capitais como Roma e Ravena. Deixou de existir em 476 d.C., quando o general Odoacro depôs o último imperador, Rômulo Augústulo." }],
  "Seleucid Kingdom": [{ from: -312, to: -63, text: "O Reino Selêucida foi um dos grandes Estados helenísticos surgidos da fragmentação do império de Alexandre, fundado pelo general Seleuco I Nicátor em 312 a.C. Em seu apogeu, estendeu-se da Anatólia e Síria até a Pérsia e as fronteiras da Índia, difundindo a cultura grega pelo Oriente. Enfraquecido por revoltas e pela pressão de Roma e dos partos, foi por fim anexado por Pompeu em 63 a.C." }],
  "Ptolemaic Kingdom": [{ from: -305, to: -30, text: "O Reino Ptolomaico foi um Estado helenístico fundado por Ptolomeu I Sóter, general de Alexandre, o Grande, após a morte deste. Com capital em Alexandria, os Ptolomeus governaram o Egito por quase três séculos, promovendo a cultura grega e ao mesmo tempo adotando tradições faraônicas. O reino terminou com a morte de Cleópatra VII e a anexação do Egito por Roma." }],
  "Parthian Empire": [{ from: -247, to: 224, text: "O Império Parta, fundado pela dinastia arsácida, dominou o planalto iraniano e a Mesopotâmia, tornando-se rival de Roma no Oriente. Sua cavalaria e táticas de arqueiros montados garantiram vitórias importantes, como a de Carras contra os romanos. O império declinou por conflitos internos até ser substituído pelos sassânidas." }],
  "Sasanian Empire": [{ from: 224, to: 651, text: "O Império Sassânida, fundado por Ardashir I, foi a última grande potência persa antiga antes do Islã. Rival duradouro do Império Romano e depois Bizantino, revitalizou o zoroastrismo como religião oficial e alcançou notável desenvolvimento cultural e artístico. Enfraquecido por guerras, sucumbiu à expansão árabe-muçulmana no século VII." }],
  Scythians: [{ from: -700, to: -300, text: "Os citas eram povos nômades de língua irânica que dominaram as estepes ao norte do Mar Negro e da Ásia Central. Exímios cavaleiros e arqueiros, ficaram famosos por sua arte em ouro e por seus túmulos monumentais chamados kurgans. Sua confederação acabou absorvida por outros povos das estepes, como os sármatas." }],
  Sabines: [{ from: -750, to: -290, text: "Os sabinos eram um povo itálico que habitava as colinas a nordeste de Roma. A lenda do rapto das sabinas descreve a fusão inicial entre eles e os primeiros romanos, e vários costumes romanos teriam origem sabina. Foram gradualmente conquistados e integrados à República Romana." }],
  Celts: [{ from: -800, to: 100, text: "Os celtas foram um conjunto de povos que compartilhavam línguas e cultura, espalhados por grande parte da Europa, da Ibéria às Ilhas Britânicas. Organizados em tribos, destacaram-se na metalurgia do ferro e na arte decorativa de estilo La Tène. Foram progressivamente submetidos pela expansão romana e por migrações germânicas." }],

  // === South / East / Central Asia ===
  "Mauryan Empire": [{ from: -322, to: -185, text: "O Império Máuria, fundado por Chandragupta Máuria, foi o primeiro Estado a unificar a maior parte do subcontinente indiano. Sob o imperador Ashoka, alcançou seu apogeu e adotou o budismo, promovendo edifícios e éditos que difundiram princípios de não violência. Após a morte de Ashoka, o império fragmentou-se rapidamente." }],
  "Gupta Empire": [{ from: 320, to: 550, text: "O Império Gupta é frequentemente lembrado como uma era de ouro da Índia clássica, marcada por avanços em matemática, astronomia, literatura e artes. Governantes como Chandragupta II presidiram um período de prosperidade e florescimento do hinduísmo. As invasões dos hunos brancos e as pressões internas levaram ao seu declínio." }],
  Han: [{ from: -206, to: 220, text: "A dinastia Han foi uma das mais duradouras e influentes da história chinesa, consolidando o modelo imperial iniciado pelos Qin. Adotou o confucionismo como base do Estado, expandiu o território e abriu a Rota da Seda ao comércio com o Ocidente. O período Han é tão fundamental que o principal grupo étnico chinês ainda se autodenomina 'han'." }],
  "Han Empire": [{ from: -206, to: 220, text: "O Império Han governou a China por mais de quatro séculos, estabelecendo instituições burocráticas e um serviço civil baseado no mérito e no confucionismo. Sob imperadores como Wu, o território expandiu-se enormemente e a Rota da Seda ligou a China ao mundo mediterrâneo. Após um período de esplendor cultural e tecnológico, o império desintegrou-se em meio a revoltas e disputas entre senhores da guerra." }],
  Qin: [{ from: -221, to: -206, text: "A dinastia Qin, sob Qin Shi Huang, unificou pela primeira vez a China em um único império centralizado. Impôs padronização de escrita, moeda, pesos e medidas, além de iniciar a construção de partes da Grande Muralha e do famoso Exército de Terracota. Seu governo rígido e legalista provocou revoltas, e a dinastia ruiu poucos anos após a morte do primeiro imperador." }],
  "Zhow states": [{ from: -1046, to: -256, text: "Os Estados Zhou correspondem ao período em que a dinastia Zhou governou a China, o mais longo de sua história dinástica. Sob o conceito do Mandato do Céu, o poder central foi se fragmentando em numerosos Estados semi-independentes. As fases das Primaveras e Outonos e dos Reinos Combatentes trouxeram guerras constantes, mas também o florescimento filosófico de Confúcio, Laozi e outros pensadores." }],
  "Zhou states": [{ from: -1046, to: -256, text: "Os Estados Zhou referem-se à China sob a dinastia Zhou, marcada pela descentralização do poder em múltiplos principados. O ideal do Mandato do Céu legitimava o governante, enquanto rivalidades entre Estados levaram aos períodos das Primaveras e Outonos e dos Reinos Combatentes. Foi uma era de intensa efervescência intelectual, berço das grandes escolas filosóficas chinesas." }],
  "Sui Empire": [{ from: 581, to: 618, text: "O Império Sui reunificou a China após séculos de divisão que se seguiram à queda dos Han. Empreendeu obras monumentais, como o Grande Canal, que ligou o norte ao sul e impulsionou o comércio e a integração. O esgotamento provocado por guerras e projetos custosos levou à rápida queda da dinastia, sucedida pelos Tang." }],
  "Tang Empire": [{ from: 618, to: 907, text: "O Império Tang é considerado uma era de ouro da civilização chinesa, marcada por grande esplendor cultural, cosmopolitismo e expansão territorial. A capital Chang'an tornou-se uma das maiores cidades do mundo, e a poesia, a arte e o budismo floresceram. Revoltas internas, como a de An Lushan, enfraqueceram gradualmente o poder imperial até a fragmentação final." }],
  "Song Empire": [{ from: 960, to: 1279, text: "O Império Song destacou-se por notáveis avanços econômicos, tecnológicos e culturais, incluindo a pólvora, a imprensa por tipos móveis e o uso do papel-moeda. Apesar da prosperidade e do refinamento artístico, enfrentou pressão militar constante de povos do norte. Acabou conquistado pelos mongóis, que fundaram a dinastia Yuan." }],
  "Ming Chinese Empire": [{ from: 1368, to: 1644, text: "O Império Ming restaurou o governo chinês nativo após o domínio mongol dos Yuan. Foi um período de grande vitalidade, com as viagens marítimas do almirante Zheng He, a reconstrução da Grande Muralha e a construção da Cidade Proibida. Crises econômicas, rebeliões e pressões externas levaram ao seu colapso e à ascensão dos manchus." }],
  "Manchu Empire": [{ from: 1636, to: 1912, text: "O Império Manchu, mais conhecido como dinastia Qing, foi fundado pelos manchus, que conquistaram a China após a queda dos Ming. Governou o maior território da história imperial chinesa, incorporando a Mongólia, o Tibete e o Turquestão Oriental. No século XIX, o declínio, as pressões coloniais e revoltas internas culminaram no fim do sistema imperial em 1912." }],
  "Qing Empire": [{ from: 1636, to: 1912, text: "O Império Qing foi a última dinastia imperial da China, estabelecida pelos manchus. Sob imperadores como Kangxi e Qianlong, alcançou grande expansão territorial e prosperidade, mas enfrentou depois a decadência marcada pelas Guerras do Ópio e por rebeliões devastadoras. Sua queda em 1912 encerrou mais de dois milênios de governo imperial na China." }],
  Xiongnu: [{ from: -209, to: 155, text: "Os xiongnu formaram uma poderosa confederação nômade das estepes ao norte da China, considerados por muitos os grandes rivais da dinastia Han. Sob líderes como Modu Chanyu, ameaçaram constantemente as fronteiras chinesas, forçando tributos e acordos matrimoniais. Divisões internas e a pressão chinesa acabaram fragmentando e dispersando sua confederação." }],
  "Kushan Empire": [{ from: 30, to: 375, text: "O Império Kushan, de origem nômade iuechi, dominou a Ásia Central e o norte do subcontinente indiano, controlando rotas cruciais da Rota da Seda. Sob soberanos como Kanishka, tornou-se um grande difusor do budismo e berço da arte greco-budista de Gandara, mesclando influências helenísticas, persas e indianas." }],
  Bactria: [{ from: -256, to: -125, text: "O Reino Greco-Báctrio surgiu quando governantes helenísticos da Ásia Central se separaram do Império Selêucida. Situada no atual Afeganistão, a Báctria foi um vibrante ponto de encontro entre as culturas grega, persa e indiana, antes de cair diante de invasores nômades." }],
  Magadha: [{ from: -600, to: -300, text: "Magadha foi um dos grandes reinos da Índia antiga, no vale do Ganges, e berço de impérios como o Máuria. Foi um importante centro do surgimento do budismo e do jainismo, além de núcleo do primeiro grande império pan-indiano." }],
  Satavahanihara: [{ from: -100, to: 220, text: "O império Satavahana dominou o Decã, servindo de ponte cultural e comercial entre o norte e o sul da Índia. Foram protetores do budismo e do comércio, cunhando moedas próprias e patrocinando monumentos como os de Amaravati." }],
  Pallavas: [{ from: 275, to: 897, text: "A dinastia Pallava governou o sudeste da Índia a partir de Kanchipuram, exercendo notável influência cultural sobre o sul da Ásia. Pioneiros da arquitetura dravídica em pedra, deixaram os célebres monumentos de Mamallapuram." }],
  Rashtrakuta: [{ from: 753, to: 982, text: "A dinastia Rashtrakuta dominou grande parte do Decã, na Índia, tornando-se uma das maiores potências do subcontinente. Foram grandes mecenas das artes, patrocinando os templos rupestres de Ellora, incluindo o monumental templo de Kailasa." }],
  "Chola state": [{ from: 848, to: 1279, text: "O Império Chola, do sul da Índia, tornou-se uma das maiores potências marítimas de seu tempo sob Rajaraja I e Rajendra I, projetando poder até o Sudeste Asiático. Destacou-se pela administração eficiente, pelos grandes templos dedicados a Xiva e pela refinada escultura em bronze." }],
  Cholas: [{ from: 848, to: 1279, text: "A dinastia Chola foi um dos mais duradouros e poderosos impérios do sul da Índia, com expedições navais que alcançaram o Sudeste Asiático. Destacou-se pela administração eficiente, pela arte em bronze e por grandiosos templos como o de Brihadeeswara." }],
  Vijayanagara: [{ from: 1336, to: 1646, text: "O Império de Vijayanagara ergueu-se no sul da Índia como baluarte hindu diante dos sultanatos islâmicos do Decã. Sob dinastias como a Tuluva e o reinado de Krishnadevaraya, alcançou grande prosperidade comercial e esplendor arquitetônico, até ser abalado pela derrota de Talikota em 1565." }],
  "Sultanate of Delhi": [{ from: 1206, to: 1526, text: "O Sultanato de Delhi foi uma sucessão de dinastias muçulmanas que dominaram o norte da Índia a partir de 1206, começando com a dinastia Mameluca. Ao longo de séculos, sultões como Alauddin Khalji e a dinastia Tughlaq expandiram e defenderam o território contra invasões mongóis. O sultanato introduziu a arquitetura indo-islâmica e novas estruturas administrativas antes de ser suplantado pelos mogóis." }],
  "Maratha Confederacy": [{ from: 1674, to: 1818, text: "A Confederação Marata surgiu na Índia central e ocidental a partir do reino fundado por Shivaji, desafiando o domínio mogol. Organizada como uma aliança de chefes militares sob os peshwas, tornou-se a principal potência do subcontinente antes de ser derrotada pelos britânicos." }],
  "Mughal Empire": [{ from: 1526, to: 1857, text: "O Império Mogol foi fundado por Babur em 1526 após a vitória em Panipat, unificando grande parte do subcontinente indiano sob domínio muçulmano. Sob Akbar, Jahangir e Shah Jahan, floresceu uma cultura sincrética célebre por monumentos como o Taj Mahal e por uma administração sofisticada. A partir do século XVIII, o império fragmentou-se e sucumbiu à expansão britânica, sendo formalmente extinto em 1857." }],
  "Ghaznavid Emirate": [{ from: 977, to: 1186, text: "O Emirado Gaznévida foi uma dinastia de origem turca centrada em Gásni, no atual Afeganistão. Sob Mahmud de Gásni, realizou numerosas campanhas na Índia e tornou-se um importante mecenas da cultura persa-islâmica." }],

  // === Steppe / Central Asian / Islamic empires ===
  "Mongol Empire": [{ from: 1206, to: 1368, text: "O Império Mongol, fundado por Gêngis Khan, tornou-se o maior império terrestre contíguo da história, estendendo-se da Coreia à Europa Oriental. Sua cavalaria e organização militar permitiram conquistas rápidas e a integração de rotas comerciais euroasiáticas sob a chamada Pax Mongolica. Após a morte de Gêngis, o império dividiu-se em canatos que gradualmente se desintegraram." }],
  "Great Khanate": [{ from: 1260, to: 1368, text: "O Grande Canato foi a porção central do Império Mongol liderada pelo Grande Cã, especialmente sob Kublai Khan, que estabeleceu a dinastia Yuan na China. Nominalmente supremo sobre os demais canatos, na prática concentrou-se no domínio do Leste Asiático. Sua autoridade declinou com revoltas e com a expulsão dos mongóis da China pelos Ming." }],
  "Golden Horde": [{ from: 1242, to: 1502, text: "A Horda de Ouro foi o canato mongol-turco surgido da divisão do império de Gêngis Khan, dominando as estepes russas e a Ásia central ocidental. Impôs tributo aos principados russos por mais de dois séculos, antes de fragmentar-se em canatos menores e ser extinta por rivais tártaros e russos." }],
  "Crimean Khanate": [{ from: 1441, to: 1783, text: "O Canato da Crimeia, herdeiro da Horda de Ouro e governado pela dinastia Girai, tornou-se vassalo do Império Otomano no fim do século XV. Sustentado em grande parte por incursões e pelo comércio de escravos nas terras eslavas, foi por fim anexado pela Rússia de Catarina II." }],
  "Timurid Empire": [{ from: 1370, to: 1507, text: "O Império Timúrida foi fundado por Tamerlão (Timur), conquistador turco-mongol que ergueu um vasto domínio a partir da Ásia Central. Samarcanda, sua capital, tornou-se um centro brilhante de arte, ciência e arquitetura islâmica. Após a morte de Timur, disputas sucessórias fragmentaram o império, embora seu legado cultural tenha inspirado o posterior Império Mogol." }],
  "Samanid Empire": [{ from: 819, to: 999, text: "O Império Samânida, de origem persa, governou a Transoxiana e o Grande Coração a partir de centros como Bucara e Samarcanda. Foi um brilhante foco de renascimento cultural persa e do saber islâmico, patrocinando poetas e sábios, até cair diante de dinastias turcas emergentes." }],
  "Seljuk Empire": [{ from: 1037, to: 1194, text: "O Império Seljúcida, fundado por turcos oguzes, dominou a Pérsia, a Mesopotâmia e a Anatólia, tornando-se protetor do califado abássida. Sua vitória em Manziquerta, em 1071, abriu a Anatólia à colonização turca e ajudou a desencadear as Cruzadas, antes da fragmentação em Estados sucessores." }],
  "Abbasid Caliphate": [{ from: 750, to: 1258, text: "O Califado Abássida derrubou os Omíadas e transferiu o centro do mundo islâmico para Bagdá. Presidiu a uma era de ouro da ciência, filosofia, medicina e tradução do saber grego, com instituições como a Casa da Sabedoria. Enfraquecido politicamente ao longo dos séculos, foi encerrado pela conquista mongol de Bagdá em 1258." }],
  "Umayyad Caliphate": [{ from: 661, to: 750, text: "O Califado Omíada, com capital em Damasco, foi a primeira grande dinastia hereditária do Islã e presidiu à maior expansão territorial árabe. Seu domínio estendeu-se da Península Ibérica à Ásia Central, difundindo a língua árabe e a administração islâmica. Foi derrubado pela revolução abássida, embora um ramo sobrevivente tenha fundado o emirado de Córdoba na Espanha." }],
  "Fatimid Caliphate": [{ from: 909, to: 1171, text: "O Califado Fatímida foi um Estado xiita ismaelita que dominou o norte da África e depois o Egito, onde fundou a cidade do Cairo. Rival dos califados abássida e omíada, promoveu comércio próspero e criou a célebre universidade de Al-Azhar. Seu poder declinou por crises internas até ser suprimido por Saladino, que restaurou o sunismo no Egito." }],
  "Ottoman Empire": [{ from: 1299, to: 1922, text: "O Império Otomano surgiu na Anatólia e cresceu até se tornar uma das maiores potências do mundo, controlando territórios na Europa, Ásia e África. A conquista de Constantinopla em 1453 marcou o fim do Império Bizantino e consolidou seu poder, atingindo o auge sob Solimão, o Magnífico. Após séculos de declínio gradual, o império desmoronou depois da Primeira Guerra Mundial, dando lugar à República da Turquia." }],
  "Safavid Empire": [{ from: 1501, to: 1736, text: "O Império Safávida governou a Pérsia a partir de 1501, quando o xá Ismail I fundou a dinastia e estabeleceu o islamismo xiita como religião oficial, moldando a identidade religiosa do Irã até hoje. Sob o xá Abbas I, o império alcançou seu apogeu cultural e militar, com Isfahan tornando-se um centro esplendoroso de arte e arquitetura. Rivalizou constantemente com o Império Otomano antes de entrar em declínio e ruir diante de invasores afegãos." }],

  // === Persia / Caucasus / Arabia (long-lived) ===
  Persia: [
    { from: -550, to: -330, text: "O Império Aquemênida, primeira grande manifestação da Pérsia antiga, foi fundado por Ciro, o Grande, e estendeu-se do Egito ao vale do Indo. Célebre por sua administração descentralizada em satrapias, estradas reais e tolerância cultural, foi conquistado por Alexandre, o Grande." },
    { from: 224, to: 651, text: "O Império Sassânida restaurou o poder persa, promovendo o zoroastrismo como religião oficial e rivalizando com Roma e Bizâncio por séculos. Foi um centro de arte, arquitetura e ciência antes de sucumbir à expansão árabe-islâmica no século VII." },
    { from: 1501, to: 1979, text: "A Pérsia moderna, sob dinastias como os Safávidas, os Cajares e os Pahlavi, consolidou o xiismo como identidade nacional e disputou influência com potências vizinhas e europeias. O país foi oficialmente renomeado Irã em 1935 e tornou-se república após a Revolução de 1979." },
  ],
  Georgia: [
    { from: -300, to: 580, text: "Os antigos reinos georgianos da Ibéria e da Cólquida ocupavam o Cáucaso Sul, região disputada entre Roma e a Pérsia. A adoção do cristianismo no início do século IV moldou profundamente sua cultura e identidade." },
    { from: 1008, to: 1490, text: "O Reino da Geórgia unificado alcançou sua Idade de Ouro sob monarcas como David IV e a rainha Tamar, expandindo territórios e florescendo nas artes e nas letras. As invasões mongóis e timúridas enfraqueceram o reino, que acabou fragmentado." },
    { from: 1991, to: 2024, text: "A Geórgia moderna reconquistou a independência com o colapso da União Soviética em 1991. Desde então, o país busca aproximação com o Ocidente, enfrentando conflitos territoriais e tensões com a Rússia." },
  ],
  Armenia: [
    { from: 301, to: 1045, text: "Na Antiguidade tardia e no período medieval, a Armênia destacou-se por ter sido o primeiro Estado a adotar oficialmente o cristianismo, em 301. Governada por dinastias como os Arsácidas e os Bagrátidas, oscilou entre a independência e a submissão a impérios vizinhos como Roma, Pérsia e Bizâncio. O reino Bagrátida floresceu com sua capital em Ani antes de cair sob domínio bizantino e seljúcida." },
    { from: 1918, to: 2024, text: "No período moderno, os armênios sofreram o genocídio perpetrado pelo Império Otomano durante a Primeira Guerra Mundial, um dos maiores traumas de sua história. Uma breve república independente surgiu em 1918, logo absorvida pela União Soviética. A Armênia recuperou plena independência em 1991, após a dissolução da URSS." },
  ],
  "Nabatean Kingdom": [{ from: -312, to: 106, text: "Reino de comerciantes árabes centrado na cidade rupestre de Petra, os nabateus prosperaram controlando as rotas de caravanas de incenso e especiarias entre a Arábia, o Levante e o Mediterrâneo. Dominavam sofisticadas técnicas de gestão da água no deserto antes de serem anexados pelo Império Romano em 106 d.C." }],
  Saba: [{ from: -800, to: 275, text: "Reino situado no sul da Arábia, no atual Iêmen, Sabá enriqueceu com o comércio de incenso e mirra e com a agricultura irrigada pela grande represa de Marib. Associada na tradição à lendária rainha de Sabá, foi uma das mais influentes civilizações da Arábia antiga." }],
  "Himyarite Kingdom": [{ from: -110, to: 525, text: "Sucedendo Sabá como potência dominante do sul da Arábia, o Reino Himiarita unificou a região e controlou lucrativas rotas comerciais. Notabilizou-se por adotar o monoteísmo, incluindo o judaísmo entre suas elites, antes de cair sob invasões aksumitas e persas." }],

  // === Europe ===
  "Frankish Kingdom": [{ from: 481, to: 751, text: "O Reino Franco foi consolidado por Clóvis I, da dinastia merovíngia, que unificou as tribos francas e converteu-se ao cristianismo católico. Sucessor do poder romano na Gália, lançou as bases políticas e religiosas da futura Europa ocidental, apesar das repetidas divisões dinásticas do território." }],
  "Carolingian Empire": [{ from: 800, to: 888, text: "O Império Carolíngio atingiu seu ápice com Carlos Magno, coroado imperador em 800, reunindo grande parte da Europa ocidental sob domínio franco. Promoveu o chamado Renascimento Carolíngio nas letras e nas artes, mas fragmentou-se após o Tratado de Verdun, dando origem a França e Alemanha." }],
  "Holy Roman Empire": [{ from: 800, to: 1806, text: "O Sacro Império Romano-Germânico teve origem na coroação de Carlos Magno em 800 e consolidou-se como uma entidade política da Europa Central, especialmente sob Otão I. Foi uma confederação descentralizada de reinos, ducados e cidades livres, unidos sob um imperador eleito, frequentemente em tensão com o papado. Enfraquecido por guerras religiosas e fragmentação, foi dissolvido em 1806 durante as guerras napoleônicas." }],
  Visigoths: [{ from: 418, to: 711, text: "Os visigodos foram um povo germânico que, após saquear Roma em 410, estabeleceu um reino na Gália e depois na Península Ibérica, com capital em Toledo. Convertidos do arianismo ao catolicismo, elaboraram códigos legais influentes até serem varridos pela conquista muçulmana de 711." }],
  Ostrogoths: [{ from: 493, to: 553, text: "Os ostrogodos, liderados por Teodorico, o Grande, fundaram um reino na Itália após derrotar Odoacro, preservando boa parte das instituições romanas. Esse Estado, marcado por relativa tolerância entre godos e romanos, foi destruído pela reconquista bizantina de Justiniano nas Guerras Góticas." }],
  Vandals: [{ from: 435, to: 534, text: "Os vândalos, povo germânico, migraram pela Europa até estabelecer um reino no norte da África, com capital em Cartago. Dotados de forte poder naval, saquearam Roma em 455 e dominaram o Mediterrâneo ocidental, até serem conquistados pelo general bizantino Belisário." }],
  Huns: [{ from: 370, to: 469, text: "Os hunos foram um povo nômade das estepes que irrompeu na Europa, pressionando as tribos germânicas e abalando o Império Romano. Sob Átila, o \"Flagelo de Deus\", formaram um vasto império de tributos que ameaçou tanto Roma quanto Constantinopla, mas ruiu logo após a morte de seu líder." }],
  Avars: [{ from: 567, to: 822, text: "Os ávaros foram um povo nômade de origem centro-asiática que fundou um poderoso canato na planície da Panônia, na Europa central. Aliados e rivais de Bizâncio, dominaram povos eslavos vizinhos por mais de dois séculos, até serem esmagados pelas campanhas de Carlos Magno." }],
  Khazars: [{ from: 650, to: 969, text: "Os cazares construíram um extenso canato entre o mar Cáspio e o mar Negro, controlando rotas comerciais entre a Europa, a Ásia e o mundo islâmico. Célebres pela conversão de sua elite ao judaísmo, serviram de barreira à expansão árabe rumo ao norte, até serem derrotados pela Rus de Kiev." }],
  "Kievan Rus": [{ from: 882, to: 1240, text: "A Rus de Kiev foi uma federação de tribos eslavas orientais liderada por príncipes varegues, consolidada em torno de Kiev a partir do fim do século IX. Sob Vladimir I e Iaroslav, o Sábio, adotou o cristianismo ortodoxo em 988 e floresceu cultural e comercialmente. Fragmentada por disputas dinásticas, foi destruída pela invasão mongol em 1240." }],
  "Russian Empire": [{ from: 1721, to: 1917, text: "O Império Russo foi proclamado em 1721 por Pedro, o Grande, após vitórias na Grande Guerra do Norte, iniciando uma era de modernização e expansão. Sob czares como Catarina, a Grande, tornou-se uma das maiores potências da Europa, estendendo-se da Polônia ao Pacífico. Marcado por autocracia e servidão, ruiu em 1917 com a Revolução Russa e a abdicação de Nicolau II." }],
  USSR: [{ from: 1922, to: 1991, text: "A União Soviética foi fundada em 1922 após a Revolução Bolchevique e a guerra civil, estabelecendo o primeiro Estado socialista sob o Partido Comunista. Industrializou-se rapidamente sob Stalin, teve papel decisivo na derrota do nazismo e emergiu como superpotência durante a Guerra Fria. Reformas e tensões internas levaram à sua dissolução em 1991." }],
  Portugal: [
    { from: 1139, to: 1415, text: "Portugal surgiu como reino independente quando Afonso Henriques afirmou sua soberania e avançou na Reconquista contra os muçulmanos. Ao longo dos séculos seguintes, consolidou suas fronteiras, praticamente definitivas já no século XIII, e firmou alianças duradouras, como a que manteve com a Inglaterra." },
    { from: 1415, to: 1822, text: "Com a tomada de Ceuta e as viagens de exploração patrocinadas pelo Infante Dom Henrique, Portugal inaugurou a era dos Descobrimentos. Construiu um vasto império marítimo e comercial que se estendia do Brasil à Índia e à China, tornando-se pioneiro da expansão europeia ultramarina." },
    { from: 1822, to: 2000, text: "Com a independência do Brasil e as revoluções liberais, Portugal entrou na era moderna em meio a instabilidade política. Passou pela monarquia constitucional, pela Primeira República, pela longa ditadura do Estado Novo e, após a Revolução dos Cravos de 1974, consolidou-se como democracia europeia." },
  ],
  Castile: [
    { from: 1065, to: 1230, text: "Castela emergiu como reino no centro-norte da Península Ibérica, protagonizando a Reconquista contra os reinos muçulmanos do sul. Suas conquistas e o vigor de figuras como o Cid marcaram sua ascensão, culminando na união definitiva com o vizinho reino de León." },
    { from: 1230, to: 1516, text: "Unida a León, a Coroa de Castela tornou-se a maior potência ibérica, avançando pela Andaluzia e desenvolvendo instituições como as Cortes. O casamento de Isabel I com Fernando de Aragão uniu as duas coroas, lançando as bases da monarquia espanhola e patrocinando a viagem de Colombo." },
  ],
  "Aragón": [{ from: 1035, to: 1516, text: "O Reino de Aragão, no nordeste da Península Ibérica, expandiu-se ao unir-se ao condado de Barcelona, formando a Coroa de Aragão. Tornou-se uma potência mediterrânea, dominando Valência, Baleares, Sardenha, Sicília e Nápoles, até a união dinástica com Castela sob os Reis Católicos." }],
  France: [
    { from: 843, to: 1453, text: "Nascida da partilha do Império Carolíngio, a França medieval foi governada pela dinastia capetiana, que gradualmente ampliou o poder real sobre os grandes senhores feudais. O período foi marcado pela consolidação territorial e pela longa Guerra dos Cem Anos contra a Inglaterra, na qual Joana d'Arc se tornou símbolo nacional." },
    { from: 1453, to: 1789, text: "Sob dinastias como Valois e Bourbon, a França caminhou para a monarquia absolutista, cujo ápice foi o reinado de Luís XIV em Versalhes. Tornou-se potência dominante na Europa, apesar das guerras religiosas e das crescentes tensões sociais e financeiras que antecederam a Revolução." },
    { from: 1789, to: 2000, text: "A Revolução Francesa de 1789 derrubou o Antigo Regime e difundiu os ideais de liberdade, igualdade e fraternidade por todo o continente. Após o império napoleônico, a França alternou monarquias, repúblicas e impérios, atravessou duas guerras mundiais e afirmou-se como república democrática e pilar da integração europeia." },
  ],
  England: [
    { from: 927, to: 1485, text: "Unificada por volta do século X sob os reis de Wessex, a Inglaterra medieval foi moldada pela conquista normanda de 1066 e pela gradual formação de instituições como o Parlamento e a Magna Carta. O período foi marcado por guerras dinásticas, incluindo a Guerra dos Cem Anos contra a França e a Guerra das Rosas entre casas nobres rivais." },
    { from: 1485, to: 1707, text: "Sob as dinastias Tudor e Stuart, a Inglaterra consolidou o poder monárquico, rompeu com Roma na Reforma e iniciou sua expansão marítima e colonial. Foi um período de intensa efervescência cultural e de conflitos religiosos e constitucionais que culminaram na Guerra Civil e na Revolução Gloriosa." },
    { from: 1707, to: 1900, text: "Com a união com a Escócia em 1707, a Inglaterra tornou-se o núcleo da Grã-Bretanha e de um vasto império global. Berço da Revolução Industrial, transformou-se em potência econômica e naval dominante ao longo dos séculos XVIII e XIX." },
  ],
  "Poland-Lithuania": [{ from: 1569, to: 1795, text: "A União de Lublin de 1569 fundiu o Reino da Polônia e o Grão-Ducado da Lituânia em uma vasta comunidade política conhecida como a República das Duas Nações. Notável por sua monarquia eletiva e pela nobreza politicamente poderosa, foi um dos maiores Estados da Europa antes de ser dividida entre potências vizinhas no fim do século XVIII." }],
  Sweden: [
    { from: 1000, to: 1523, text: "Emergindo da era viking, a Suécia medieval consolidou-se gradualmente como reino cristão e ingressou na União de Kalmar com a Dinamarca e a Noruega em 1397. Tensões com o domínio dinamarquês marcaram os séculos seguintes." },
    { from: 1523, to: 1721, text: "Sob Gustavo Vasa, a Suécia rompeu com a União de Kalmar e afirmou sua independência, adotando a Reforma Protestante. No século XVII tornou-se uma grande potência do Báltico, com forte atuação na Guerra dos Trinta Anos." },
    { from: 1721, to: 1900, text: "Após o declínio de seu império báltico na Grande Guerra do Norte, a Suécia perdeu influência militar mas desenvolveu instituições parlamentares e reformas internas. Uniu-se à Noruega em 1814 e manteve uma política de neutralidade ao longo do século XIX." },
  ],
  "Kalmar Union": [{ from: 1397, to: 1523, text: "Formada em 1397, a União de Kalmar reuniu sob uma única monarquia os reinos da Dinamarca, da Suécia e da Noruega. Apesar de unir a Escandinávia por mais de um século, foi marcada por tensões internas e pela resistência sueca ao domínio dinamarquês, dissolvendo-se com a ascensão de Gustavo Vasa." }],
  Prussia: [
    { from: 1525, to: 1701, text: "Surgida da secularização do Estado da Ordem Teutônica, a Prússia começou como ducado ligado ao Brandemburgo sob a dinastia Hohenzollern. Ao longo do século XVII consolidou seus territórios dispersos e fortaleceu o poder centralizado." },
    { from: 1701, to: 1871, text: "Elevada a reino em 1701, a Prússia tornou-se uma grande potência militar europeia sob Frederico, o Grande. Sua disciplina administrativa e força militar fizeram dela o Estado que lideraria a unificação da Alemanha em 1871." },
  ],
  Austria: [
    { from: 1156, to: 1526, text: "Estabelecida como ducado em 1156, a Áustria tornou-se o centro do poder da dinastia Habsburgo a partir do século XIII. Sua posição estratégica no coração da Europa Central fez dela um núcleo político e dinástico de crescente importância." },
    { from: 1526, to: 1804, text: "Sob os Habsburgos, a Áustria reuniu vastos territórios e assumiu papel central no Sacro Império Romano-Germânico. Defendeu a Europa Central contra a expansão otomana e tornou-se baluarte da Contrarreforma católica." },
    { from: 1804, to: 1918, text: "Proclamada Império Austríaco em 1804 e reorganizada como Áustria-Hungria em 1867, tornou-se um Estado multinacional que abrigava numerosos povos. As tensões nacionalistas internas contribuíram para seu colapso ao fim da Primeira Guerra Mundial." },
  ],
  "Austro-Hungarian Empire": [{ from: 1867, to: 1918, text: "Criado pelo Compromisso de 1867, o Império Austro-Húngaro foi uma monarquia dual que unia a Áustria e a Hungria sob o soberano Habsburgo. Vasto e multiétnico, enfrentou crescentes tensões nacionalistas e desintegrou-se ao término da Primeira Guerra Mundial." }],
  Pergamon: [{ from: -281, to: -133, text: "O Reino de Pérgamo, na Anatólia ocidental, ascendeu sob a dinastia atálida após a fragmentação do império de Alexandre. Famoso por sua monumental biblioteca, seu altar de Zeus e o mecenato às artes, foi legado a Roma pelo último rei, Átalo III." }],
  "Odrysian Kingdom": [{ from: -480, to: -46, text: "O Reino Odrísio foi a mais poderosa entidade política dos trácios, unificando tribos nos Bálcãs orientais. Prosperou pelo comércio e pela metalurgia, oscilando entre a independência e a submissão a persas, macedônios e, por fim, a Roma." }],

  // === Africa ===
  Kush: [{ from: -1070, to: -300, text: "O Reino de Cuxe emergiu na Núbia, ao sul do Egito, tornando-se uma potência que chegou a conquistar o próprio Egito e a governá-lo como a XXV dinastia. Centrado inicialmente em Napata, absorveu e adaptou tradições egípcias, incluindo a construção de pirâmides e o culto a Amón. Posteriormente transferiu seu centro para Meroé, prolongando a civilização núbia por séculos." }],
  Meroe: [{ from: -300, to: 350, text: "Meroé foi a capital do reino de Cuxe em seu período tardio, situada na atual Sudão, ao sul do Egito. Tornou-se um importante centro de produção de ferro e comércio, com pirâmides próprias e uma escrita meroítica ainda pouco decifrada. O reino declinou por volta do século IV, sofrendo pressão de Axum." }],
  Axum: [{ from: 100, to: 940, text: "O Reino de Axum foi uma potência comercial no norte da atual Etiópia e Eritreia, conectando África, Arábia e o mundo mediterrâneo pelo mar Vermelho. Cunhou sua própria moeda, ergueu grandes estelas e adotou o cristianismo no século IV sob o rei Ezana. Declinou a partir do século VII com a ascensão do comércio islâmico e mudanças ambientais." }],
  Numidia: [{ from: -202, to: -46, text: "A Numídia foi um reino berbere no norte da África, correspondente a partes da atual Argélia, unificado por Masinissa como aliado de Roma contra Cartago. Após um período de prosperidade e conflitos internos, foi anexada pela República Romana como província no rescaldo das guerras civis." }],
  Nobatia: [{ from: 350, to: 650, text: "Nobátia foi o mais setentrional dos reinos cristãos núbios, estabelecido após a queda de Méroe entre a primeira e a terceira catarata do Nilo. Cristianizada no século VI, acabou incorporada ao reino vizinho de Makúria, com o qual passou a formar uma única entidade política." }],
  Makkura: [{ from: 340, to: 1317, text: "Makúria foi um dos reinos cristãos da Núbia medieval, situado no vale do Nilo, com capital em Dongola. Convertida ao cristianismo no século VI, resistiu por séculos à expansão islâmica graças a um pacto com o Egito, antes de declinar sob pressão árabe e mameluca." }],
  Alwa: [{ from: 500, to: 1504, text: "Álua (Alódia) foi o mais meridional dos três reinos cristãos da Núbia, com capital em Soba, próxima à atual Cartum. Rica e populosa segundo relatos medievais, manteve o cristianismo por quase um milênio até sucumbir à migração árabe e ao avanço do sultanato de Sennar." }],
  Ethiopia: [
    { from: -100, to: 940, text: "Na Antiguidade, a região da Etiópia foi dominada pelo poderoso Reino de Axum, uma potência comercial e uma das primeiras a adotar o cristianismo. Ligava a África ao mundo mediterrâneo e árabe por meio do mar Vermelho, cunhando moeda e erguendo monumentos. Seu declínio abriu caminho para os reinos cristãos medievais do planalto etíope." },
    { from: 1137, to: 1974, text: "A Etiópia medieval e moderna consolidou-se sob dinastias cristãs como a Zagué, construtora das igrejas rupestres de Lalibela, e a Salomônica, que reivindicava descendência do rei Salomão. Resistiu de forma singular à colonização europeia, derrotando a Itália em Adwa em 1896. A milenar monarquia terminou em 1974 com a deposição do imperador Hailé Selassié." },
  ],
  "Empire of Ghana": [{ from: 300, to: 1240, text: "O Império de Gana, também chamado Wagadu, foi um dos primeiros grandes Estados da África Ocidental, situado entre os atuais Mali e Mauritânia. Enriqueceu controlando o comércio transsaariano de ouro e sal, tornando-se lendário por sua prosperidade. Enfraquecido por conflitos e pela seca, foi absorvido pelo emergente Império do Mali no século XIII." }],
  Mali: [{ from: 1235, to: 1670, text: "O Império do Mali foi fundado por Sundiata Keita por volta de 1235 e tornou-se a potência dominante da África Ocidental. Sob Mansa Musa, célebre por sua fabulosa riqueza em ouro, o império controlou o comércio transsaariano e fez de Timbuktu um centro de aprendizado islâmico. Declinou a partir do século XV diante de revoltas e da ascensão de Songhai." }],
  Songhai: [{ from: 1464, to: 1591, text: "O Império Songhai foi o maior dos impérios da África Ocidental, dominando a curva do rio Níger a partir de meados do século XV sob Sonni Ali e Askia Muhammad. Controlou o comércio transsaariano de ouro e sal e transformou Gao e Timbuktu em centros de riqueza e erudição islâmica. Foi derrotado por uma invasão marroquina armada com pólvora em 1591." }],
  Kanem: [{ from: 700, to: 1380, text: "Império situado a nordeste do lago Chade, Kanem ergueu-se sobre o comércio transaariano de sal, cobre e escravizados. Sob a dinastia Sefawa adotou o islã no século XI, antes de transferir seu núcleo de poder para Bornu diante de pressões internas e externas." }],
  "Bornu-Kanem": [{ from: 1380, to: 1893, text: "Após o deslocamento do centro de poder do antigo Kanem para a região de Bornu, o império Kanem-Bornu renasceu a oeste do lago Chade sob a dinastia Sefawa. Islâmico e mercantil, controlou as rotas transaarianas por séculos, atingindo seu apogeu sob Idris Alooma no fim do século XVI." }],
  Oyo: [{ from: 1400, to: 1836, text: "Poderoso reino iorubá no atual sudoeste da Nigéria, Oyo destacou-se por sua eficiente cavalaria e por uma estrutura política que limitava o poder do rei, o Alafin, por meio de conselhos. Prosperou com o comércio, incluindo o tráfico atlântico, antes de entrar em declínio no início do século XIX." }],
  Benin: [{ from: 1180, to: 1897, text: "O Reino de Benin, do povo edo, floresceu no atual sul da Nigéria e ficou célebre por sua corte sofisticada e por suas notáveis placas e esculturas de bronze e marfim. Estado centralizado e militarmente forte, manteve intenso comércio com europeus até ser destruído por uma expedição britânica em 1897." }],
  Dahomey: [{ from: 1600, to: 1904, text: "Reino do povo fon no atual Benim, Daomé caracterizou-se por um Estado altamente centralizado e militarizado, célebre por seu corpo de guerreiras conhecidas como as amazonas. Sua economia esteve fortemente ligada ao tráfico atlântico de escravizados antes da conquista francesa no início do século XX." }],
  Asante: [{ from: 1701, to: 1901, text: "Confederação do povo akan no atual Gana, o Império Asante foi fundado em torno do símbolo unificador do Banco de Ouro. Enriqueceu com o comércio de ouro e a expansão militar, resistindo por décadas à colonização britânica antes de ser anexado no início do século XX." }],
  "Sokoto Caliphate": [{ from: 1804, to: 1903, text: "O Califado de Sokoto foi um vasto Estado islâmico da África Ocidental, fundado por Usman dan Fodio após uma jihad de renovação religiosa. Tornou-se um dos maiores impérios da região, com forte organização política e intelectual, até ser conquistado pelos britânicos." }],
  Buganda: [{ from: 1300, to: 1900, text: "Reino situado às margens do lago Vitória, no atual Uganda, Buganda desenvolveu uma administração centralizada sob o soberano conhecido como Kabaka. Tornou-se um dos Estados mais poderosos da região dos Grandes Lagos africanos antes de integrar-se ao protetorado britânico." }],
  Congo: [{ from: 1390, to: 1857, text: "O Reino do Congo (Kongo) foi um poderoso Estado da África Centro-Ocidental, na região do atual norte de Angola e da República Democrática do Congo. Seus reis converteram-se ao cristianismo após o contato com Portugal no fim do século XV, e o reino foi profundamente afetado pelo comércio e pelo tráfico atlântico de escravizados." }],
  Ndongo: [{ from: 1500, to: 1671, text: "Reino do povo mbundu situado no atual Angola, Ndongo era governado por um soberano chamado Ngola, termo que originou o nome do país. Notabilizou-se pela resistência à expansão portuguesa, sobretudo sob a liderança da rainha Nzinga, antes de sucumbir ao domínio colonial." }],
  Mwenemutapa: [{ from: 1430, to: 1760, text: "O Reino do Monomotapa (Mwenemutapa) estendeu-se pelo planalto entre os rios Zambeze e Limpopo, no atual Zimbábue e Moçambique. Herdeiro da tradição do Grande Zimbábue, prosperou com o comércio de ouro e marfim com mercadores swahili e portugueses antes de fragmentar-se." }],
  "Great Zimbabwe": [{ from: 1100, to: 1450, text: "Grande Zimbábue foi a capital de um próspero reino da África Austral, célebre por suas imponentes muralhas de pedra erguidas sem argamassa. Prosperou entre os séculos XII e XV graças à criação de gado e ao comércio de ouro e marfim com a costa do Índico. A cidade foi gradualmente abandonada, possivelmente devido ao esgotamento de recursos e a mudanças nas rotas comerciais." }],
  Zulu: [{ from: 1816, to: 1897, text: "O Reino Zulu emergiu no sudeste da África sob a liderança de Shaka, que unificou clãs de língua nguni e reorganizou o exército com táticas e armas inovadoras. No auge, tornou-se uma potência militar regional, resistindo à expansão colonial até a Guerra Anglo-Zulu de 1879, quando foi por fim incorporado ao domínio britânico." }],
  "Almohad Caliphate": [{ from: 1121, to: 1269, text: "O Califado Almóada foi um império berbere reformista que dominou o noroeste da África e a Península Ibérica muçulmana. Impôs uma interpretação rigorosa do islã e legou obras notáveis, mas ruiu após a derrota de Las Navas de Tolosa." }],
  "Almoravid dynasty": [{ from: 1040, to: 1147, text: "A dinastia Almorávida foi um movimento berbere que unificou o Magrebe e o Alandalus sob uma vertente austera do islã. Deteve o avanço cristão na Ibéria por um tempo antes de ser suplantada pelos almóadas." }],
  "Hafsid Caliphate": [{ from: 1229, to: 1574, text: "O Califado Háfsida governou a Ifríquia, correspondente à atual Tunísia e regiões vizinhas, a partir de Túnis. Prosperou com o comércio mediterrâneo e o corso, mantendo-se até ser absorvido pelo Império Otomano." }],

  // === East / Southeast Asia ===
  Korea: [
    { from: -2333, to: 668, text: "A tradição situa nas origens da Coreia o reino lendário de Gojoseon, seguido pelo período dos Três Reinos, quando Goguryeo, Baekje e Silla disputaram a península. Foi uma era de formação da cultura coreana, com forte influência budista e chinesa e intensa rivalidade militar entre os reinos." },
    { from: 668, to: 1392, text: "Após a unificação promovida por Silla e, depois, pela dinastia Goryeo, a Coreia consolidou-se como um Estado centralizado e budista. Floresceram as artes, a impressão com tipos móveis e a cerâmica celadon, apesar das invasões mongóis que marcaram os séculos finais desse período." },
    { from: 1392, to: 1948, text: "A dinastia Joseon adotou o confucionismo como ideologia de Estado e criou o alfabeto hangul, moldando a identidade coreana moderna. O reino sofreu invasões e, no início do século XX, foi colonizado pelo Japão, até a libertação e a divisão da península após 1945." },
  ],
  Goryeo: [{ from: 918, to: 1392, text: "Fundada por Wang Geon, a dinastia Goryeo reunificou a península coreana e deu origem ao nome ocidental \"Coreia\". Notabilizou-se pela cerâmica celadon, pela impressão em tipos móveis metálicos e pelo budismo de Estado, resistindo a repetidas invasões mongóis que a tornaram vassala do império de Kublai Khan." }],
  Silla: [{ from: -57, to: 935, text: "Um dos Três Reinos da Coreia, Silla expandiu-se a partir do sudeste da península e, aliada à China Tang, derrotou Baekje e Goguryeo, unificando grande parte da Coreia em 668. A chamada Silla Unificada viveu um apogeu cultural budista antes de declinar em meio a revoltas aristocráticas." }],
  Balhae: [{ from: 698, to: 926, text: "Balhae foi um reino multiétnico que se estendeu pela Manchúria, pelo norte da Coreia e por partes do Extremo Oriente russo, fundado por remanescentes de Goguryeo. Chamado de \"país próspero do leste\", combinou influências coreanas e chinesas antes de ser destruído pelos quitanes." }],
  Japan: [
    { from: -660, to: 1185, text: "Nas eras antiga e clássica, o Japão emergiu de sociedades como a Yayoi e desenvolveu-se sob a corte imperial de Yamato, que consolidou o poder e adotou influências chinesas e coreanas. Nara e depois Heian tornaram-se centros de uma refinada cultura aristocrática, budista e literária. Esse período lançou as bases da identidade cultural, religiosa e política japonesa." },
    { from: 1185, to: 1868, text: "Durante a era feudal, o poder real deslocou-se do imperador para os xoguns e a classe guerreira samurai, iniciando-se com o xogunato Kamakura. Séculos de guerras civis foram seguidos pela unificação e por um longo período de paz e isolamento sob o xogunato Tokugawa. Uma sociedade rigidamente hierárquica floresceu culturalmente enquanto o país permanecia fechado ao exterior." },
    { from: 1868, to: 2024, text: "A partir da Restauração Meiji, em 1868, o Japão modernizou-se rapidamente, industrializando-se e tornando-se uma potência mundial. Após a expansão imperialista e a derrota na Segunda Guerra Mundial, reconstruiu-se como uma democracia pacífica e uma das maiores economias do planeta. Combina hoje tradição milenar com liderança tecnológica global." },
  ],
  Yamato: [{ from: 250, to: 710, text: "O período Yamato marca a formação do Estado japonês antigo em torno da região de Nara, sob uma linhagem imperial em consolidação. Foi uma era de crescente influência chinesa e coreana, com a introdução do budismo e de modelos administrativos continentais." }],
  "Empire of Japan": [{ from: 1868, to: 1947, text: "O Império do Japão nasceu com a Restauração Meiji de 1868, que restaurou o poder imperial e impulsionou rápida modernização e industrialização. Movido por ambições expansionistas, anexou territórios na Ásia e no Pacífico, culminando em sua participação na Segunda Guerra Mundial. A derrota em 1945 pôs fim ao império militarista, seguido por uma nova constituição pacifista em 1947." }],
  "Tokugawa Shogunate": [{ from: 1603, to: 1868, text: "O Xogunato Tokugawa foi estabelecido por Tokugawa Ieyasu em 1603, inaugurando mais de dois séculos de paz e estabilidade conhecidos como período Edo. Adotou uma política de isolamento (sakoku), restringindo severamente o contato com o exterior, enquanto sustentava uma rígida ordem social. Enfraquecido por pressões internas e externas, entregou o poder ao imperador em 1868, encerrando a era feudal." }],
  "Khmer Empire": [{ from: 802, to: 1431, text: "O Império Khmer dominou grande parte do Sudeste Asiático continental a partir de 802, com seu centro na região de Angkor, no atual Camboja. Construiu vastos complexos de templos, como Angkor Wat, e desenvolveu engenhosos sistemas hidráulicos que sustentavam uma população numerosa. Após séculos de esplendor, enfraqueceu diante de pressões regionais e do reino de Ayutthaya, abandonando Angkor em 1431." }],
  "Srivijaya Empire": [{ from: 650, to: 1288, text: "Srivijaya foi um poderoso império marítimo budista centrado em Sumatra, que controlou rotas comerciais estratégicas pelos estreitos de Malaca e Sunda. Prosperou como centro de aprendizado budista e polo do comércio entre a Índia e a China. Seu domínio declinou a partir do século XI diante de rivais como Chola e reinos javaneses." }],
  Champa: [{ from: 192, to: 1832, text: "Champa foi um conjunto de principados hinduístas e depois islamizados do povo cham, ao longo da costa do atual Vietnã central. Prosperou com o comércio marítimo e deixou notável arquitetura em tijolo, mas foi gradualmente absorvido pela expansão vietnamita rumo ao sul." }],
  Funan: [{ from: 68, to: 550, text: "Funan foi um dos mais antigos Estados do Sudeste Asiático, situado no delta do Mekong. Enriquecido pelo comércio entre a Índia e a China, adotou influências indianas na religião e na administração antes de declinar diante do reino sucessor de Chenla." }],
  Dvaravati: [{ from: 550, to: 1100, text: "Dvaravati foi uma cultura mon de orientação budista que floresceu na bacia do rio Chao Phraya, na atual Tailândia. Notável pela arte e pela difusão do budismo Theravada, foi mais uma rede de cidades-Estado do que um império centralizado." }],
  Mataram: [{ from: 716, to: 1016, text: "O Reino de Mataram, em Java central, foi um poderoso Estado hindu-budista responsável por monumentos como Borobudur e Prambanan. A rivalidade entre as dinastias Sailendra e Sanjaya marcou sua história antes de o poder deslocar-se para o leste de Java." }],
  Ayutthaya: [{ from: 1351, to: 1767, text: "O Reino de Ayutthaya foi um poderoso Estado siamês que dominou boa parte do atual território tailandês. Rico centro de comércio internacional e refinada cultura budista, foi destruído por um exército birmanês em 1767." }],
  Sukhothai: [{ from: 1238, to: 1438, text: "Sukhothai é considerado o primeiro reino tailandês, celebrado como uma era de ouro da cultura e da identidade siamesa. Sob o rei Ramkhamhaeng, teria surgido a escrita tailandesa; mais tarde foi absorvido pelo crescente reino de Ayutthaya." }],

  // === The Americas ===
  Olmec: [{ from: -1200, to: -400, text: "Considerada a cultura-mãe da Mesoamérica, a civilização olmeca floresceu nas terras baixas tropicais do golfo do atual México. É famosa pelas colossais cabeças esculpidas em pedra e por lançar bases culturais, religiosas e artísticas herdadas por civilizações posteriores." }],
  "Zapotec Empire": [{ from: -500, to: 900, text: "A civilização zapoteca floresceu no vale de Oaxaca, no México, tendo Monte Albán como seu grande centro urbano a partir de cerca de 500 a.C. Os zapotecas desenvolveram um dos primeiros sistemas de escrita da Mesoamérica, além de calendários e monumentais construções. Monte Albán declinou por volta do ano 900, embora cidades zapotecas persistissem até a chegada dos espanhóis." }],
  "Teotihuacán": [{ from: -100, to: 650, text: "Grande metrópole do centro do atual México, Teotihuacán foi uma das maiores cidades do mundo antigo, com suas imponentes Pirâmides do Sol e da Lua e a ampla Avenida dos Mortos. Exerceu profunda influência comercial e cultural sobre a Mesoamérica antes de seu misterioso declínio." }],
  "Maya chiefdoms and states": [{ from: -2000, to: 250, text: "Nas eras Pré-Clássica, as comunidades maias evoluíram de aldeias agrícolas para cacicados e estados incipientes ao longo de milênios. Surgiram centros como El Mirador e Nakbé, com arquitetura monumental precoce e as bases da escrita e do calendário. Esse longo desenvolvimento preparou o terreno para o esplendor das cidades-estado do período Clássico." }],
  "Maya city-states": [{ from: 250, to: 900, text: "Durante o período Clássico, as cidades-estado maias, como Tikal, Palenque e Calakmul, floresceram nas terras baixas da América Central. Cada cidade era governada por dinastias reais que competiam por prestígio e poder, deixando avanços notáveis em escrita, astronomia e matemática. Um colapso generalizado no século IX levou ao abandono de muitos desses centros nas terras baixas do sul." }],
  "Toltec Empire": [{ from: 900, to: 1168, text: "Os toltecas dominaram o centro do México a partir de sua capital Tula por volta do século X, sucedendo Teotihuacan como potência regional. Reverenciados por civilizações posteriores, como os astecas, tornaram-se sinônimo de refinamento artístico e sabedoria, associados à figura de Quetzalcóatl. Seu domínio ruiu no século XII em meio a conflitos e pressões de povos do norte." }],
  "Aztec Empire": [{ from: 1428, to: 1521, text: "O Império Asteca, ou Tríplice Aliança, dominou o centro do México a partir de 1428, com Tenochtitlan como capital em uma ilha do lago Texcoco. Desenvolveu uma sociedade complexa marcada por tributos, comércio, religião e sacrifícios rituais. Foi conquistado por Hernán Cortés e seus aliados indígenas em 1521, marcando o fim da era pré-colombiana no México central." }],
  Moche: [{ from: 100, to: 700, text: "Cultura que floresceu na costa norte do atual Peru, os moches destacaram-se pela cerâmica realista, pela metalurgia e pela construção de grandes pirâmides de adobe, como as Huacas do Sol e da Lua. Sua sociedade era organizada em torno de senhores guerreiros e de complexos rituais religiosos." }],
  Nazca: [{ from: -100, to: 800, text: "Desenvolvida na costa sul do atual Peru, a cultura Nazca é célebre pelas enigmáticas geoglifos traçadas no deserto, as Linhas de Nazca. Dominava técnicas avançadas de irrigação subterrânea e produziu cerâmica e tecidos de grande refinamento." }],
  "Tiahuanaco Empire": [{ from: 500, to: 1000, text: "Centrado nas margens do lago Titicaca, no altiplano andino, o Estado de Tiwanaku foi um importante centro religioso e político. Sua monumental arquitetura de pedra, como a Porta do Sol, e sua influência cultural irradiaram-se por vasta região dos Andes centro-sul." }],
  "Huari Empire": [{ from: 600, to: 1000, text: "O Império Wari expandiu-se pelos Andes centrais do atual Peru a partir de sua capital homônima, criando uma das primeiras grandes organizações estatais da região. Notabilizou-se pela construção de centros administrativos, extensas redes de estradas e sistemas de terraços agrícolas." }],
  "Chimú Empire": [{ from: 900, to: 1470, text: "Desenvolvido na costa norte do atual Peru, o Império Chimú teve como capital a monumental cidade de barro de Chan Chan. Foi a maior civilização andina antes dos incas, destacando-se pela engenharia hidráulica e pela fina metalurgia, até ser conquistado pelo Império Inca." }],
  "Inca Empire": [{ from: 1438, to: 1533, text: "O Império Inca, chamado Tawantinsuyu, foi o maior império da América pré-colombiana, estendendo-se pelos Andes a partir de 1438. Notável por sua engenharia, terraços agrícolas, estradas e administração centralizada em Cusco, integrou diversos povos sob o domínio do Sapa Inca. Enfraquecido por guerra civil e epidemias, foi conquistado por Francisco Pizarro em 1533." }],

  // === Modern nation-states (shown in recent snapshots) ===
  China: [{ from: 1912, to: 2025, text: "A China moderna emergiu com o fim do império em 1912 e a proclamação da República. Após décadas de guerra civil, invasão japonesa e a vitória comunista de 1949, a República Popular da China tornou-se, sobretudo a partir das reformas econômicas de 1978, uma superpotência e a nação mais populosa do mundo, herdeira de uma das mais antigas civilizações da história." }],
  India: [{ from: 1947, to: 2025, text: "A Índia moderna nasceu como nação independente em 1947, após séculos de domínio britânico e o movimento liderado por Mahatma Gandhi. Tornou-se a maior democracia do mundo e, no século XXI, uma das nações mais populosas e uma economia de crescente peso global, marcada por enorme diversidade cultural, linguística e religiosa." }],
  "United States": [{ from: 1776, to: 2025, text: "Os Estados Unidos surgiram da independência das treze colônias britânicas em 1776 e expandiram-se por todo o continente norte-americano ao longo do século XIX. Após a Guerra Civil, a industrialização e duas guerras mundiais, tornaram-se a principal potência econômica e militar do mundo e um centro de inovação tecnológica e cultural." }],
  "United States of America": [{ from: 1776, to: 2025, text: "Os Estados Unidos da América formaram-se com a independência de 1776 e cresceram de uma república agrária a superpotência global. Sua história inclui a expansão para o oeste, a Guerra Civil e a abolição da escravidão, a ascensão industrial e a liderança econômica, militar e cultural consolidada no século XX." }],
  Brazil: [{ from: 1822, to: 2025, text: "O Brasil tornou-se independente de Portugal em 1822, primeiro como império e, a partir de 1889, como república. Maior país da América do Sul e herdeiro de uma formação marcada por povos indígenas, colonização portuguesa e a diáspora africana, consolidou-se como uma das maiores economias e democracias do mundo, célebre por sua diversidade cultural e natural." }],
  Mexico: [{ from: 1821, to: 2025, text: "O México conquistou a independência da Espanha em 1821, herdando um território que abrigara grandes civilizações como astecas e maias. Após revoluções, perdas territoriais e a Revolução Mexicana de 1910, firmou-se como uma república populosa e uma das principais economias da América Latina, com forte identidade cultural mestiça." }],
  Canada: [{ from: 1867, to: 2025, text: "O Canadá formou-se como confederação em 1867, reunindo colônias britânicas da América do Norte, e alcançou plena soberania ao longo do século XX. Segundo maior país do mundo em área, é uma democracia parlamentar bilíngue, próspera e multicultural, com vastos recursos naturais." }],
  Australia: [{ from: 1901, to: 2025, text: "A Austrália tornou-se uma federação em 1901, unindo as colônias britânicas do continente. Habitada por povos aborígenes há dezenas de milhares de anos antes da colonização europeia, desenvolveu-se como uma democracia estável e economia desenvolvida, ocupando sozinha um continente inteiro." }],
  Russia: [{ from: 1991, to: 2025, text: "A Federação Russa emergiu como Estado independente com a dissolução da União Soviética em 1991, herdeira do Império Russo e da URSS. Maior país do mundo em território, estendendo-se por dois continentes, mantém grande influência geopolítica, vastos recursos naturais e um papel central na política internacional." }],
  Germany: [{ from: 1871, to: 2025, text: "A Alemanha unificou-se como Estado-nação em 1871 sob a liderança da Prússia. Depois de protagonizar as duas guerras mundiais e de ser dividida durante a Guerra Fria, reunificou-se em 1990 e consolidou-se como a maior economia da Europa e um dos pilares da União Europeia." }],
  Italy: [{ from: 1861, to: 2025, text: "A Itália unificou-se como reino em 1861, reunindo os diversos Estados da península após séculos de fragmentação. Berço do Império Romano e do Renascimento, passou pelo período fascista e pelas guerras mundiais antes de tornar-se, em 1946, uma república democrática e uma das maiores economias europeias." }],
  Spain: [{ from: 1516, to: 2025, text: "A Espanha unificou-se sob os Reis Católicos e, no século XVI, construiu um vasto império global que se estendia pelas Américas, Ásia e Europa. Após a perda de suas colônias, a guerra civil e a ditadura de Franco, tornou-se, a partir de 1978, uma democracia parlamentar e um membro ativo da União Europeia." }],
};

function nearestPeriod(periods: EraSummary[], year: number): EraSummary {
  let best = periods[0];
  let bestDist = Infinity;
  for (const p of periods) {
    const dist = year < p.from ? p.from - year : year > p.to ? year - p.to : 0;
    if (dist < bestDist) {
      bestDist = dist;
      best = p;
    }
  }
  return best;
}

// Returns the era-appropriate summary for a territory at a given year,
// or null if the territory has no curated summary. `name` must be the
// original GeoJSON NAME/SUBJECTO (not the translated display name).
export function summaryFor(name: string, year: number): string | null {
  const periods = TERRITORY_SUMMARIES[name];
  if (!periods || periods.length === 0) return null;
  const containing = periods.find((p) => year >= p.from && year <= p.to);
  return (containing ?? nearestPeriod(periods, year)).text;
}
